### ISSUE TITLE
General: add logic to automatically support long running requests for message activites

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#10]
Inbound "reactive" requests will timeout after a few seconds. This is problematic for long requests and the solution is to convert the incoming "reactive" request to a "proactive" request.  To do that you need to call `continueConversation()` off the adapter and create a new `TurnContext` instance. We can simplify this task for developers by adding an option to the `Application` class to do this conversion automatically.

This feature should be off by default as it's not without its side effects:

- If you're bot is running in a shared hosting environment it could get recycled in the middle of a request. This is by far the biggest potential issue. In shared hosting environments you're a candidate for recycling the moment the original inbound request completes. Dedicated hosting environments don't have this requirement so the main general recommendation we should make is that you only turn this feature on if your bot is running in a dedicated hosting environment.
- Shared hosting environments can't accurately bill the customer. Shared hosting environments like Azure Functions bill based on minutes of compute consumed. They do this billing by measuring the length of inbound requests so if you terminate the request early they can't accurately bill you. That's also why they're aggressive about recycling processes with no current requests.
- Bot Framework channels can't detect that the bot failed to process a given activity. This affects logging on the Bot Framework side of things mostly but there is a user facing error log for each channel that won't get properly populated so worth calling out.

**Comment by govil1811** [comment]
P2

**Comment by lifan0127** [comment]
> I see the `longRunningMessages` option is available in the JavaScript implementation of the Application class. However, it doesn't seem to work for me. I am still getting the timeout message after 10-15 seconds (Debug in Teams (Chrome)). Any suggestions? Thanks!
> 
> https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/Application.ts#L129
> 
> ![image](https://private-user-images.githubusercontent.com/7218193/328233963-87d0503c-5c2c-42e4-a616-0400ccaeb292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODIwMTMsIm5iZiI6MTcxNTc4MTcxMywicGF0aCI6Ii83MjE4MTkzLzMyODIzMzk2My04N2QwNTAzYy01YzJjLTQyZTQtYTYxNi0wNDAwY2NhZWIyOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTVUMTQwMTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRiODY4NWE4YTg2ZGRmMGVjYWVlODE1ZWNhZDg4YjcwNjE5MTlkYTU1NzUyYTRhYWRjODI5YThlM2JlYzQzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IB1PqHZeW-yUO9OEQTkUYS10o0ajSfmgqDavq0mSXoU)

Hello @singhk97, would you please advise how we should use this feature? As in my last post, it doesn't appear to work for me. Thanks!
