### ISSUE TITLE
[Chore] JS vision follow-up questions

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#1017]
Due to time constraints, we didn't wait for resolution on outstanding questions, so I will list them here.

- [x] Streamline the ability to add images from memory to storage? [Comment](https://github.com/microsoft/teams-ai/pull/913/files#r1414673876)
    - No, the image does not need to persist beyond the turn., 
- [x] Are we going to limit what types of files can be added? [Comment](https://github.com/microsoft/teams-ai/pull/913/files#r1414675686), [Comment](https://github.com/microsoft/teams-ai/pull/913/files#r1416302308)
    - No, we don't want to limit the types so this can work beyond vision.
- [x] Rename samples to not use 'master [Comment](https://github.com/microsoft/teams-ai/pull/913/files#r1416304911)
- [ ] Clarify what work exactly needs to be done, then file work item [Comment](https://github.com/microsoft/teams-ai/pull/913#discussion_r1416308727)
- [ ] Clean up samples [Comment](https://github.com/microsoft/teams-ai/pull/913#pullrequestreview-1766201213)
    - Manifest images (currently they are chef bot)
    - Update screencaps (chef bot)
    - confirm all names are inclusive

**Comment by Stevenic** [comment]
I'm responding to your comments @corinagum
