### ISSUE TITLE
[PY] Augmentations

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1068]
implement `augmentations` functionality of `JS` SDK https://github.com/microsoft/teams-ai/tree/main/js/packages/teams-ai/src/augmentations
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/1272
```

**Comment by blackchoey** [comment]
Need to add augmentation related logic to PromptManager and PromptTemplate
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/PromptManager.ts#L409-L451
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/PromptTemplate.ts#L40
