### ISSUE TITLE
[PY] Models

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1069]
implement `models` functionality` of `JS` SDK https://github.com/microsoft/teams-ai/tree/main/js/packages/teams-ai/src/models

**Comment by blackchoey** [comment]
Need to add action related logic to PromptManager and PromptTemplate:
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/PromptManager.ts#L305-L312
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/PromptTemplate.ts#L35
