### ISSUE TITLE
[Bug]: Inaccurate doc for JS SDK

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1163]
### Language

Javascript/Typescript

### Version

latest

### Description

Creating this issue to list all the doc issues I found. Better to make them more accurate for our SDK
- [x] There's no return value: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/MemoryFork.ts#L23
- [x] There's no template value: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/TurnState.ts#L464
- [x] Missing doc: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/LayoutEngine.ts#L42-L47

### Reproduction Steps

N/A

**Comment by corinagum** [comment]
Thanks @blackchoey, I'm doing very similar work right now, so I will make these corrections. If you add more to this issue, could you mention me in a comment? I'll check back regularly until I'm done with the PR, too.

**Comment by blackchoey** [comment]
@corinagum   sure, I will update along with my python work.

**Comment by blackchoey** [comment]
@corinagum Another inaccurate doc: the default value for textPrefix should be empty string, not undefined: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/prompts/PromptSectionBase.ts#L33
