### ISSUE TITLE
[Feature Request]: Newer GPT models have support for JSON mode in chat completion API

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1201]
### Scenario

**Context**

Newer models support JSON mode in Chat Completion API which constrains the model to only generate strings that parse into valid JSON object.

> When calling `gpt-4-1106-preview` or `gpt-3.5-turbo-1106,` you can set [response_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) to { "type": "json_object" } to enable JSON mode. When JSON mode is enabled, the model is constrained to only generate strings that parse into valid JSON object.

### Solution

Update the OpenAI's chat completion call when using to enable JSON Model when sequence and monologue augmentation is used along with an allowed model.

**Comment by aacebo** [comment]
https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format

**Comment by Stevenic** [comment]
Should be an easy add and I’d tie it to the augmentation used meaning that if you pick one of the client side augmentations just enable it.
