### ISSUE TITLE
[Bug]: Token calculation is inaccurate in ConversationHistory class

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1225]
### Language

Javascript/Typescript, C#, Python

### Version

latest

### Description

When the conversation history has multiple lines, the ConversationHistory class assumes each line breaks will take 1 token. However  the line breaks will not consume tokens in certain condition. So the actual token length will be slightly shorter than the calculated one in ConversationHistory class.
Should be low priority.

### Reproduction Steps

```bash
Take following conversation history as example, the ConversationHistory thinks the token length is `36`. The actual token length is `34` based on the OpenAI's tokenizer.

assistant: Sure, where would you like to go?
user: I'd like to book a flight
assistant: Hi! How can I help you?
user: Hello
```
```

**Comment by Stevenic** [comment]
The token counting calculations are best effort as they don’t take into account additional tokens that OpenAI adds for the message markers. It’s more than one token so we’re generally undercounting if anything. It’s nearly impossible to get an accurate count

**Comment by corinagum** [comment]
Closing as no-op. gpt-tokenizer gets us as close as we can get to estimate token usage
