### ISSUE TITLE
[Bug]: 04.ai.a.teamsChefBot broken with update to Azure.AI.OpenAI - Could not load type 'Azure.AI.OpenAI.ChatMessage' 

### ISSUE THREAD

**Issue by mjfusa** [microsoft/teams-ai#1234]
### Language

C#

### Version

latest

### Description

When running sample get error: `Could not load type 'Azure.AI.OpenAI.ChatMessage' from assembly 'Azure.AI.OpenAI.`
Looking into this is seems ChatMessage has been deprecated from Azure.AI.OpenAI after version 1.0.0-beta.9.
It looks like Microsoft.Teams.AI.AI.Models creates a ChatMessage in CompletePromptAsync.
Any suggestion for a workaround?

### Reproduction Steps

```bash
1. F5 to run the sample.
2. In Teams enter 'Hi'
3. Note Error message.
...
```

**Comment by singhk97** [comment]
Bumped `Microsoft.Teams.AI` to `v1.1.1`. This issue should be resolved.
