### ISSUE TITLE
[Bug] repair message causing LLM forgetfulness

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1245]
JSON attempted repair message `Return a JSON object that uses the SAY command to say what you're thinking.` causes models (more common in Azure models) to respond with a confused response and lose track of conversation context.

**Comment by singhk97** [comment]
If this is caused by the model is not returning a JSON object, latest updates to OpenAI's chat completion API supports `json_mode`, which ensures the model always returns a JSON object.

**Comment by Stevenic** [comment]
That feature didn’t exist when I coded this logic
