### ISSUE TITLE
Test New Models With Samples

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1271]
OpenAI and Azure OpenAI have released new models and we need to test them with some of our samples to ensure they are working as expected and if not create tickets for follow up work. These new models need to be tested in OpenAI AND Azure OpenAI:

- `text-embedding-3-small`
- `text-embedding-3-large`
- `gpt-4`

Acceptance Criteria:

- RAG is tested using new embeddings models in OAI/AOAI
- Assistants Planner is tested using new `gpt-4` model in OAI/AOAI
- Action Planner is tested using new `gpt-4` model in OAI/AOAI

**Comment by lilyydu** [comment]
Success - Tested LightBot (ActionPlanner) with `gpt-4` on OAI/AOAI for JS
