### ISSUE TITLE
[Bug]: Pylance type error in Python samples

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1304]
### Language

Python

### Version

latest

### Description

Pylance will report following error in Python samples. May need to fix the error as user will see the errors when try the samples.
Mypy does not report the error after test.

> "Application" is not exported from module "teams" Import from "teams.app" instead
> "ApplicationOptions" is not exported from module "teams" Import from "teams.app_options" instead

![image](https://github.com/microsoft/teams-ai/assets/16605901/b97d7201-f9ea-4b31-9c71-e8646c05e503)

### Reproduction Steps

```bash
N/A
```

**Comment by lilyydu** [comment]
Hey @blackchoey, is this in the samples or in our SDK logic?

**Comment by blackchoey** [comment]
@lilyydu I remember this is resolved after one of Alex's PR. Will close this one. Thank you!
