### ISSUE TITLE
[Bug]: @microsoft/teams-ai yarn build failure 

### ISSUE THREAD

**Issue by VKZycus** [microsoft/teams-ai#1305]
### Language

Javascript/Typescript

### Version

latest

### Description

Following documentation 
https://github.com/microsoft/teams-ai/tree/main/js/samples/01.messaging.a.echoBot

yarn build fails

| ../../node_modules/typescript/lib/lib.dom.d.ts(2289,11): error TS2300: Duplicate identifier 'AbortController'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(2304,13): error TS2300: Duplicate identifier 'AbortController'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(2318,11): error TS2300: Duplicate identifier 'AbortSignal'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(2337,13): error TS2300: Duplicate identifier 'AbortSignal'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(8610,11): error TS2300: Duplicate identifier 'FormData'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(8630,13): error TS2300: Duplicate identifier 'FormData'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(22532,11): error TS2300: Duplicate identifier 'URL'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(22562,13): error TS2300: Duplicate identifier 'URL'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(22577,11): error TS2300: Duplicate identifier 'URLSearchParams'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(22623,13): error TS2300: Duplicate identifier 'URLSearchParams'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(28021,6): error TS2300: Duplicate identifier 'RequestInfo'.
 | ../../node_modules/typescript/lib/lib.dom.d.ts(28208,6): error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.
 | ../../../../../node_modules/@types/react-native/globals.d.ts(49,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Blob' must be of type '{ new (blobParts?: BlobPart[] | undefined, options?: BlobPropertyBag | undefined): Blob; prototype: Blob; }', but here has type '{ new (blobParts?: (string | Blob)[] | undefined, options?: BlobOptions | undefined): Blob; prototype: Blob; }'.
 | ../../../../../node_modules/@types/react-native/globals.d.ts(54,15): error TS2300: Duplicate identifier 'FormData'.
 | ../../../../../node_modules/@types/react-native/globals.d.ts(76,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'Headers' must be of type '{ new (init?: HeadersInit | undefined): Headers; prototype: Headers; }', but here has type '{ new (init?: HeadersInit_ | undefined): Headers; prototype: Headers; }'.
 | ../../../../../node_modules/@types/react-native/globals.d.ts(110,5): error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'BodyInit | null | undefined', but here has type 'BodyInit_ | undefined'.
 | ../../../../../node_modules/@types/react-native/globals.d.ts(112,5): error TS2717: Subsequent property declarations must have the same type.  Property 'headers' must be of type 'HeadersInit | undefined', but here has type 'HeadersInit_ | undefined'.
![image](https://github.com/microsoft/teams-ai/assets/104554101/efee05a0-2afd-4333-9fdb-75b73febc446)
![image](https://github.com/microsoft/teams-ai/assets/104554101/c8bd340e-aa62-4647-b71a-f0090922f987)

### Reproduction Steps

```bash
1.git clone https://github.com/Microsoft/teams-ai.git

2.cd teams-ai/js
3.yarn install
4.yarn build
```

**Comment by lilyydu** [comment]
Hi @VKZycus,

I tried reproducing your steps but mine ran successfully. When you ran `yarn install`, did that go through successfully?

**Comment by lilyydu** [comment]
To confirm, you ran `yarn install` and `yarn build` in the /js directory? Do you mind double checking you're following [these steps](https://github.com/microsoft/teams-ai/blob/66500cc7775b3c17d54ad9019443efb68c547411/getting-started/QUICKSTART.md#build-and-run-the-sample-app-1)?

**Comment by lilyydu** [comment]
@VKZycus Closing this ticket due to 2-week inactivity, please feel free to re-open if you are still facing this issue!
