### ISSUE TITLE
[PY] Auth Sign-in Method

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#1318]
https://github.com/microsoft/teams-ai/pull/911

Added getTokenOrSignInUser method in Application class. It is meant to be the single catch-all method to sign a user in and get the token. If the user is signed in it simply returns the token. If not, it triggers the sign in flow. Starting the sign in flow will only work if the incoming activity supports it (ex. message, messageExtension/fetch...etc). This method will work in action handlers as well.

**Comment by BMS-geodev** [comment]
test comment

**Comment by BMS-geodev** [comment]
@lilyydu when you are back,

I reviewed the initial comment above and have a few questions.

1. "getTokenOrSignInUser":
I see getTokenOrStartSignIn here
https://github.com/microsoft/teams-ai/blob/135235e5583910a824a0bade99f3bf6b23c83c8d/js/packages/teams-ai/src/Application.ts#L1091, is this how it ended up?

would the goal be to model after this and add a similar implementation to the python /teams/ai/app.py? There we have _authenticate_user() but that isn't really the same thing. 

I'll stop there for now

**Comment by singhk97** [comment]
https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/USER-AUTH.md#manual-sign-in
