### ISSUE TITLE
[Feature Request]: Support using client certificate for bot

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#1345]
### Scenario

Some tenant may block the use of client secret. In this case, developers need to add a client certificate to identify the application itself.

### Solution

Update the SDK to accept client certificate as an alternative to MicrosoftAppPassword in the bot application and provide example for this usage.

**Comment by aacebo** [comment]
here is an example of using a certificate with BF which is identical to how you would configure it using our SDK since we use the same auth methods and bot adapters https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/84.bot-authentication-certificate
