### ISSUE TITLE
Not able to configure the environment variables 

### ISSUE THREAD

**Issue by venkateshkumar** [microsoft/teams-ai#1363]
### Language

Javascript/Typescript

### Version

latest

### Description

I have done the setup with the following instructions and when i configure the environment variables not able to hit the API's
Request you to provide the steps for configuring open ai parameters.

### Reproduction Steps

```bash
1. Configure the application
2. Configure the environment variables
3. Yarn start the application
```

**Comment by corinagum** [comment]
@venkateshkumar Could you share what your .env file looks like? It should be similar to `sample.env`. If you are using Open AI, it should look like:  

```
BOT_ID=
BOT_PASSWORD=
OPENAI_KEY=abc123...

#AZURE_OPENAI_KEY=
#AZURE_OPENAI_ENDPOINT=
```

Which sample are you looking at? If it is missing the `sample.env` file we can make a quick update.

**Comment by venkateshkumar** [comment]
I'm referring to this sample

js/samples/01.messaging.a.echoBot/env

**Comment by corinagum** [comment]
@venkateshkumar thank you for the info. It looks like echobot may be missing its `sample.env` file so I will get that added. I will close this dev support item as responded :)
