### ISSUE TITLE
[JS] Update package and samples to support node v18 & v20. End support for v16.

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1371]
node v16 is current in EOL status.

https://nodejs.github.io/nodejs.dev/en/about/releases/#:~:text=Major%20Node.js%20versions%20enter%20Current%20release%20status%20for,LTS%20status%20and%20are%20ready%20for%20general%20use.

- [ ] Also update documentation to note this (Check main readme, js readme, teams-ai readme, and samples)

**Comment by corinagum** [comment]
We're semi-blocked on enforcing this because there are dependencies in the botbuilder packages that are unable to be updated to use node >16 at this time. For now, we've removed note that node 16 is supported but will not be enforcing it.

**Comment by ajith007** [comment]
I've Node v20.11.0, and so not able to try the samples! :(
**error @microsoft/teams-ai@1.2.1: The engine "node" is incompatible with this module. Expected version "18.x". Got "20.11.0"**

**Comment by aacebo** [comment]
Yes we are blocked from updating our node version by our Bot Framework dependency

**Comment by venkatace** [comment]
The packages should support node v20 & above. How to resolve this?

**Comment by corinagum** [comment]
Botbuilder 4.23.x now supports node >18. However, the package @azure/msal-browser still does not support versions greater than 18, preventing us from being able to support it as well.
