### ISSUE TITLE
[Feature Request]: Add an API Wrapper to the AI class in order to reach and obtain the Action Plan by using the API endpoint accessed from outside of Teams platform

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-ai#1388]
### Scenario

Some customers develop more than one platform solution for their AI business objectives. For example, the same customer may have Teams client, Web client and Slack client. They'd like to use the power of Teams AI Library to create an action plan based on the LLM analyze of the user's prompt. These actions can be invoked then in various platforms as per those platform implementation details.

### Solution

Create an API Wrapper to Teams AI class so that it can be called to generate an action plan for the given prompt and configuration.

**Comment by corinagum** [comment]
After discussion with dannygar, we clarified that both the web app and slack app are not using botbuilder. While any botbuilder bot channel can utilize teams-ai (despite the name of the repo), extending beyond usage of botbuilder is out of scope of our project at this time. Danny will discuss with our PMs, and if there is a change in status we can reopen this issue at that time.
