### ISSUE TITLE
[Bug]: Teams chef bot sample throws "Error generating embeddings ... Request failed with status code 400"

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1389]
### Language

Javascript/Typescript

### Version

latest

### Description

Exploring Teams chef bot sample and keep getting this error:
* I use Azure OpenAI endpoint and key, and it works when I am using aibot template
* I also changed the hard coded azureDeployment value in /VectraDataSource.ts
* I use a gpt4 deployment

`
[onTurnError] unhandled error: Error: Error generating embeddings for query: AxiosError: Request failed with status code 400
Error: Error generating embeddings for query: AxiosError: Request failed with status code 400
    at LocalDocumentIndex.<anonymous> (/home/.../teams-ai/js/samples/04.ai.a.teamsChefBot/node_modules/vectra/src/LocalDocumentIndex.ts:269:19)
`

### Reproduction Steps

```bash
1.follow Readme in js/samples/04.ai.a.teamsChefBot
```

**Comment by dylanw-oss** [comment]
I figured it out with a curl request to Azure OpenAI endpoint to do embedding. 

got this error:
"The embeddings operation does not work with the specified model, gpt-4. Please choose different model and try again.

I must deploy an embedding model, but unfortunately, it's not available in the region my OpenAI resource in, I ended up with a new OpenAI and it works now.

Please update document to make it clear that two deployments as prerequisites if using Azure OpenAI, one embedding model and one GPT model deployment.

**Comment by derhallim** [comment]
@dylanw-oss can you please clarify how you used the 2 models in your code? You need to have the config.json and the index.ts to have the name of your model, did you set it to your embedding model? If so, how did you use the GPT model?
