### ISSUE TITLE
[Feature Request]: Add TeamsAttachmentDownloader in Python SDK

### ISSUE THREAD

**Issue by frankqianms** [microsoft/teams-ai#1390]
### Scenario

To support inline image inputs for user, a TeamsAttachmentDownloader which can be configured in Application is needed. 
Just like what is done in JS.

### Solution

The class should be used like this:
```python
downloader = TeamsAttachmentDownloader(
  botAppId=config.APP_ID,
  adapter=TeamsAdapter(config),
)
app = Application[TurnState](
    ApplicationOptions(
        bot_app_id=config.APP_ID,
        storage=storage,
        adapter=TeamsAdapter(config),
        ai=AIOptions(planner=planner),
    ),
    downloader=downloader
)
```

**Comment by lilyydu** [comment]
Hi @frankqianms, thanks for the suggestion and proposed implementation! Closing as we already have this tracked as an upcoming feature through #1331 - estimated release around early May.
