### ISSUE TITLE
[Bug]:  The repair strategy is causing an error, despite receiving a valid response.

### ISSUE THREAD

**Issue by mluebbec** [microsoft/teams-ai#1391]
### Language

C#

### Version

latest

### Description

It seems that there is an error when using the repair strategy. When i ask the bot for simple tasks, i see in the console that the repair strategy provides a valid response. 

However, the bot encounters an error with the following message: 

"Reached max model response repair attempts. Last feedback given to model: "No valid JSON objects were found in the response. Return a valid JSON object with your thoughts and the next action to perform."

Im using the monologue augmentation type.
Planner option are as follows:

LogRepairs = true,
MaxRepairAttempts = 3

Console Output:
![image](https://github.com/microsoft/teams-ai/assets/52731873/41aa44a1-d1ea-4fbb-93f4-f6da6d10eb23)
![image](https://github.com/microsoft/teams-ai/assets/52731873/ca842b26-fb8c-4c0a-a8c1-978248283ee3)
![image](https://github.com/microsoft/teams-ai/assets/52731873/6dc13180-95a2-4ad6-a933-e6d7171c46d3)

### Reproduction Steps

```bash
1. Starting new conversation (empty history)
2. Empty action.json
3. skprompt.txt contains "You are an KI that answers human questions."
2. Ask the bot for a simple regular expression - e.g. "i need a regex to validate email addresses"
```

**Comment by singhk97** [comment]
This happens when the model is unable to repair the JSON. You should use the `tools` augmentation over the `sequence` and `monologue` augmentation as it is more reliable.
