### ISSUE TITLE
Support for Azure OpenAI Assistants

### ISSUE THREAD

**Issue by NikhilBery** [microsoft/teams-ai#1398]
### Scenario

Currently, the library does not offer support for integrating Azure OpenAI based assistants within Planners, only OpenAI Assistants are supported.

### Solution

Azure recently launched Assistant support, in its models, will 
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant

Request support for Azure OpenAI based assistants within the Teams AI library's Planner module.

**Comment by corinagum** [comment]
Thanks! We've discussed this as a team and will hopefully be adjusting our roadmap for this. :)

**Comment by singhk97** [comment]
Thanks for opening this ticket @NikhilBery. We have this on our roadmap!

**Comment by corinagum** [comment]
Work items: 
https://github.com/microsoft/teams-ai/issues/1497
https://github.com/microsoft/teams-ai/issues/1498
https://github.com/microsoft/teams-ai/issues/1499

@NikhilBery, thanks for filing this request! I'm going to close this since we will track the work item progress with the above links.
