### ISSUE TITLE
[Bug]: can't let app.ai.action to stop repeating my command

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1399]
### Language

Javascript/Typescript

### Version

latest

### Description

I'm trying to use this api to add a command for user to get last N days sales count.

```typescript
app.ai.action('SalesCount', async (context: TurnContext, state: ApplicationTurnState, parameters: SalesCountParameters) => {

  // async code to query database and save to res ...
  
  await context.sendActivity(`[getting last ${parameters.days}] days Sales count:`);
  await context.sendActivity(res);
  return `done`;
}
```

and in Teams chat, the bot replies to me with 3 messages, like this:

```
                    (me) get last 10 days Sales count
(bot) [getting last 10] days Sales count:
         <res list>
         Getting last 10 days Sales count
```

I don't want the bot to send me the last sentence, it's repeating my command.

How to do it?

and I tried to change the function to return null, and the bot won't reply any message after the change. 

### Reproduction Steps

```bash
see description
```

**Comment by corinagum** [comment]
Hi @dylanw-oss, it looks like you may need to parse your `res` object before sending the activity. 

1. Could you share what the full `res` object is?
2. It might also be helpful to share the query database code
3. Are you using augmentation? I'm wondering if there's some kind of looping issue. 
![image](https://github.com/microsoft/teams-ai/assets/14900841/d3f9f3ec-82f7-423c-b317-e46746b61035)
4. Could you share your `config.json`, `actions.json`, and prompt text?

**Comment by dannygar** [comment]
You can have the bot to be "silent" after it completes the action by returning the AI.StopCommandName
 instead of 'done'

**Comment by dylanw-oss** [comment]
`allow_looping` to false does not work, but returning "AI.StopCommandName" fix the issue for me. 
Thank you @corinagum and @dannygar!
