### ISSUE TITLE
[Bug]: build failed due to "Messages' has no exported member 'ThreadMessage"

### ISSUE THREAD

**Issue by KennethBWSong** [microsoft/teams-ai#1405]
### Language

Javascript/Typescript

### Version

latest

### Description

![image](https://github.com/microsoft/teams-ai/assets/63089166/d709e57c-2640-4e27-a5c5-59bff32ce8e9)

### Reproduction Steps

```bash
1.Open 06.assistants.a.mathBot template
2. npm install
3. npm run build
...
```

**Comment by baishalighosh** [comment]
Running into the same issue

**Comment by baishalighosh** [comment]
<img width="1046" alt="image" src="https://github.com/microsoft/teams-ai/assets/91940334/22a89a50-c759-4c49-b6b0-9426886aebab">

**Comment by implodingduck** [comment]
Looks like the newer openai 4.29.1 dependency changed some exports. I had luck building by forcing openai to use version 4.28.4

**Comment by implodingduck** [comment]
It was more brute forcing... 

I added the following to my "dependencies" section in package.json
```
"dependencies": {
        "@microsoft/teams-ai": "~1.1.1",
        "botbuilder": "^4.22.1",
        "botbuilder-dialogs": "^4.22.1",
        "dotenv": "^16.4.5",
        "replace": "~1.2.0",
        "restify": "~11.1.0",
        "shx": "^0.3.4",
        "openai": "4.28.4"
    }
```

then I removed my node_modules and re installed with `npm install -f`

**Comment by baishalighosh** [comment]
Just tried your recommendation and this seems to work for the time being, thank you!

**Comment by dylanw-oss** [comment]
run into the same issue, and I workaround it by deleting packages-lock.json and run `yarn install` and `yarn build`

**Comment by KriyenKP** [comment]
Same issue, mentioned resolution does not work.

**Comment by corinagum** [comment]
Hi folks, just a reminder that we use hoisting via yarn, and our directions instruct to use `yarn install && yarn build` in the root `js` folder. We can certainly work on a fix to get these bugs out of the way, but they can be avoided for now by doing the above.

**Comment by baishalighosh** [comment]
[like]  Baishali Ghosh reacted to your message:
________________________________

**Comment by dylanw-oss** [comment]
> It was more brute forcing...
> 
> I added the following to my "dependencies" section in package.json
> 
> ```
> "dependencies": {
>         "@microsoft/teams-ai": "~1.1.1",
>         "botbuilder": "^4.22.1",
>         "botbuilder-dialogs": "^4.22.1",
>         "dotenv": "^16.4.5",
>         "replace": "~1.2.0",
>         "restify": "~11.1.0",
>         "shx": "^0.3.4",
>         "openai": "4.28.4"
>     }
> ```
> 
> then I removed my node_modules and re installed with `npm install -f`

@implodingduck did you try pin openai version with `yarn install && yarn build`? I tried your approach, `npm install -f && npm run build` works but `yarn build` doesn't work, which got the same error.

**Comment by dylanw-oss** [comment]
Although `npm install -f && npm run build` didn't throw error, it didn't recover packages in node_modules folder, so it won't work for me as "Deploy" step requires packages ready in sample folder, see issue #1428

**Comment by corinagum** [comment]
Hi everyone, thanks for your patience. teams-ai package has been updated to have openai as a peer dependency, and all samples have also had the dependency added, pending merge on a few last samples. This error should now be fixed. 

Please note we've also changed how TTK works, and will now use npm install. However, we recommend copy-pasting the sample folder to a different directory in order to avoid workspace issues. To use latest repo changes instead of published changes, simply comment out the npm install command under `deploy` in `teamstoolkit.local.yml`

**Comment by baishalighosh** [comment]
[like]  Baishali Ghosh reacted to your message:
________________________________
