### ISSUE TITLE
[Bug]: Teams AI Bot has no response in chat after deploying to non-Testing environment and uploading to Teams.

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1414]
### Language

Javascript/Typescript

### Version

latest

### Description

Trying to deploy bot to Azure and upload it to Teams, it has no response to my questions in chat.

**Reproduction steps:**

1. Followed LightBot sample and tested it working in local with my Microsoft 365 Testing Tenant;
js/samples/04.ai.c.actionMapping.lightBot
2. Trying to deploy to MSIT tenant and Teams by following below steps.
3. In VS code Teams toolkit, log out Microsoft 365 testing tenant, and login M365 and Azure with my MSIT account;
4. Delete `"openAIKey": { "value": "${{SECRET_OPENAI_KEY}}"}` from infra/azure.parameters.json, and added "AZURE_OPENAI_KEY=<>" and "AZURE_OPENAI_ENDPOINT=<>" to env/.env.staging
5. Click "Provision" and select a resource group from a MSIT subscription;
6. Click "Deploy", 
7. Click "Publish", it completed but I can't find the application in Teams, 
8. Try another way, click utility "Zip Teams App Package", and then in Teams -> Apps -> Manage your Apps -> Upload an App, select the package, now I can add the bot to my Teams.
9. Chat with the bot in Teams, but it has no response to me. 
10. I also [Validate the app package](https://dev.teams.microsoft.com/appvalidation.html), no errors.
11. I don't know how to figure out the problem, is there any logs I can check? 
12. I also checked Azure bot, there is a "Test in Web chat" function, I tried it, and then in channels blade, I found there're some errors in Web chat. 
...

![image](https://github.com/microsoft/teams-ai/assets/53635739/adff878b-d285-4367-ad39-f11b2cff4078)

and the error message is something like this:
"There was an error sending this message to your bot: HTTP status code Unauthorized"

Probably I missed something when trying to deploy the Teams application to MSIT Azure and Teams. Is there a document I can follow to do a real deployment after testing with "Microsoft 365 Testing tenant"?

**[Update 3/18 - A]**
I checked [developer portal](https://dev.teams.microsoft.com/apps) and uploaded the app package to developer portal, and clicked "Preview in Teams", and selected to use "web app", and login with my Microsoft account, it gave me this error:
![image](https://github.com/microsoft/teams-ai/assets/53635739/24996b28-d539-40de-98ad-de22c062101f)
"MSIT" is the Microsoft 365 Testing Tenant, for some reason it messed up with Microsoft tenant with "Microsoft 365 Testing Tenant", the app was uploaded to Microsoft developer portal and it thought it belongs to a Testing tenant.

**[Update 3/18 - B]**
I cleaned up everything and restarted the whole process, Provision/Deploy/build package/upload to Teams, the last error gone - "Selected user account does not exist in tenant 'MSFT' and cannot access the application '5e3ce6c0-2b1f-4285-8d4b-75ee78787346' in that tenant", unfortunately it still does not work, the bot has not response. And this time, in Azure, Teams bot has different issue in Teams channel with message "Error occurred while communicating with bot", and I also queried logs in Azure portal, got empty records for "Activities Sent from Clients to Direct Line", "Bot To Channels", "Channel to Bot", "Clients To Direct Line Channel", "Failed Requests", etc.
![image](https://github.com/microsoft/teams-ai/assets/53635739/099022e2-7247-4169-99b2-6b24effa2ae9)

### Reproduction Steps

```bash
see description.
```

**Comment by corinagum** [comment]
Please note that these issues you are filing are not related to Teams Ai itself, so the help we'll be able to provide is limited. What you're experiencing is partially related to the tenant rules that have been modified recently on the Microsoft tenant, and therefore affects all apps. Teams Toolkit team is your best bet for getting help in this area. 

The first error (Pick an account) means that your browser is either logged into the incorrect tenant (i.e., you are logged into your FTE account while trying to access your alt tenant or vice versa). I recently had problems where, even on an incognito browser, my credentials were mixed with my alt tenant even after signing out of FTE and into alt. Possibly a caching issue.

For #4 on your steps to repro, please see the other issue you filed which I converted to a discussion. 

HTTP status code unauthorized: Means your bot id and/or password credentials are incorrect.

**Comment by dylanw-oss** [comment]
@corinagum , appreciated your inputs!
Could you please tell me how I can reach out to "Teams Toolkit team"? Github repo or an internal DG?
And in my last deployment, unauthorized issue gone, now only one left is the issue "Error occurred while communicating with bot" in Teams channel in Azure portal. I have no idea where to start investigating.

**Comment by dylanw-oss** [comment]
I'll try this one: https://github.com/microsoft/botframework-sdk

**Comment by corinagum** [comment]
@dylanw-oss Correct repo is https://github.com/OfficeDev/TeamsFx

**Comment by dylanw-oss** [comment]
@corinagum 
I found that the deployed bot app service has some problem. 
1) the provision does not work for openAIKey, even it is defined in infra/azure.parameters.json, the bicep file doesn't have reference to it. I'll open another bug for it.
2) I deployed the sample by removing openAIKey from infra/azure.parameters.json and then in Azure portal, bot App service environment variable, manually add "AZURE_OPENAI_KEY" and "AZURE_OPENAI_ENDPOINT"
![image](https://github.com/microsoft/teams-ai/assets/53635739/381be013-f122-4d4d-9536-993915f23531)

And in Kudu, I found there is an error log in `site/LogFiles/Application/logging-errors.txt`

```Application has thrown an uncaught exception and is terminated:
  Error: Cannot find module 'dotenv'
  Require stack:
  - C:\home\site\wwwroot\lib\index.js
  - C:\Program Files (x86)\iisnode\interceptor.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (C:\home\site\wwwroot\lib\index.js:29:18)
      at Module._compile (node:internal/modules/cjs/loader:1105:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)```
And there is no dotenv under C:\home\site\wwwroot\node_modules>
![image](https://github.com/microsoft/teams-ai/assets/53635739/4c0e6270-06d7-4bf2-a91d-ac57f9fa4984)

**Comment by dylanw-oss** [comment]
@corinagum, there is no such issue on my local, no matter I run `yarn install` under js folder or the specific sample folder. When we use provision/deploy we need to start from sample folder in VS Code, and the problem happens in Azure, the package.json does have the reference of dotenv, it seems that `yarn install` wasn't run during publishing? Can you confirm if js sample works in Azure, I suspect it's some common issue.

**Comment by dylanw-oss** [comment]
@corinagum, I know what you mean. The dotenv package was installed under /teams-ai/js/node_modules/dotenv folder, but when we run provision and deploy in VS Code, we have to open specific sample folder, right? I think the install/build/package during the Deploy step will only use the packages under the sample folder, for example, /teams-ai/js/samples/04.ai.c.actionMapping.lightBot/node_modules/
That's the reason why we got "Error: Cannot find module 'dotenv'" in Azure bot service.

**Comment by corinagum** [comment]
> @corinagum, I know what you mean. The dotenv package was installed under /teams-ai/js/node_modules/dotenv folder, but when we run provision and deploy in VS Code, we have to open specific sample folder, right? I think the install/build/package during the Deploy step will only use the packages under the sample folder, for example, /teams-ai/js/samples/04.ai.c.actionMapping.lightBot/node_modules/ That's the reason why we got "Error: Cannot find module 'dotenv'" in Azure bot service.

Sorry for the confusion. What I meant was, I do see "dotenv" under the sample's package.json, so theoretically it should be added on the deploy step. 

If you haven't already, could you try the following?
1. delete node modules in the sample folder
2. do yarn && yarn build inside the sample folder
3. Test the sample / deploy
4. Publish to Azure bot service


Could you tell me what steps you run into errors? You're also welcome to message me internally; my alias is the same as my github username.

**Comment by dylanw-oss** [comment]
@corinagum, I tried these 4 steps with sample 01.messaging.a.echoBot and it works. But it does not work with sample 04.ai.c.actionMapping.lightBot. 
My observation: step 1 and 2 can recover all packages in sample folder for both samples, but when run deploy from VS code, sample 04.ai.c.actionMapping.lightBot node_modules folder was refreshed and only a few packages lefts, and this didn't happen for sample 01, which is very weird.
I workaround this by removing the first two cli/runNpmCommand from /teams-ai/js/samples/04.ai.c.actionMapping.lightBot/teamsapp.yml, and VS Code Teams Toolkit / Deploy can deploy all required packages to Azure Bot service.

**Comment by dylanw-oss** [comment]
@corinagum, I can successfully run sample 01.messaging.a.echoBot with its bot and service deployed in Azure! :nerd_face: 
But the same issue (bot has no response) still occurs for sample using Azure OpenAI, e.g. 04.ai.c.actionMapping.lightBot, I suspected that there is some issue happened when it communicating with Azure OpeanAI endpoint, but if it's the case it should at least respond something like "The bot encountered an error or bug."?

**Comment by corinagum** [comment]
Issue was found, and new bug filed: https://github.com/microsoft/teams-ai/issues/1439 
closing this as resolved :)
