### ISSUE TITLE
[Bug]: Teams Chef Bot Sample is not able to provision in Teams Toolkit

### ISSUE THREAD

**Issue by tecton** [microsoft/teams-ai#1418]
### Language

Javascript/Typescript

### Version

latest

### Description

The content of `teamsapp.yml` has error so that user cannot run lifecycle command in Teams Toolkit like "Provision".
![image](https://github.com/microsoft/teams-ai/assets/886116/1ead07c0-5db7-48aa-9cbe-365eb4eb6637).
It shows an error like:

> [Error] - code:ConfigManager.InvalidYamlSchemaError, message: Unable to parse yaml file: xxx\teams-ai\js\samples\04.ai.a.teamsChefBot\teamsapp.yml. Please open the yaml file for detailed errors.
>  Help link: https://aka.ms/teamsfx-actions/invalid-lifecycle-error

### Reproduction Steps

```bash
1. clone sample project.
2. Open "04.ai.a.teamsChefBot" in VS Code. (v1.87.2)
3. VS Code has installed Teams Toolkit. (5.6.0)
4. Click "Provision" in Teams Toolkit view.
5. Error message pops up.
```

**Comment by therealjohn** [comment]
These lines need deleted. 

https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.a.teamsChefBot/teamsapp.yml#L46-L48
