### ISSUE TITLE
[Bug]: Can't provision sample to Azure, there is no bicep steps for openAIKey

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1427]
### Language

Javascript/Typescript

### Version

latest

### Description

This instruction does not work:
https://github.com/microsoft/teams-ai/tree/main/js/samples#deploy-the-bot-to-azure

The reason is that there is a definition of "openAIKey", but no reference in bicep file.
https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.c.actionMapping.lightBot/infra/azure.parameters.json#L20-L22

There will be an error message when you trying to provision it:
`
(×) Error: arm/deploy failed.
    (×) Error: The ARM templates for deployment name: 'Create-resources-for-tab' could not be deployed in resource group 'bot_rg' for reason: Deployment template validation failed: 'The template parameters 'openAIKey' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'resourceBaseName, botAadAppClientId, botAadAppClientSecret, webAppSKU, botDisplayName, serverfarmsName, webAppName, location'. Please see https://aka.ms/arm-pass-parameter-values for usage details.'.
`

### Reproduction Steps

```bash
see description
```

**Comment by corinagum** [comment]
@KennethBWSong and @MuyangAmigo, could we get your assistance looking into this? Your help is appreciated!

**Comment by KennethBWSong** [comment]
@corinagum In my understanding, you need to update these two parts:
1. In "infra/azure.bicep", add following line before definition of resources:
```
@secure()
param openAIKey string
```
and add following line in appSettings of resource "webApp":
![image](https://github.com/microsoft/teams-ai/assets/63089166/4dbaa8f9-fe1b-468f-942e-d1f1320ff136)
2. Create ".env.staging.user" file, and add follow line:
```
SECRET_OPENAI_KEY="your-key"
```
When running provision, ttk will read .env files and replace the placeholders in "azure.parameters.json" with values in the env variables. Then azure.bicep will consume the values in "azure.parameters.json" and provision the azure resources.

**Comment by corinagum** [comment]
Lightbot and other samples have been updated to add more details about adding keys. Closing this bug as resolved.
