### ISSUE TITLE
[Bug]: JS sample does not work in Azure, missing dotenv package

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1428]
### Language

Javascript/Typescript

### Version

latest

### Description

Provision JS sample to Azure, and the bot service has issue that missing dotenv package. 
The problem is that dotenv is installed in JS node_modules folder when you execute `yarn install` there, the specific sample node_modules folder does not have it, but when you do provision/deploy from VS Code you're working from a specific folder. 
And if you try to execute `yarn install` inside a specific sample folder, VS code deploy will fail with this error: 

`
[deploy.Error]: An unexpected error has occurred while performing the Deploy task. {"stack":"Error: ENOENT: no such file or directory, stat '/home/teams-ai/js/samples/04.ai.c.actionMapping.lightBot/node_modules/.bin/semver'","message":"ENOENT: no such file or directory, stat '/home/teams-ai/js/samples/04.ai.c.actionMapping.lightBot/node_modules/.bin/semver'","errno":-2,"code":"ENOENT","syscall":"stat","path":"/home/teams-ai/js/samples/04.ai.c.actionMapping.lightBot/node_modules/.bin/semver"}
`

### Reproduction Steps

```bash
1. under JS folder, execute `yarn install`
2. open any specific sample folder in VS Code
3. Use Teams toolkit to execute Provision/Deploy/Publish
4. Open Azure bot service in Azure portal
5. In Kudo, you can find an error in service log:
```

```
Error: Cannot find module 'dotenv'
Require stack:
- C:\home\site\wwwroot\lib\index.js
- C:\Program Files (x86)\iisnode\interceptor.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\home\site\wwwroot\lib\index.js:29:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
...
```

**Comment by dylanw-oss** [comment]
Thanks @corinagum for the help, this workaround works:
1. delete node modules in the sample folder
2. do yarn && yarn build inside the sample folder
3. Test the sample / deploy
4. Publish to Azure bot service

But for some samples, execute "deploy" in VS code Teams Toolkit will refresh node_moduels folder, in this case, we can delete the first two cli/runNpmCommand from teamsapp.yml and then run deploy.

**Comment by corinagum** [comment]
Keeping this work item open to discuss with TTK team on how to better set up our samples for ease of use and compatibility.

**Comment by corinagum** [comment]
@dylanw-oss it turns out there is an issue where provisioning to Azure doesn't work for a sample that is still nested inside the `teams-ai` directory. If planning on doing more than testing locally, users should copy-paste the sample folder outside of `teams-ai` and proceed with development that way. Our sample directions will be updated in the coming weeks to reflect as such. Thanks for your patience on this!
