### ISSUE TITLE
[Bug]: wrong environment variable name in samples bicep file: MicrosoftAppId and MicrosoftAppPassword

### ISSUE THREAD

**Issue by dylanw-oss** [microsoft/teams-ai#1439]
### Language

Javascript/Typescript

### Version

latest

### Description

Sample's bicep file defines environment name as MicrosoftAppId and MicrosoftAppPassword
https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.c.actionMapping.lightBot/infra/azure.bicep#L55-62

but code is referencing BOT_ID and BOT_PASSWORD
https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.c.actionMapping.lightBot/src/index.ts#L33-34

they should match each other.

### Reproduction Steps

```bash
see description
```

**Comment by corinagum** [comment]
Hi @dylanw-oss, could you try copy-pasting the sample outside of the teams-ai repository and see if you have the same results? It looks like when the sample is nested inside the repo, there's an interference with yarn that causes package issues.
