### ISSUE TITLE
[Bug]:  onUserSignInSuccess is not invoked in TEAMSSSO.BOT sample, when using BLOBSTORAGE

### ISSUE THREAD

**Issue by svandenhoven** [microsoft/teams-ai#1457]
### Language

Javascript/Typescript

### Version

latest

### Description

There is an issue with the sample 06.AUTH.TEAMSSSO.BOT when replacing MemoryStorage by BlobStorage. 

I discoverd this by replacing the line

```javascript
const storage = new MemoryStorage();
```

with 

```javascript
import { BlobsStorage } from 'botbuilder-azure-blobs';

const storage = new BlobsStorage(
`DefaultEndpointsProtocol=https;AccountName=${process.env.STORAGE_ACCOUNT_NAME};AccountKey=${process.env.STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net`,
    'process.env.STORAGE_ACCOUNT_CONTAINER_NAME!
);
```

When running the app, the app will compile, build and run. On the first message the authentication will start. However the handler 
app.authentication.get('your authentication setting key').onUserSignInSuccess is not invoked.

```javascript
app.authentication.get('your authentication setting key').onUserSignInSuccess(async (context: TurnContext, state: ApplicationTurnState) => {
    // Successfully logged in
    await context.sendActivity('Successfully logged in');
    await context.sendActivity(`Token string length: ${state.temp.authTokens['graph']!.length}`);
    await context.sendActivity(`This is what you said before the AuthFlow started: ${context.activity.text}`);
});
```

The state and converstation are been stored in the blobstorage, but no error is given or reason why onUserSignInSuccess is not invoked

This means that the user cannot be informed on the signin and will most likely retype the message and discover it has been signed in. We would like to use the teams-ai SDK for solution and inform the user that the sign in has been successful.
 

### Reproduction Steps

```bash
1. use the Sample 06.AUTH.TEAMSSSO.BOT 
2. Add environment variables in .env:
   - STORAGE_ACCOUNT_NAME=
   - STORAGE_ACCOUNT_KEY=
   - STORAGE_ACCOUNT_CONTAINER_NAME=
2. go to index.ts
3. Add import { BlobsStorage } from 'botbuilder-azure-blobs';
4. Replace the line 
const storage = new MemoryStorage(); 
by
const storage = new BlobsStorage(
`DefaultEndpointsProtocol=https;AccountName=${process.env.STORAGE_ACCOUNT_NAME};AccountKey=${process.env.STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net`,
    'process.env.STORAGE_ACCOUNT_CONTAINER_NAME'
);
5. run the app 
6. add a message and notice the onUserSignInSuccess handler is not invoked
...
```

**Comment by corinagum** [comment]
@singhk97 could you take a look? Thank you~

**Comment by yonggang-xiao** [comment]
I found the problem too.

**Comment by preetiyadav12** [comment]
> ### Language
> Javascript/Typescript
> 
> ### Version
> latest
> 
> ### Description
> There is an issue with the sample 06.AUTH.TEAMSSSO.BOT when replacing MemoryStorage by BlobStorage.
> 
> I discoverd this by replacing the line
> 
> ```js
> const storage = new MemoryStorage();
> ```
> 
> with
> 
> ```js
> import { BlobsStorage } from 'botbuilder-azure-blobs';
> 
> const storage = new BlobsStorage(
> `DefaultEndpointsProtocol=https;AccountName=${process.env.STORAGE_ACCOUNT_NAME};AccountKey=${process.env.STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net`,
>     'process.env.STORAGE_ACCOUNT_CONTAINER_NAME!
> );
> ```
> 
> When running the app, the app will compile, build and run. On the first message the authentication will start. However the handler app.authentication.get('your authentication setting key').onUserSignInSuccess is not invoked.
> 
> ```js
> app.authentication.get('your authentication setting key').onUserSignInSuccess(async (context: TurnContext, state: ApplicationTurnState) => {
>     // Successfully logged in
>     await context.sendActivity('Successfully logged in');
>     await context.sendActivity(`Token string length: ${state.temp.authTokens['graph']!.length}`);
>     await context.sendActivity(`This is what you said before the AuthFlow started: ${context.activity.text}`);
> });
> ```
> 
> The state and converstation are been stored in the blobstorage, but no error is given or reason why onUserSignInSuccess is not invoked
> 
> This means that the user cannot be informed on the signin and will most likely retype the message and discover it has been signed in. We would like to use the teams-ai SDK for solution and inform the user that the sign in has been successful.
> 
> ### Reproduction Steps
> ```shell
> 1. use the Sample 06.AUTH.TEAMSSSO.BOT 
> 2. Add environment variables in .env:
>    - STORAGE_ACCOUNT_NAME=
>    - STORAGE_ACCOUNT_KEY=
>    - STORAGE_ACCOUNT_CONTAINER_NAME=
> 2. go to index.ts
> 3. Add import { BlobsStorage } from 'botbuilder-azure-blobs';
> 4. Replace the line 
> const storage = new MemoryStorage(); 
> by
> const storage = new BlobsStorage(
> `DefaultEndpointsProtocol=https;AccountName=${process.env.STORAGE_ACCOUNT_NAME};AccountKey=${process.env.STORAGE_ACCOUNT_KEY};EndpointSuffix=core.windows.net`,
>     'process.env.STORAGE_ACCOUNT_CONTAINER_NAME'
> );
> 5. run the app 
> 6. add a message and notice the onUserSignInSuccess handler is not invoked
> ...
> ```

The above mentioned for BlobStorage happens when writing to blob-storage. Detailed description of what was found is as below. 
-  in `BotAuthenticationBase` class `handleSignInActivity` method is called. In this method on line 148 `if (result.status === DialogTurnStatus.complete)` result.status comes out to be `waiting` from `TeamsSsoBotAuthentication` class and hence it doesn't go inside the `if` where `userSignInSuccessHandler?.(context, state);` is called on line 161.

- In `TeamsSsoBotAuthentication` class while trying to create ssoDilog context in this method `createSsoDialogContext`. it calls `shoulddedup` to check for deduplications but fails with error of `eTag conflict` and ends up setting the status to be waiting on line number 135 `return Dialog.EndOfTurn;` 

error messages 
```
RestError: The condition specified using HTTP conditional header(s) is not met.
RequestId:89d81975-701e-0010-5b5a-8f2bac000000
Time:2024-04-15T17:26:48.5988191Z
    at handleErrorResponse (/Users/preetiyadav/teams-ai/teams-ai/js/node_modules/@azure/core-http/src/policies/deserializationPolicy.ts:274:17)
    at /Users/preetiyadav/teams-ai/teams-ai/js/node_modules/@azure/core-http/src/policies/deserializationPolicy.ts:179:47
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async StorageRetryPolicy.attemptSendRequest (/Users/preetiyadav/teams-ai/teams-ai/js/node_modules/@azure/storage-blob/src/policies/StorageRetryPolicy.ts:169:18)
    at async StorageClientContext.sendOperationRequest (/Users/preetiyadav/teams-ai/teams-ai/js/node_modules/@azure/core-http/src/serviceClient.ts:521:23)
    at async BlockBlobClient.upload (/Users/preetiyadav/teams-ai/teams-ai/js/node_modules/@azure/storage-blob/src/Clients.ts:3858:14)
    at async /Users/preetiyadav/teams-ai/teams-ai/js/node_modules/botbuilder-azure-blobs/node_modules/p-map/index.js:57:22
```

```
status: 412
The condition specified using HTTP conditional header(s) is not met.\nRequestId:89d81975-701e-0010-5b5a-8f2bac000000\nTime:2024-04-15T17:26:48.5988191Z.
```

**Comment by singhk97** [comment]
Thanks for the repro steps @preetiyadav12 I will be looking into it soon.

**Comment by singhk97** [comment]
The `RestError: The condition specified using HTTP conditional header(s) is not met.` error implies that the state values aren't being written to the blob storage. 

This could be an issue when configuring the blob storage. Can you verify that the conversation state persists even in non-auth scenarios? The echo bot sample keeps a counter so you can use that to verify.

**Comment by svandenhoven** [comment]
Thanks for the reply. The error indeed implies error with writing to blob. This can be causes when the eTag used to write to blob is not the same as the current value in the blob. This is check by the azure blob API as a concurrency check.

I have tested the echobot with the same blobstorage as we use in our project

``` typescript
import { BlobsStorage } from "botbuilder-azure-blobs";

...
// Define storage and application
// const storage = new MemoryStorage();
const storage = new BlobsStorage(
  `DefaultEndpointsProtocol=https;AccountName=${storageAccountName};AccountKey=${storageAccountKey};EndpointSuffix=core.windows.net`,
  storageContainerName
);

const app = new Application<ApplicationTurnState>({
    storage
});
```

This seems to work fine and the state is written to a blob in the azure storage container.

Might it be that by using SSO multiple call are done to the bot causing a concurrency error?

Many thanks in advance for your reply and assistance.

**Comment by svandenhoven** [comment]
Hi, I might have found a cause for the issue. I found that in TeamsSSOBotAuthentication.ts in the method Dedup a value for eTag is set. See <https://github.com/microsoft/teams-ai/blob/092edad3e72fc0bb1d3bb01f7d2bf0c25e37f102/js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.ts#L149>

```typescript
    private async shouldDedup(context: TurnContext): Promise<boolean> {
        const storeItem = {
            eTag: context.activity.value.id
        };

        const key = this.getStorageKey(context);
        const storeItems = { [key]: storeItem };

        try {
            await this._storage.write(storeItems);
        } catch (err) {
            if (err instanceof Error && err.message.indexOf('eTag conflict')) {
                return true;
            }
            throw err;
        }
        return false;
    }
```

The eTag gets the value of context.activity.value.id and is set along to the _storage.write().

We use { BlobsStorage } from 'botbuilder-azure-blobs' instead of Memory storage. The write method can be found at <https://github.com/microsoft/botbuilder-js/blob/37c7b6ae7b2ae3d927563de8a8fbe9b407291530/libraries/botbuilder-azure-blobs/src/blobsStorage.ts#L155> where the code is:

```typescript
    async write(changes: StoreItems): Promise<void> {
        z.record(z.unknown()).parse(changes);

        await this._initialize();

        await pmap(
            Object.entries(changes),
            ([key, { eTag = '', ...change }]) => {
                const blob = this._containerClient.getBlockBlobClient(sanitizeBlobKey(key));
                const serialized = JSON.stringify(change);

                return blob.upload(serialized, serialized.length, {
                    conditions: typeof eTag === 'string' && eTag !== '*' ? { ifMatch: eTag } : {},
                    blobHTTPHeaders: { blobContentType: 'application/json' },
                });
            },
            {
                concurrency: this._concurrency,
            }
        );
    }
```

You can see that in blob.upload a condition is give on eTag. If the eTag is string and not *, that an ifMatch on eTag is added to the call to blob. This will match the eTag. It will result in the "RestError: The condition specified using HTTP conditional header(s) is not met." error when the eTag send and present in the Blob do no match.

As the eTag that is sent in  shouldDedup is "context.activity.value.id", this will always fail IMO as the eTag on a blob is a timestap.


I have tested this by changing the code of the shouldDedup method into below code (added some console.log for debug). I have run the code with rebuilding teams-ai locally and use the d.teamsBot-SSO sample:

```typescript
    private async shouldDedup(context: TurnContext): Promise<boolean> {
        const storeItem = {
            eTag: '*',
        };

        const key = this.getStorageKey(context);
        const storeItems = { [key]: storeItem };

        try {
            console.log('Writing token exchange state to storage.');
            await this._storage.write(storeItems);
        } catch (err) {
            if (err instanceof Error && err.message.indexOf('eTag conflict')) {
                console.log('Ignoring duplicate token exchange event.');
                return true;
            }
            throw err;
        }
        return false;
    }
```

By setting the storeItem.eTag to "*" instead of context.activity.value.id, the this_storage.write() does not fail because of the mismatched eTag and the SSO authentication.

I cannot oversee the implications of this change, but it proves that using TeamsAI SDK and botbuilder-azure-blobs, do not work well together imo.

Can you advice what best way forward is?

**Comment by svandenhoven** [comment]
Hi, I might have found a cause for the issue. I found that in TeamsSSOBotAuthentication.ts in the method Dedup a value for eTag is set. See <https://github.com/microsoft/teams-ai/blob/092edad3e72fc0bb1d3bb01f7d2bf0c25e37f102/js/packages/teams-ai/src/authentication/TeamsSsoBotAuthentication.ts#L149>

```typescript
    private async shouldDedup(context: TurnContext): Promise<boolean> {
        const storeItem = {
            eTag: context.activity.value.id
        };

        const key = this.getStorageKey(context);
        const storeItems = { [key]: storeItem };

        try {
            await this._storage.write(storeItems);
        } catch (err) {
            if (err instanceof Error && err.message.indexOf('eTag conflict')) {
                return true;
            }
            throw err;
        }
        return false;
    }
```

The eTag gets the value of context.activity.value.id and is set along to the _storage.write().

We use { BlobsStorage } from 'botbuilder-azure-blobs' instead of Memory storage. The write method can be found at <https://github.com/microsoft/botbuilder-js/blob/37c7b6ae7b2ae3d927563de8a8fbe9b407291530/libraries/botbuilder-azure-blobs/src/blobsStorage.ts#L155> where the code is:

```typescript
    async write(changes: StoreItems): Promise<void> {
        z.record(z.unknown()).parse(changes);

        await this._initialize();

        await pmap(
            Object.entries(changes),
            ([key, { eTag = '', ...change }]) => {
                const blob = this._containerClient.getBlockBlobClient(sanitizeBlobKey(key));
                const serialized = JSON.stringify(change);

                return blob.upload(serialized, serialized.length, {
                    conditions: typeof eTag === 'string' && eTag !== '*' ? { ifMatch: eTag } : {},
                    blobHTTPHeaders: { blobContentType: 'application/json' },
                });
            },
            {
                concurrency: this._concurrency,
            }
        );
    }
```

You can see that in blob.upload a condition is give on eTag. If the eTag is string and not *, that an ifMatch on eTag is added to the call to blob. This will match the eTag. It will result in the "RestError: The condition specified using HTTP conditional header(s) is not met." error when the eTag send and present in the Blob do no match.

As the eTag that is sent in  shouldDedup is "context.activity.value.id", this will always fail IMO as the eTag on a blob is a timestap.


I have tested this by changing the code of the shouldDedup method into below code (added some console.log for debug). I have run the code with rebuilding teams-ai locally and use the d.teamsBot-SSO sample:

```typescript
    private async shouldDedup(context: TurnContext): Promise<boolean> {
        const storeItem = {
            eTag: '*',
        };

        const key = this.getStorageKey(context);
        const storeItems = { [key]: storeItem };

        try {
            console.log('Writing token exchange state to storage.');
            await this._storage.write(storeItems);
        } catch (err) {
            if (err instanceof Error && err.message.indexOf('eTag conflict')) {
                console.log('Ignoring duplicate token exchange event.');
                return true;
            }
            throw err;
        }
        return false;
    }
```

By setting the storeItem.eTag to "*" instead of context.activity.value.id, the this_storage.write() does not fail because of the mismatched eTag and the SSO authentication.

I cannot oversee the implications of this change, but it proves that using TeamsAI  and botbuilder-azure-blobs

**Comment by singhk97** [comment]
Hey @svandenhoven, thanks for deep diving into this issue and finding a possible solution. To give a bit more context, when the SSO flow starts, if you have multiple teams clients open (web, desktop...etc) then each client will send a token exchange request to the bot. The `shouldDedup` method ensures that the first one that is processed is the last one as any subsequent requests will be met with an etag conflict. 

Setting `eTag: *` will ignore any etag conflicts and change the desired behavor of the `shouldDedup` method. 

Here are a few possible solutions:

1. Is the etag conflict due to an a pre-existing entry? If so then update the catch block to detect BlobStorage etag conflict and return true. If the etag conflict always arise, even before the first write, then maybe a different format of etag? I have a feeling the blob client returns an etag that you would have to use, but since this is in the BlobStorage implementation we might not be able to use it in the AI library.
Create aMemoryStorage for the TeamsSSOBotAuthentication class that will handle the dedup logic.

These are ideas that i have off the top of my head but if you find a better solution please let me know.

**Comment by svandenhoven** [comment]
Hi @singhk97 

Many thanks for the answer and the clarification of the use of the eTag. This makes it not possible to use * for eTag

I did some extra research. In the Team-ai Library the etag is only set in the shouldDedup method. In the MemoryStorage.write method  there is an check indeed on eTag. If eTag is exists but is different an eTag Conflict Error is returns.
(see https://github.com/microsoft/botbuilder-js/blob/37c7b6ae7b2ae3d927563de8a8fbe9b407291530/libraries/botbuilder-core/src/memoryStorage.ts#L69)

```typescript
    write(changes: StoreItems): Promise<void> {
        const saveItem = (key: string, item: any) => {
            const clone: any = { ...item };
            clone.eTag = (this.etag++).toString();
            this.memory[key] = JSON.stringify(clone);
        };

        return new Promise<void>((resolve: any, reject: any): void => {
            if (!changes) {
                throw new ReferenceError('Changes are required when writing.');
            }
            Object.keys(changes).forEach((key: any) => {
                const newItem: any = changes[key];
                const old: string = this.memory[key];
                if (!old || newItem.eTag === '*' || !newItem.eTag) {
                    saveItem(key, newItem);
                } else {
                    const oldItem: any = <any>JSON.parse(old);
                    if (newItem.eTag === oldItem.eTag) {
                        saveItem(key, newItem);
                    } else {
                        reject(new Error(`Storage: error writing "${key}" due to eTag conflict.`));
                    }
                }
            });
            resolve();
        });
    }

```

However when using Azure Blogstore eTag is already a preserved tag for the blob and when set in the change: StoreItems and ifMatch condition is added. I think that this means that the inital write will already fail which is not catched in the shoudlDedup method. This causes the authentication to fail.

**Comment by svandenhoven** [comment]
Hi @singhk97 

Many thanks for the answer and the clarification of the use of the eTag. This makes it not possible to use * for eTag

I did some extra research. In the Team-ai Library the etag is only set in the shouldDedup method. In the MemoryStorage.write method  there is an check indeed on eTag. If eTag is exists but is different an eTag Conflict Error is returns.
(see https://github.com/microsoft/botbuilder-js/blob/37c7b6ae7b2ae3d927563de8a8fbe9b407291530/libraries/botbuilder-core/src/memoryStorage.ts#L69)

```typescript
    write(changes: StoreItems): Promise<void> {
        const saveItem = (key: string, item: any) => {
            const clone: any = { ...item };
            clone.eTag = (this.etag++).toString();
            this.memory[key] = JSON.stringify(clone);
        };

        return new Promise<void>((resolve: any, reject: any): void => {
            if (!changes) {
                throw new ReferenceError('Changes are required when writing.');
            }
            Object.keys(changes).forEach((key: any) => {
                const newItem: any = changes[key];
                const old: string = this.memory[key];
                if (!old || newItem.eTag === '*' || !newItem.eTag) {
                    saveItem(key, newItem);
                } else {
                    const oldItem: any = <any>JSON.parse(old);
                    if (newItem.eTag === oldItem.eTag) {
                        saveItem(key, newItem);
                    } else {
                        reject(new Error(`Storage: error writing "${key}" due to eTag conflict.`));
                    }
                }
            });
            resolve();
        });
    }

```

However when using Azure Blogstore eTag is already a preserved tag for the blob and when set in the change: StoreItems and ifMatch condition is added. I think that this means that the inital write will already fail and therefor the whole

**Comment by svandenhoven** [comment]
I have done more research and it seems not to be possible to use blobstorage. The only way would be to make a new version of BlobStorage class, without the rule to check on eTag. This would result in a possible failure when user logins in on multiple devices, as this is the reason why in teams-ai an field eTag is added to the payload.

As we do need to have a persistent storage for enterprise use to store state persistently and resilient for application, server restarts and multi-server installations, I have create a CosmosDB version for Storage. This can be found in my repo. For more info see: https://github.com/svandenhoven/d.teamsSSO-bot?tab=readme-ov-file#using-sso-with-persistent-storage.

This seems to work fine except 2 issues:

1. The activity that is used before user is authenticated is stored. This means that all information is in storage, including the latest message. If the app restart and user signin again, this message is used as latest message as it is not overwritten. See example below
![image](https://github.com/user-attachments/assets/c269b66e-4732-486c-9da1-c69adc56f9f5)

2. There are two items stored, one with the conversation.state and one with the eTag. The latter is used for the authentication. After an signout or restart the key of the item for authentication is new, resulting in multiple items in CosmosDB. With memory storage this was no issue as the memory was deleted after a restart, but with persistent storage this is not the case. This will result in un-used data storage.

**Comment by singhk97** [comment]
#1896 #1897 

I have created two bugs that we'll be looking into soon.
