### ISSUE TITLE
[Bug]: The Bot's LLM takes only the first document content embeddings from the Vectra data sources when multiple documents are uploaded

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-ai#1501]
### Language

Javascript/Typescript

### Version

latest

### Description

If I upload multiple documents and then ask question related to the last document was uploaded, the Bot LLM returns the response as if only the first document was used as RAG embedding in the response.

Here are the steps to recreate this issue:
1. Upload the first document and ask any questions related to that document.
2. Bot will correctly respond with the answer related to the first document content.
3. Upload the second document containing the different content from the first document and ask any question related to the second document.
4. Bot will think my question was related to the first document, and therefore the LLM response most likely will be inaccurate.

Additionally, here are some screenshots to illustrate this issue:

![image](https://github.com/microsoft/teams-copilot-starter/assets/1878251/5871772e-6fac-4f18-aa55-deb7f500b96c)

Note: the first document is uploaded containing the product invoice from CONTOSO.

![image](https://github.com/microsoft/teams-copilot-starter/assets/1878251/9c7a603f-2782-4ba5-b6fc-b00a5eb59916)

This was the result came from analyzing the first document. It shows accurate invoice from CONTOSO.

Now, let's upload the second document, and ask Bot to find the founders (the document contain the Tesla company profile information):

![image](https://github.com/microsoft/teams-copilot-starter/assets/1878251/de790823-d36c-4ae0-8414-b515392a857c)

The result came as following:
![image](https://github.com/microsoft/teams-copilot-starter/assets/1878251/2edcbf72-2fdc-42ca-95d4-c124ab516a5f)

Here you can see that LLM didn't correctly recognize that the document containing company profile was already uploaded and added to Vectra Local Index.

To help with the debugging logs, here's the debugging output of the `functions` argument when the `async completePrompt(context, memory, functions)` function is called in `planners/LLMClient.js` from `planners/ActionPlanner's completePrompt() method`:

![image](https://github.com/microsoft/teams-copilot-starter/assets/1878251/da03b012-b070-40e9-a8cc-cb3eae970d6d)

Here you can see that `_data` property contains the array of 4 elements, which are embeddings generated by Vectra Local Index containing the 2 copies of the first document and 2 copies of the second document.

### Reproduction Steps

```bash
1. Upload the first document and ask any questions related to that document.
2. Bot will correctly respond with the answer related to the first document content.
3. Upload the second document containing the different content from the first document and ask any question related to the second document.
4. Bot will think my question was related to the first document, and therefore the LLM response most likely will be inaccurate.
...
```

**Comment by corinagum** [comment]
@Stevenic could you comment?

**Comment by Stevenic** [comment]
@dannygar sorry for the delay. Are these PDF's? I can't see the screenshots but one thing that can happen with PDF's is you could be trying to import an "image only" PDF. Have you verified that you're actually extracting text from these other documents?

**Comment by corinagum** [comment]
Closing due to lack of response.
