### ISSUE TITLE
[Missing Sample for NodeJS]: 04.ai.c.actionMapping.lightBot is missing from JS folder 

### ISSUE THREAD

**Issue by ChetanSharma-msft** [microsoft/teams-ai#1548]
### Language

Javascript/Typescript

### Version

latest

### Description

[Missing Sample for NodeJS]: 04.ai.c.actionMapping.lightBot is missing from JS folder 

Sample is linked to the documentation but does not exists.
https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.c.actionMapping.lightBot

Is this intentionally, if yes, please remove the sample link from the below documentation;
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/teams-conversation-ai-overview#code-samples

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by corinagum** [comment]
Pull request filed: https://github.com/MicrosoftDocs/msteams-docs/pull/10748
