### ISSUE TITLE
[Bug]: the 04.ai.a.teamsChefBot sample is not working after git clone

### ISSUE THREAD

**Issue by nemesv** [microsoft/teams-ai#155]
By following the quick start guide here: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start this sample cannot be started after cloning the repository.

I have encountered two problems:
- the **taks.json and launch.json files are missing** from the .vscode folder, so the application cannot be started using F5 in VScode 
    -   -> copying the .vscode folder from a different sample solves this issue
- after starting the application with F5 it does not find the manifest.json file because the teamsapp.local.yml references the **teamsAppManifest** folder but the file is in the **appManifest** folder 
    -   -> renaming the folder solves this issue

**Comment by corinagum** [comment]
Hi @nemesv, thanks for filing the issue. Teams Chef Bot is actually slightly behind the curve - it hasn't been set up (yet) to work with Teams Toolkit. Now that BUILD is almost over, we're hoping to get that done ASAP. However, please feel free to make the changes you listed above in a PR! The help is very much appreciated.

FYI @therealjohn @aycabas
