### ISSUE TITLE
[Bug]: env file missing in teamsChefBot sample

### ISSUE THREAD

**Issue by tecton** [microsoft/teams-ai#1564]
### Language

Javascript/Typescript

### Version

latest

### Description

The instructions in the README of `js/samples/04.ai-apps/a.teamsChefBot` tell users to modify `./env/.env.local.user` file, but there's no such file under that sample.
The order of steps under "Setting up the sample" is confusing: it has two "step 1" followed by "step 4".

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by ayachensiyuan** [comment]
Is anyone still following up on this issue？

**Comment by corinagum** [comment]
@ayachensiyuan this is a P2 bug so while it's been assigned to me, I haven't had the chance to get to it yet. Thanks for your patience.
