### ISSUE TITLE
Missing configuration information for 2 parameters in 04.q.questBot sample

### ISSUE THREAD

**Issue by Mohammed-MSFT** [microsoft/teams-ai#157]
Hi!
We are Unable to build teams AI sample **No. 10** from the list, because below two parameters are required which is not mentioned in readme and also not added in **.env** file.

**Sample Link :** [04.q.questBot](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.q.questBot).

1.StorageConnectionString
2.StorageContainer 

We were using this two parameters in **bot.ts** file.

<img width="650" alt="Screenshot 2023-05-26 151047" src="https://github.com/microsoft/teams-ai/assets/109147706/8790f9a2-ed93-456f-b565-b043ee339999">

Please provide information on this, what values we have to use in this 2 parameters.

**Thanks!!**

**Comment by rolandbodenstaff** [comment]
Hi,

I'm not a maintainer of this project but I think you need to provide a connection string and container name of a Azure Storage account resource that you need to create.
