### ISSUE TITLE
[Feature Request]: Use local llm

### ISSUE THREAD

**Issue by rcalv002** [microsoft/teams-ai#1589]
### Scenario

The official documentation at https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/teams-conversation-ai-overview mentions that we can use local llms. I found this to be possible with the typescript sdk as i could pass in an endpoint, but was unable to find the equivalent for the dotnet SDK.

### Solution

Provide an overload on the dotnet sdk to pass in endpoint and model name so we can use local openapi compliant apis?

**Comment by corinagum** [comment]
@Stevenic

**Comment by aacebo** [comment]
to use a local LLM you would need to implement the `PromptCompletionModel` interface which allows you to define your own model

**Comment by rcalv002** [comment]
Any chance you could provide a sample? I'm spent plenty of time trying to accomplish this and although embedding generation seems to work, implementing the `PromptCompletionModel` (`public class OllamaAIModel : IPromptCompletionModel`) and using it did direct api calls to my ollama instance, but to endpoints that dont exist. Here's what it tries to reach for chat completions

"/v1/openai/deployments/llama3/chat/completions?api-version=2024-04-01-preview"

where it should just be "/v1/chat/completions"

It's been an endless rabbit hole of dependencies without much real progress. The teams ai overview page mentions support for this several times but I haven't seen any guidance offered.

**Comment by overcookedpanda** [comment]
> Any chance you could provide a sample? I've spent plenty of time trying to accomplish this and although embedding generation seems to work, implementing the `PromptCompletionModel` (`public class OllamaAIModel : IPromptCompletionModel`) and using it did direct api calls to my ollama instance, but to endpoints that dont exist. Here's what it tries to reach for chat completions
> 
> "/v1/openai/deployments/llama3/chat/completions?api-version=2024-04-01-preview"
> 
> where it should just be "/v1/chat/completions"
> 
> It's been an endless rabbit hole of dependencies without much real progress. The teams ai overview page mentions support for this several times but I haven't seen any guidance offered.

Did you ever figure this issue out?

**Comment by overcookedpanda** [comment]
> to use a local LLM you would need to implement the `PromptCompletionModel` interface which allows you to define your own model

Can you point us to an example for this?

**Comment by rcalv002** [comment]
N

> > Any chance you could provide a sample? I've spent plenty of time trying to accomplish this and although embedding generation seems to work, implementing the `PromptCompletionModel` (`public class OllamaAIModel : IPromptCompletionModel`) and using it did direct api calls to my ollama instance, but to endpoints that dont exist. Here's what it tries to reach for chat completions
> > "/v1/openai/deployments/llama3/chat/completions?api-version=2024-04-01-preview"
> > where it should just be "/v1/chat/completions"
> > It's been an endless rabbit hole of dependencies without much real progress. The teams ai overview page mentions support for this several times but I haven't seen any guidance offered.
> 
> Did you ever figure this issue out?

No, I didn't really. Instead I cloned the Microsoft.Teams.AI repo, and made changes to add the endpoint and then just pointed it in my client library to my ollama instance. I don't recommend it

**Comment by overcookedpanda** [comment]
> > > Any chance you could provide a sample? I've spent plenty of time trying to accomplish this and although embedding generation seems to work, implementing the `PromptCompletionModel` (`public class OllamaAIModel : IPromptCompletionModel`) and using it did direct api calls to my ollama instance, but to endpoints that dont exist. Here's what it tries to reach for chat completions
> > > "/v1/openai/deployments/llama3/chat/completions?api-version=2024-04-01-preview"
> > > where it should just be "/v1/chat/completions"
> > > It's been an endless rabbit hole of dependencies without much real progress. The teams ai overview page mentions support for this several times but I haven't seen any guidance offered.
> > 
> > 
> > Did you ever figure this issue out?
> 
> No, I didn't really. Instead I cloned the Microsoft.Teams.AI repo, and made changes to add the endpoint and then just pointed it in my client library to my ollama instance. I don't recommend it

Thank you for the response! This was the only method I could see working, and would prefer not to do it as well.
