### ISSUE TITLE
Quest Bot: switch back from in-memory storage

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#159]
In #158 @therealjohn fixed Quest bot to use in-memory storage since we don't have documentation on obtaining storage string/key yet.

Once we have more information available, we should switch back and/or let the user choose which option they want to use. 

- [ ] Update the sample
- [ ] Update the `README.md`
- [ ] Documentation

**Comment by Stevenic** [comment]
Yeah I've done a couple of core fixes for QuestBot as one-off PR's but I also switched QuestBot back to using the MemoryStorage provider.
