### ISSUE TITLE
[Dev support]: Why does the app.messageExtensions.query handler use `Query<TParams>` instead of a `MessageExtensionQuery` type? 

### ISSUE THREAD

**Issue by therealjohn** [microsoft/teams-ai#1628]
## Code snippets
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/MessageExtensions.ts#L317

This makes it harder to re-use existing code or autocomplete for understanding what comes from the query. For example, the `MessageExtensionQuery` type in the Bot Framework SDK has clear properties for parameters that make it simpler to learn the API. 

![image](https://github.com/microsoft/teams-ai/assets/1501196/c804856a-c77a-410e-bbcd-2756a6a0b22a)

Compared to this in the AI SDK makes it difficult to use: 

```
app.messageExtensions.query("searchCmd", async (context, state, query) => {
  const searchQuery = query.parameters.queryText;
  // Other handling
  // e.g. Create search / action cards
  ```

**Comment by corinagum** [comment]
@therealjohn We flatten the object from `MessageExtensionQuery` later in the code: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/MessageExtensions.ts#L333 but I'm not recalling why. 

@Stevenic do you have insight on this? I realize it was a decision made a while ago at this point, but it would be good to know if there's reasons to avoid switching to `MessageExtensionQuery`

**Comment by Stevenic** [comment]
@therealjohn we were trying to unify all of the various query structures across the SDK. There are 2 or 3 different patterns that basically do the same thing so the goal was to get that down to one unified pattern. You're still free to ignore our unified `query` parameter and just use the activity directly.

Can you elaborate on the intelisense issues as that shouldn't really be impacted.

**Comment by corinagum** [comment]
Closing as answered. Please feel free to add info on discussions held in chat for other developers' info.
