### ISSUE TITLE
Cannot use Azure OpenAI service

### ISSUE THREAD

**Issue by adiazcan** [microsoft/teams-ai#163]
I tried to use Azure OpenAI with the new @microsoft/teams-ai, version 0.1.0-preview.2, and I had the following error on the completion request: 

_[onTurnError] unhandled error: AxiosError: Request failed with status code 401_

To reproduce the problem, I change the OpenAIPlanner for the following AzureOpenAIPlanner: 

```
const planner = new AzureOpenAIPlanner({
  apiKey: config.openAIKey,
  defaultModel: 'gpt-35-turbo',
  logRequests: true,
  endpoint: config.openAIEndpoint,
  apiVersion: '2023-03-15-preview'
});
```
Debugging the problem, the code requested the OpenAI endpoint not the Azure endpoint. 

![image](https://github.com/microsoft/teams-ai/assets/6652046/342bd7b1-ad39-4721-a069-50b24b2fb2b3)

Maybe I missed a param to configure the planner to use Azure or the Azure Planner is not correctly configured to use the Azure OpenAI client.

**Comment by Stevenic** [comment]
@adiazcan the value your passing for `config.openAIEndpoint` is the endpoint from your Azure deployment?  I can try to reproduce this today...

**Comment by adiazcan** [comment]
Hello @Stevenic 

I pass the Azure endpoint from my service like https://****.openai.azure.com/

**Comment by corinagum** [comment]
Hey @adiazcan, could you confirm:
1. The correct model for your Azure OpenAI subscription? Your code says `'gpt-35-turbo'` but the model we have internally is a different one -- this is the first thing that stands out to me.
2. No references to '@microsoft/botbuilder-m365' in any code, including package-lock and yarn.lock?

**Comment by corinagum** [comment]
oh, nice catch. Your PR would be much appreciated! I'll close this issue as resolved. :)

**Comment by tsubakimoto** [comment]
Hi @adiazcan 

Based on your comment, I also tried to make TeamsChefBot compatible with Azure OpenAI Service, but it does not work.

js/samples/04.ai.a.teamsChefBot/src/index.ts

```ts
// https://xxx.openai.azure.com is dummy

const planner = new AzureOpenAIPlanner({
    apiKey: process.env.OPENAI_API_KEY,
    defaultModel: 'text-davinci-003',
    logRequests: true,
    endpoint: 'https://xxx.openai.azure.com',
    apiVersion: '2023-05-15'
});
const moderator = new OpenAIModerator({
    apiKey: process.env.OPENAI_API_KEY,
    moderate: 'both',
    endpoint: 'https://xxx.openai.azure.com'
});
```

What other responses have you made?
Thanks for your support.

**Comment by corinagum** [comment]
@tsubakimoto currently moderation is not fully implemented and is in development. For me, not including moderation worked. Could you give that a try?

**Comment by tsubakimoto** [comment]
@corinagum Thank you for your support.
By commenting out `moderator` I was able to use AOAI.
