### ISSUE TITLE
[Dev support]: Chef Bot

### ISSUE THREAD

**Issue by PatelN123** [microsoft/teams-ai#1636]
Hi - I have managed to get Chef Bot up and running however I'm encountering issues customising the index. I've used Vectra and created a custom script to create the embeddings and index however Teams-AI is not accepting this when I upload it and send a message. Is there a script that I can use to create an index based on my TXT files?

**Comment by corinagum** [comment]
Hi @PatelN123, have you already followed the Vectra instructions for creating your index? https://github.com/Stevenic/vectra/blob/main/samples/wikipedia/README.md#create-an-empty-index 
Is it after this that you are still running into trouble?

**Comment by PatelN123** [comment]
Ah yes that's worked, thanks. I did not see the samples folder!
