### ISSUE TITLE
[Bug]: Citations not showing for "h.datasource-azureOpenAI" sample

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/teams-ai#1649]
### Language

Javascript/Typescript

### Version

latest

### Description

Describe the bug
Im not getting citations on the "h.datasource-azureOpenAI" sample from teams ai library, like in this video: "https://www.youtube.com/watch?v=VLP32Ci02M0"
I did not modify anything, just pasted in my azure resources.

Expected behavior
To get the same answer but with a citation tab under it.

Do I need to enable a specific feature flag in Teams or use a specific version of Teams? When will this be available in the public version of Teams?

Related bug: https://github.com/OfficeDev/TeamsFx/issues/11568

**Comment by corinagum** [comment]
Yes, you need to be in R0 of Teams with all 5 feature flags enabled. You also need your bot to be whitelisted.

**Comment by yasinbozkurt-tr** [comment]
What is R0?
