### ISSUE TITLE
[SECURITY] AOAI OAuth Sample Authentication

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1665]
update samples that use AOAI to use `OAuth` to attain an api key.

**Comment by wangyuantao** [comment]
I believe not just sample code update, but also Teams AI lib core need update to support `DefaultAzureCredential`. You are the expert how to implement it. The requirement is: using the same code, for developer to debug locally, the app uses developer's user identity, for deployed app service, the app users app services's system assigned managed identity.
infra/bicep of the sample code also need to update so the managed identity will be enabled and role assignments will be added during the azure resource provision/deploy
