### ISSUE TITLE
[SECURITY] Data Source Samples Use Environment Keys

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1666]
update data source samples that require user to update `config.json` with secrets to instead inject environment variables into default prompt using factory.

**Comment by wangyuantao** [comment]
FYI - different data source type has different secret name, for example, azure search using api key, but cosmos db is using connection string.

**Comment by wangyuantao** [comment]
Maybe there is no need to do that. Azure security requires no secret can be added into the download .zip file. we have already scrubbed the .zip. so moving secret from config.json to .env doesn't help. the developer must manually add the secrets here and there on their own after download.
