### ISSUE TITLE
[Bug]: Manifest Validation failed! Unable to get schema

### ISSUE THREAD

**Issue by sindiachoolackal** [microsoft/teams-ai#1681]
### Language

C#

### Version

latest

### Description

I am trying the dotnet samples. Whenever I try to "Prepare Teams App Dependencies" from Teams Toolkit (Rightclick the project), it fails with this error.
Summary:
(×) Error: Lifecycle stage provision failed.
  (√) Done: teamsApp/create was executed successfully.
    (√) Done: Teams app with id 0013fa54-1xxxxxxxxxxxa742ceb94 already exists, skipped creating a new Teams app.
  (√) Done: botAadApp/create was executed successfully.
    (√) Done: Used existing Microsoft Entra application with client id c2a9b5a1xxxxxxxxxxxxxxx06630978074.
  (√) Done: file/createOrUpdateJsonFile was executed successfully.
    (√) Done: The json file has been generated successfully to ./appsettings.Development.json.
  (√) Done: botFramework/create was executed successfully.
    (√) Done: The bot registration has been updated successfully (https://dev.botframework.com/bots?id=c2a9b5a1-a82d-40xxxxxxxx978074).
  (×) Error: teamsApp/validateManifest failed.

**Manifest Validation failed!** Unable to get schema from https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json, message: Failed to get manifest at url https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json due to: request to https://developer.microsoft.com/json-schemas/teams/v1.16/MicrosoftTeams.schema.json failed, **reason: self signed certificate in certificate chain**

This is happening for Echobot and all other samples.

### Reproduction Steps

```bash
1.Open one of the dotnet sample projects (Echobot)
2.Set the dev tunnel
3.Right click on the project. Teams toolkit --> Prepare Teams App Dependencies
Then it fails with the above mentioned error.
```

**Comment by corinagum** [comment]
This is not a Teams AI library issue. Please contact the [TTK team](https://github.com/OfficeDev/teams-toolkit) for support.
