### ISSUE TITLE
I have an issue with h.datasource-azureOpenAI JS sample

### ISSUE THREAD

**Issue by ahmedmahmoudR** [microsoft/teams-ai#1682]
### Language

Javascript/Typescript

### Version

latest

### Description

I followed all the steps to configure the Azure OpenAI and Search services, replacing the necessary keys and endpoints. However, I am encountering issues during normal Chrome debugging, where it repeatedly asks for the Azure Search key and Azure OpenAI key. Additionally, when I use the Teams Toolkit testtool, I receive an unhandled error message: [onTurnError] unhandled error: AxiosError: Request failed with status code 400 +0ms.

**Chrome debugging** 

![image](https://github.com/microsoft/teams-ai/assets/19419509/a57531a0-6cdd-4905-9f83-2738436c2dde)

**Teams testtool debugging**

![image](https://github.com/microsoft/teams-ai/assets/19419509/82588435-9b27-49d4-9172-0cf31300e57f)

![image](https://github.com/microsoft/teams-ai/assets/19419509/db1b8cf8-77b4-45fe-a66f-4ce26d83789b)

![image](https://github.com/microsoft/teams-ai/assets/19419509/4a69eed5-9094-4f5a-a32f-9987c9178739)

Please note I test az open key and endpoint with other sample code and its works fine 

### Reproduction Steps

```bash
1.Clone repo
2.replace the azure key and azure endpoint 
3.create .env file 
4.add azure search key and endpoint to propmt config.json
5. run npm i
6. test the app
...
```

**Comment by corinagum** [comment]
Please verify that your `index_name` in the code matches the index name of your files on oai.azure.com. When customers have encountered a 400 error on this sample, that has usually been the cause of the bug.
