### ISSUE TITLE
I have an issue with Chat With Your Data (Using Microsoft 365 Data) template

### ISSUE THREAD

**Issue by ahmedmahmoudR** [microsoft/teams-ai#1683]
### Language

Javascript/Typescript

### Version

latest

### Description

I followed all the steps to configure Chat With Your Data (Using Microsoft 365 Data) template, however I faced issue after send message to bot 

 [onTurnError] unhandled error: PolyFillNot

Err 

![image](https://github.com/microsoft/teams-ai/assets/19419509/82efe7e3-0f3d-409f-8631-efbbab803340)

![image](https://github.com/microsoft/teams-ai/assets/19419509/b127e965-a4f4-4843-8e24-324c8a30641c)

### Reproduction Steps

```bash
1.Clone the repo 
2. npm i 
3.add azure key and azure endpoint and deployment name
4. Add documents to SharePoint
5- Debug the Bot
...
```

**Comment by corinagum** [comment]
Hi @ahmedmahmoudR, which sample are you using when you run into this problem?

**Comment by ahmedmahmoudR** [comment]
This issue when i choose to create sample from teams toolkit vs  (Microsoft 365 Data)

![image](https://github.com/microsoft/teams-ai/assets/19419509/68cdf42f-806c-47c9-b507-cfafa5c01373)

**Comment by corinagum** [comment]
Please bring this issue to the [Teams Toolkit team](https://github.com/OfficeDev/Teams-Toolkit-Samples) as they are the writers of that sample :)
