### ISSUE TITLE
[Bug]: Exception thrown for HTTP embeddings call with AOAI

### ISSUE THREAD

**Issue by KrishnP1202** [microsoft/teams-ai#1688]
### Language

Python

### Version

latest

### Description

We are using an internal loadbalancer, which is http for embedding call, and we have been using with azureopenai library for this already. But here we are getting an exception that the endpoint must be a valid HTTPS url. Can you allow http endpoints too.

### Reproduction Steps

```bash
1.Using http azure endpoint for embedding calls
```

**Comment by lilyydu** [comment]
Hi @KrishnP1202, could you provide more details on your logic and where the exception is being thrown?

**Comment by KrishnP1202** [comment]
Hey @lilyydu, I was trying to use the AzureOpenAIEmbeddings using azure_endpoint which is http. I got this error in the init function of the AzureOpenAIEmbeddings class inside the library.
`if not endpoint.lower().startswith("https://"):
            raise ValueError(f"""
                Client created with an invalid endpoint of \"{endpoint}\".
                The endpoint must be a valid HTTPS url.
                """)`

**Comment by lilyydu** [comment]
Got it @KrishnP1202  . Just discussed and confirmed with the team, I'll make a PR to remove this check shortly

**Comment by KrishnP1202** [comment]
That's great @lilyydu, thank you
