### ISSUE TITLE
[Feature Request]: Make Python SDK support user-defined LLM models

### ISSUE THREAD

**Issue by frankqianms** [microsoft/teams-ai#1691]
### Scenario

Including OpenAI and Azure OpenAI, there are quite a lot of LLM models user can use for their AI scenarios. Sometimes they might fine tune a minor model and want to apply it to their Teams bot app. In such scenario, shall we support user-defined LLM models rather than only OAI and AzOAI?

### Solution

Make Python SDK support user-defined LLM models

**Comment by aacebo** [comment]
since we export the `PromptCompletionModel` interface devs can implement their own models in a compatible way the same way we do. An example of this is our `LLaMaModel`.
