### ISSUE TITLE
[Dev support]: Javascript Prompt Template Issue

### ISSUE THREAD

**Issue by nicolekaate** [microsoft/teams-ai#1695]
Please be sure to check the Discussions Q&A section before filing a new question.

## Question
How can I get my prompt to show up in teams ai bot?

## Code snippets
My index.js
![image](https://github.com/microsoft/teams-ai/assets/77560154/81e27d84-66e4-4275-917a-66a2d2e97a17)
My skprompt.txt
![image](https://github.com/microsoft/teams-ai/assets/77560154/922cc9f5-5002-4d49-9f0c-9732a5344efc)
Console
![image](https://github.com/microsoft/teams-ai/assets/77560154/0a357aaa-74a5-46a6-ab92-6ad8176884cc)

## What you have tried already
It only shows up in console. 

I tried using:
app.beforeTurn((context, state) => {
  state.temp.post = "Lorem Ipsum...";
});
from the teams-ai PROMPTS.md concepts on GitHub, but it still only shows in console.

> Note: please use this template to file your questions regarding implementation. Once your question is answered, our team will move this question to Q&A in Discussions for findability.

**Comment by corinagum** [comment]
For the bot to send a message, you will need to send the activity for it to be added to the conversation.

https://github.com/microsoft/teams-ai/blob/main/js/samples/03.ai-concepts/a.twentyQuestions/src/index.ts#L150
