### ISSUE TITLE
[JS] Errors while debugging the h.datasource-azureOpenAI sample

### ISSUE THREAD

**Issue by v-kushals** [microsoft/teams-ai#1703]
### Language

Javascript/Typescript

### Version

latest

### Description

- After following the instructions in the readme file of the https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/h.datasource-azureOpenAI, we got the following error on the first debug:

![image](https://github.com/microsoft/teams-ai/assets/145653999/e0e602de-b948-407c-a1e4-f7aee938af9b)

- We tested again on a different device and were able to debug the bot but the prompts weren't working. Upon further investigation, we found that the source file "nba.pdf" was corrupted.

- We used "nba.pdf" from a different sample and upon debugging, ran into the following issue:
![image](https://github.com/microsoft/teams-ai/assets/145653999/2ae4aea5-eab3-4cc9-a474-02c9c24f4039)
 
Here's the terminal output:
`CHAT PROMPT:
OpenAIModel.js:93
[
  {
    "role": "user",
    "content": "The following is a conversation with an AI assistant, who is an expert on answering questions over the given context.\nResponses should be in a short journalistic style with no more than 80 words. "
  },
  {
    "role": "user",
    "content": "nba"
  }
]
OpenAIModel.js:94
  azureopenai:app:error [onTurnError] unhandled error: AxiosError: Request failed with status code 400 +13s
common.js:113
  azureopenai:app:error AxiosError: Request failed with status code 400
  azureopenai:app:error     at settle (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\core\settle.js:19:12)
  azureopenai:app:error     at IncomingMessage.handleStreamEnd (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\adapters\http.js:589:11)
  azureopenai:app:error     at IncomingMessage.emit (node:events:526:35)
  azureopenai:app:error     at IncomingMessage.emit (node:domain:489:12)
  azureopenai:app:error     at endReadableNT (node:internal/streams/readable:1359:12)
  azureopenai:app:error     at processTicksAndRejections (node:internal/process/task_queues:82:21)
  azureopenai:app:error     at Axios.request (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\core\Axios.js:45:41)
  azureopenai:app:error     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  azureopenai:app:error     at async OpenAIModel.post (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\models\OpenAIModel.ts:408:26)
  azureopenai:app:error     at async OpenAIModel.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\models\OpenAIModel.ts:299:26)
  azureopenai:app:error     at async LLMClient.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\LLMClient.ts:293:31)
  azureopenai:app:error     at async ActionPlanner.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:250:16)
  azureopenai:app:error     at async ActionPlanner.continueTask (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:178:24)
  azureopenai:app:error     at async ActionPlanner.beginTask (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:153:16)
  azureopenai:app:error     at async AI.run (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\AI.ts:366:24)
  azureopenai:app:error     at async D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\Application.ts:823:21 +2ms`

- We tried again with OpenAI keys instead of Azure OpenAI. Here's the error we got:
![335553692-d55a7132-ed13-4aa9-bb3c-17ca59356122](https://github.com/microsoft/teams-ai/assets/145653999/73ab4641-2ece-4ba2-a5d3-9590192b20ef)

Terminal output:
`follow-redirects options {
  maxRedirects: 21,
  maxBodyLength: Infinity,
  protocol: 'https:',
  path: '/v1/chat/completions',
  method: 'POST',
  headers: [Object: null prototype] {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    'User-Agent': '@microsoft/teams-ai-v1',
    Authorization: 'Bearer sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'Content-Length': '627',
    'Accept-Encoding': 'gzip, compress, deflate, br'
  },
  agents: { http: undefined, https: undefined },
  auth: undefined,
  family: undefined,
  beforeRedirect: [Function: dispatchBeforeRedirect],
  beforeRedirects: { proxy: [Function: beforeRedirect] },
  hostname: 'api.openai.com',
  port: '',
  agent: undefined,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      validateHeaderName: [Function: __node_internal_],
      validateHeaderValue: [Function: __node_internal_],
      get: [Function: get],
      request: [Function: request],
      setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
} +0ms
  azureopenai:app:error [onTurnError] unhandled error: AxiosError: Request failed with status code 404 +0ms
  azureopenai:app:error AxiosError: Request failed with status code 404
  azureopenai:app:error     at settle (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\core\settle.js:19:12)
  azureopenai:app:error     at BrotliDecompress.handleStreamEnd (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\adapters\http.js:589:11)
  azureopenai:app:error     at BrotliDecompress.emit (node:events:526:35)
  azureopenai:app:error     at BrotliDecompress.emit (node:domain:489:12)
  azureopenai:app:error     at endReadableNT (node:internal/streams/readable:1359:12)
  azureopenai:app:error     at processTicksAndRejections (node:internal/process/task_queues:82:21)
  azureopenai:app:error     at Axios.request (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\axios\lib\core\Axios.js:45:41)
  azureopenai:app:error     at processTicksAndRejections (node:internal/process/task_queues:95:5)
  azureopenai:app:error     at async OpenAIModel.post (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\models\OpenAIModel.ts:408:26)
  azureopenai:app:error     at async OpenAIModel.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\models\OpenAIModel.ts:299:26)
  azureopenai:app:error     at async LLMClient.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\LLMClient.ts:293:31)
  azureopenai:app:error     at async ActionPlanner.completePrompt (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:250:16)
  azureopenai:app:error     at async ActionPlanner.continueTask (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:178:24)
  azureopenai:app:error     at async ActionPlanner.beginTask (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\planners\ActionPlanner.ts:153:16)
  azureopenai:app:error     at async AI.run (D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\AI.ts:366:24)
  azureopenai:app:error     at async D:\Projects\Sample_New_Apps\temp\AI\teams-ai-main\teams-ai-main\js\samples\04.ai-apps\h.datasource-azureOpenAI\node_modules\@microsoft\teams-ai\src\Application.ts:823:21 +1ms`

- Tried with again with the gpt-3.5-turbo model and received the following error code:
![2](https://github.com/microsoft/teams-ai/assets/145653999/31c7c076-0d6b-4dc3-85c0-b81c9bf90d10)

### Reproduction Steps

```bash
1. Clone the teams-ai repo.
2. Replace the placeholder Azure key, Azure endpoint, secret Azure key, and secret Azure endpoint values.
3. Create .env file.
4. Add the "nba.pdf" file in Data Sources in Azure OpenAI Studio.
4. Add Azure search key and Azure endpoint to prompt config.json.
5. Run npm.
6. Debug the app.
```

**Comment by corinagum** [comment]
If you are absolutely sure that your api key for Azure Search is correct, the overwhelmingly common error is that the `index_name` for Azure Search in your `data_source` code does not match the index name in oai.azure.com. Please verify that the index names match.
