### ISSUE TITLE
[Dev support]: untrusted_authority when run in Teams

### ISSUE THREAD

**Issue by Tourenathan-G5organisation** [microsoft/teams-ai#1712]
Please be sure to check the Discussions Q&A section before filing a new question.

## Question
I have created a custom copilot in VS code using JavaScript as programming language using teams toolkit. I have configured the necessary properties for azure open ai. I have connected my MS 365 account and Azure account.
When I run the program in the Test tool it works well but when I use the Debug in Teams (Edge), it install the bot in teams but there is a problem when i try to interact with the bot. The error message is **untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter**

## What you have tried already
I have follows Microsoft docs and done necessary configuration in the App registration, but the error persist. 
When I add the knownAuthorities as a component of webApplicationInfo in the manifest.json file, the manifest validation fails.
Where can I configure the knownAuthorities?

> Note: please use this template to file your questions regarding implementation. Once your question is answered, our team will move this question to Q&A in Discussions for findability.

**Comment by corinagum** [comment]
Hi @Tourenathan-G5organisation, could you file an issue with the [Teams Toolkit team](https://github.com/OfficeDev/Teams-Toolkit-Samples) and link that issue here? Unfortunately this isn't a Teams AI Library issue so I'm not able to provide much help.

**Comment by corinagum** [comment]
Closing this, but we can reopen if necessary.
