### ISSUE TITLE
[Bug]: Demo file in JS sample '04.ai-apps/h.datasource-azureOpenAI' is different from the example picture in ReadMe

### ISSUE THREAD

**Issue by frankqianms** [microsoft/teams-ai#1724]
### Language

Javascript/Typescript

### Version

latest

### Description

Demo file in JS sample ['04.ai-apps/h.datasource-azureOpenAI'](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/h.datasource-azureOpenAI/src/data) is different from the [example picture](https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai-apps/h.datasource-azureOpenAI/assets/example.png) in ReadMe.

And the sample does not work with the given demo file 'nba.pdf'.

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by corinagum** [comment]
This isn't a bug. The image is only included so that the user can know what to expect to see for Powered by AI features. no op.
