### ISSUE TITLE
[Bug]: TeamsSsoPrompt never completes due to timeout

### ISSUE THREAD

**Issue by stepro** [microsoft/teams-ai#1744]
### Language

C#

### Version

latest

### Description

[Here](https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/TeamsSsoPrompt.cs#L32) the timeout value (default 15 minutes) is used to assign an absolute expiration time into the state. [Later](https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/Authentication/Bot/TeamsSsoPrompt.cs#L51), it is used to determine if the prompt has timed out. Unfortunately, the initial assignment uses `DateTime.Now` but the check uses `DateTime.UtcNow`. This means that anybody who is more than 15 minutes behind UTC will observe that the dialog always times out at this stage.

### Reproduction Steps

```bash
1. Try to run the 06.auth.teamsSSO.bot in the US, which is 5 or more hours behind UTC. It always silently ends the dialog before handling the token exchange invoke activity.
```

**Comment by singhk97** [comment]
This issue does not exist in JS. `new Date().getTime()` is used in both setting the `state.experies` property and the check.

Definition:
https://github.com/microsoft/teams-ai/blob/8f0fbbd2cacf6694f8fca6fad63d26789851a648/js/packages/teams-ai/src/authentication/TeamsBotSsoPrompt.ts#L105
Check:
https://github.com/microsoft/teams-ai/blob/8f0fbbd2cacf6694f8fca6fad63d26789851a648/js/packages/teams-ai/src/authentication/TeamsBotSsoPrompt.ts#L136
