### ISSUE TITLE
[Bug]: 401(Unauthorized) when calling Azure OpenAI

### ISSUE THREAD

**Issue by swatDong** [microsoft/teams-ai#1746]
### Language

Javascript/Typescript

### Version

1.3.0

### Description

Calling Azure OpenAI with API Key, the code to create `OpenAIModel`:
``` javascript
    const model = new OpenAIModel({
        azureEndpoint: "https://my-aoai.openai.azure.com/",
        azureDefaultDeployment: "gpt-35-turbo",
        azureApiKey: "xxx...."
    });
```

But get 401 response from AOAI:
```
{"statusCode":401,"message":"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired."}
```

Also found that, the request header has `"Authorization":"Bearer xxx..."`. But according to the [Azure OpenAI doc](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication), to use API Key, should use `api-key` header.

### Reproduction Steps

1. Use `@microsoft/teams-ai 1.3.0`
2. Create `OpenAIModel` with azure settings
   ```
    const model = new OpenAIModel({
        azureEndpoint: "https://my-aoai.openai.azure.com/",
        azureDefaultDeployment: "gpt-35-turbo",
        azureApiKey: "xxx...."
    });
   ```
3. Run the code / app.

**Comment by swatDong** [comment]
Looked into code and it seems to be caused by [here](https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/models/OpenAIModel.ts#L398-L410)

Created PR for my proposed fix. Feel free to create other fixes if I missed any scenario.

**Comment by rgudic** [comment]
Having same problems from this morning
