### ISSUE TITLE
[Dev support]: How to change AI response 

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#1762]
## Question
 
I am trying to modify the AI response from text to an adaptive card.    

For example, in the  dotnet  [04.e.twentyQuestions sample project](https://github.com/microsoft/teams-ai/tree/main/dotnet/samples/04.e.twentyQuestions), when a user asks a question, it currently provides a text answer. Instead, how can I alter the AI response to return an adaptive card? such as below image ,  

should i use output Moderator or something?

![image](https://github.com/microsoft/teams-ai/assets/5784846/0825d1a9-f37f-4a15-9400-1a2ec0c3f1ad)

**Comment by lilyydu** [comment]
The format of this response is controlled through the handler class-

For TwentyQuestions, your circled area is [captured here](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/04.e.twentyQuestions/GameBotHandlers.cs#L71C60-L71C86)

You can see our use of adaptive cards in the [TypeAhead sample's ActivityHandler class](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/03.adaptiveCards.a.typeAheadBot/ActivityHandlers.cs#L48), you can use the message factory class to send an attachment

**Comment by asith-w** [comment]
@lilyydu 
Thank your reply it was relay helpful.

In that case, I believe I should use the code below to manually get an AI response by registering  _OnActivity_ activity handler

```PromptResponse response = await _actionPlanner.CompletePromptAsync(turnContext, turnState, template, null, cancellationToken);```

**Comment by lilyydu** [comment]
Hi @asith-w,

You won't be calling that method in particular (thats used internally in our library), instead you will need to create your own custom activity handler-

Example of replacing the TwentyQuestionBot's handler with the logic from TypeAheadBot
        
```
public async Task OnMessageActivityAsync(ITurnContext turnContext, GameState turnState, CancellationToken cancellationToken)
        {
            Attachment attachment = CreateAdaptiveCardAttachment(_pathToAdaptiveCard);
            await turnContext.SendActivityAsync(MessageFactory.Attachment(attachment), cancellationToken); 
        };
```
        
You can use the [TurnState object](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/TURNS.md#turn-state) to access specific parameters. 

For TwentyQuestions specifically, the handlers are registered [here](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/04.e.twentyQuestions/Program.cs#L108)

**Comment by asith-w** [comment]
@lilyydu 
 this [handlers ](https://microsoft-my.sharepoint.com/:p:/p/aacebo/EWn81IhcaghFvNvxAjXsjusBwiYjuKAB2AsgdFznZB8UXA?e=28xjJ1)link is not accessible for me

just to clear the answer again. 

Here, what I tried

I created AI Chatbot template using visual studio toolkit and run the app
once I ask a question from the bot , it responses with text answer in Teams
I want to show this response text in a adaptive card , 
can I do it without manually calling _actionPlanner.CompletePromptAsync () 
 
or can i track AI response text before it sending activity such as this ?

```cs

public string SomeCompletePromptAsync (...)
{ 
    var promptResponseText = GetPromptResponseText (); 
    await turnContext.SendActivityAsync(MessageFactory.Attachment(GetCardAttachment(promptResponseText )), cancellationToken);

}

```

**Comment by lilyydu** [comment]
Hi @asith-w,

My apologies, I pasted in the wrong link and misunderstood your question. First, could you try [here](https://github.com/microsoft/teams-ai/blob/main/getting-started/MIGRATION/02.DOTNET.md#activity-handler-methods)

If you want to manually get a response from the LLM, you can call `CompletePromptAsync`. In the example of `TwentyQuestions`, you can replace [L71 ](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/04.e.twentyQuestions/GameBotHandlers.cs#L71) with

```
Attachment attachment = CreateAdaptiveCardAttachment(_pathToAdaptiveCard, guessCount, hint);
await turnContext.SendActivityAsync(MessageFactory.Attachment(attachment), cancellationToken); 
```

Extra data generated from the LLM can be passed through as method parameters.

If you do have a specific scenario in mind, you can utilize actions as well, the [LightBot](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/04.ai.c.actionMapping.lightBot/LightBotActions.cs) is a good example of this 

Could you attach the link to the AI Chatbot you are using so I could also give you more specific assistance?

**Comment by corinagum** [comment]
Closing as resolved. We can reopen if there's more activity.
