### ISSUE TITLE
[Dev support]: Teams bot conversations - Frequent downtime (Unauthorized 401 in weekends)

### ISSUE THREAD

**Issue by penguinsource** [microsoft/teams-ai#1766]
Please be sure to check the Discussions Q&A section before filing a new question.

## Question
Hello everyone! I have made a related post in a different repository (bot framework) and they have directed me this way. This is the original issue raised, a year ago - https://github.com/microsoft/botframework-sdk/issues/6601. The issues persists today.

## Describe the bug
I am sending POST requests to `https://smba.trafficmanager.net/amer` and receiving timeouts on my remote server (google cloud, app engine) - the same is not happening locally when using ngrok.

Nothing has changed on our code's behalf and it all started failing yesterday (June 14th).

## Expected behavior
Our platform proactively sends messages to an existing conversation (through the REST url) and then continues the conversation through a `bot-builder` implementation.

## Screenshots
<img width="1391" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/68e4e28e-7ec6-40b3-85a8-858c8860ff47">
<img width="1427" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/2596623/8dbe0fde-9d61-4155-8ed7-7c77a64fe7d0">

## Additional context
- Issue does not occur in ngrok, but it does occur on app engine instances
- Bot has been working fine for the past 2 years, but all of a sudden, something must have happened and it's now getting all these timeouts

```
 error: FetchError: request to https://smba.trafficmanager.net/amer/v3/conversations/a:17cILmBogFKvwOhSb3Qb8s8s8Mvi8-v28V74WaXT2do5qpcvX2iWx7u9TIFKgjUZCbC2Sbuy3LltGjgAxKHPhYDjwOaEarjchGEhQOtN2Rax4hMDG8YjSjl_rpBR-2yaD/activities/ failed, reason: connect ETIMEDOUT 52.114.142.186:443
      at ClientRequest.<anonymous> (/workspace/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (events.js:400:28)
      at TLSSocket.socketErrorListener (_http_client.js:475:9)
      at TLSSocket.emit (events.js:400:28)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    type: 'system',
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT'
  },
```

## Code Snippets

I store each user's MS Teams Authentication object in my database (this is our prod test user):
<img width="700" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/f4e843d5-984a-4215-9aab-de73adc56cc5">

Every time we make a call to send a (proactive) message or updating an existing conversation message, we use the `serviceUrl` defined in this `msTeamsAuth` object. All that code works fine throughout the week, and then starts receiving a 401 Unauthorized as shown in the above screenshots in the weekend (Sat to Monday) and then sometimes in the weekdays, too.

I have a simple function which sends a message every 5 mins (CRON job), which can more easily be used to debug this issue:

Getting data to make the proactive messaging call:
<img width="737" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/e2f68555-1bc7-43f7-ad6c-8ff3ef8c3213">

Sending a proactive message:
<img width="617" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/05d5a799-2e70-4e45-8212-429d6428b8dd">

I have just yesterday also added a hardcoded version of the `serviceUrl` set to `'https://smba.trafficmanager.net/teams/';` instead of the usual `'https://smba.trafficmanager.net/amer/';` which is what most of our prod users are using (according to their ms teams auth object).

This issue also occurs when a user answers an interactive message from our bot. This is a bot framework implementation. Code snippet for this:
Step 1:
<img width="565" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/6822f09e-1423-48d0-ae46-eac193fd8cae">

Step 2:
<img width="616" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/a7ea7ca9-680f-4c5b-90c7-b898e8eed74e">

## What's happening?

I have a good feeling that the traffic manager is blocking our prod bot during the weekends. The dev bot seems to work? I am not sure how to go about debugging it any further without additional help.

Thank you very much!

**Comment by corinagum** [comment]
@penguinsource thanks for filing this issue. I'm following up internally with this and will get back to you shortly.

**Comment by penguinsource** [comment]
thanks @corinagum . if it helps, if i upload my service to another endpoint, it seems like it does not fail. so the most likely issue is with the dns smba traffic manager limiting traffic per up/domain

**Comment by corinagum** [comment]
Hi @penguinsource. I've spoken with one of my colleagues and he has asked for further information. Once I get his github username, I will tag him here.

To quote: 

> for further investigation we would need more details about concrete failed requests. The MS-CV is not applicable here since the requests didn't come through, but at least bot id and timestamp of several problematic requests would be great help here.

Could you provide a few bot id and timestamps for a number of these problematic requests you've had? If possible, the more recent they can be, the better.

Thank you!

**Comment by corinagum** [comment]
Assigning this to @vsvandelik; could you please leave a comment on this GitHub issue and I can assign it to you for tracking?

**Comment by vsvandelik** [comment]
@penguinsource As @corinagum mentioned - if you could provide us with the bot id and timestamps where the requests didn't come through, we can investigate on our side what could possibly be the issue. 

> if it helps, if i upload my service to another endpoint, it seems like it does not fail. so the most likely issue is with the dns smba traffic manager limiting traffic per up/domain

Can you please confirm this is still valid and on another endpoint you don't see this issue? Are you still calling the same endpoint?

**Comment by pyramid-scheme-ceo** [comment]
Hi @corinagum @vsvandelik unfortunately I'm finding the same issue but pretty sporadically, not at any specific time.

Lots of requests similar to below are being marked as "Faulted" (sorry no status code, that's the best App Insights can give me as a dependency) after waiting ~20 seconds.

```
POST https://smba.trafficmanager.net/amer/v3/conversations/<conversation ID>/activities
```

We're currently sending up to 10 requests to the API simultaneously (thought this would be reasonable but let me know if there's rate limits I haven't seen in any docs) and some make it through while others don't...

![image](https://github.com/microsoft/teams-ai/assets/22147620/ebe02879-580e-4bbe-9d48-bc2e84ccd31b)

**Comment by penguinsource** [comment]
hey @corinagum @vsvandelik sorry for the delays! Okay so, I am seeing the same issue, but switching to send requests from a different IP fixes it until that ip gets "blocked", too.

Here are the production bot details:
BOT_NAME=WorkStory
BOT_ID=b30ea535-4b7b-4f4f-aa24-c63594e13b24

Earlier today timestamps:

<img width="1417" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/748d502f-cd15-44b9-b79c-50ad0b7c0d41">

Calls were made from domain `https://cdone-av5ptmyuga-uc.a.run.app/api`

-----
The flow I have going on to keep this up for our users is.. I have a cloud run server I deploy:
<img width="711" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/8d319ce2-2417-4f62-acca-daf7147fb6bc">

When one service gets blocked, I use the other one to send messages along with having to manually update the Messaging Endpoint on dev.botframework.com - you can see how this could be a hassle daily haha

**Comment by penguinsource** [comment]
hi @vsvandelik , did you get a chance to check this out on your side yet? cc @corinagum

**Comment by vsvandelik** [comment]
hey @pyramid-scheme-ceo sorry for delayed answer.

> Lots of requests similar to below are being marked as "Faulted" (sorry no status code, that's the best App Insights can give me as a dependency) after waiting ~20 seconds.

Unfortunately without additional details we won't be able to investigate the problem with failed requests. For further investigation we need to know at least the bot id and timestamps of the failed request. Even better if you can provide the header value under key `ms-cv`. The more details about the failed requests the better. You can select some and provide details for them.

> We're currently sending up to 10 requests to the API simultaneously (thought this would be reasonable but let me know if there's rate limits I haven't seen in any docs) and some make it through while others don't...

The rate limits are here: https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/rate-limit

**Comment by vsvandelik** [comment]
hey @penguinsource thanks for your patience.

I checked logs on Microsoft side for the first request in the table and I am seeing:

`IDX10223: Lifetime validation failed. The token is expired. ValidTo (UTC): '7/3/2024 11:29:12 PM', Current time (UTC): '7/5/2024 11:10:00 AM`.

Please check on your side how you are issuing tokens.

**Comment by penguinsource** [comment]
hey @vsvandelik ,
The token has a lifetime of 24h (86399s) and I am refreshing the token every 12 hours. I have previously also refreshed the token every hour in order to prevent this from happening and **thoroughly** tested it.
<img width="1045" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/deabf454-93f1-4041-aadc-4ef29a71801d">

I will add additional logs right away/now to show this, but it's very unlikely to be the reason. Can you help me with a few things from your side please:
1. Can you confirm that the access tokens from this endpoint really are set for 24h and not a lot less:
<img width="746" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/5cecf662-ba52-4e2b-83f3-e43257bef911">
2. Can you check if there are an unexpected amount of `Lifetime validation failed` errors on your side - this might prove a most system-wide token validation issue on your side if it's the case
3. Currently, I send a message every 10 minutes to an account to ensure that Teams is still up - essentially trying to have a health endpoint - is there an actual health endpoint or different method I can use to ensure that my token is `valid` and won't trigger a 401 unauthorized?

Thanks a lot,
Mihai

**Comment by penguinsource** [comment]
Actually, a really good test would be checking out the number of `Lifetime validation failed` errors coming in on your side during the downtime times that I am encountering, which is starting on friday/saturday to monday afternoon (EST times). If there are a lot more errors happening during that time range, then we will know there is actually something wrong on the Teams' side of things.

**Comment by corinagum** [comment]
@penguinsource I've asked @vsvandelik to look further into the logs. 

In the meantime, could you share with me more about how you are doing bot authentication / token caching? I was speaking to another bot engineer and he said that if using the SDK auth, caching is handled automatically.

**Comment by penguinsource** [comment]
Every instance of a server that we run has an interval that used to run every 12h (now runs every 2h) that automatically refetches a new token.

Code to fetch the token:
<img width="609" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/f5ec8915-3c1a-4c1a-911a-b7513fd9d1d1">

Code for the 2h interval to refresh token:
<img width="464" alt="image" src="https://github.com/microsoft/teams-ai/assets/2596623/a7f85729-5dd2-455c-95d4-d15d167a6d06">

**Comment by corinagum** [comment]
Can I ask the need for manually fetching the token? What is your intent for keeping a 'healthy endpoint'? 

Have you tried this sample that sends proactive messages using the SDK code, meaning you don't have to handle tokens manually? The SDK handles it for you. https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/16.proactive-messages

Other than needing to check the SMBA logs, this is a token concern and doesn't fall under Teams AI library support. I'm trying to figure out the best person to direct you to, and answers to the above questions will help :)

**Comment by penguinsource** [comment]
Acknowledged @corinagum , please let me get back to you. We are looking into the SDK proactive messaging now.

**Comment by penguinsource** [comment]
We've implemented and deployed the changes, so we dont contact smba.trafficmanager manually anymore. Let's keep this ticket open until next week, to confirm that this fixes it (or not). Thanks! Will follow up in 1 week!

**Comment by corinagum** [comment]
@penguinsource wonderful! I think this will prevent a lot of token-related issues like what you've had above and others that may come up with a custom implementation. Thanks for your patience while we dug down on this.

**Comment by pyramid-scheme-ceo** [comment]
Hey @vsvandelik sorry for the delay on my end too! The bot ID is 61aa6197-4b01-4bb4-a7a6-6ecf477654a0 and some example timestamps (UTC) are
* 04/07/2024, 04:01:34.491
* 04/07/2024, 04:01:34.489
* 03/07/2024, 23:01:12.875

**Comment by pyramid-scheme-ceo** [comment]
Not doing anything particularly unorthodox with the connections/authentication I think, here's the setup:

ConnectorClientFactory.cs
```
...
        public IConnectorClient Create(string serviceUrl)
        {
            AppCredentials.TrustServiceUrl(serviceUrl);
            var credentials = new MicrosoftAppCredentials(_configuration.AppId, _configuration.AppSecret);

            return new ConnectorClient(new Uri(serviceUrl), credentials);
        }
...
``` 

ConversationService.cs
```
...
            var connectorClient = _connectorClientFactory.Create(teamsUser.ServiceUrl);

            try
            {
                // Judging by the logs, the error is happening here
                await connectorClient.Conversations.SendToConversationAsync(teamsUser.ConversationId, activity, cancel);
            }
            catch (Exception e)
            {
                // Rate-limiting exception
                if (e is HttpOperationException ex && ex.Response != null && (uint)ex.Response.StatusCode == 429)
                {
                    _logger.LogError("Rate limit reached for tenant {TenantId}", tenantId);
                }
                else if (e is ErrorResponseException exception && exception.Body.Error.Code == "ConversationBlockedByUser")
                {
                    return SendMessageResult.Failed(CommonMessages.BlockedByUser, trackingId);
                }
                else
                {
                    _logger.LogError(e, "Failed to send message in tenant {TenantId}", tenantId);
                }

                return SendMessageResult.Failed(e.Message, trackingId, userId ?? default(long));
            }
...
```

**Comment by corinagum** [comment]
@pyramid-scheme-ceo please make sure you are using the built in bot framework token management, as shown in the sample I linked above. I will ping @vsvandelik on those timestamps but I suspect his feedback will be the same as above.
