### ISSUE TITLE
[Dev support]: Is there option for configuring Prompt starters

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#1775]
## Question
Hello All,

I would like to know about Prompt starters such as below image.  

is it possible to set those pre built commands via teams-ai library when user open the chat bot like copilot ?

also , If I want to give personalize suggested prompts based on conversation history, context, user profile and org , should I implement it manually or is there any built-in option ? 

![image](https://github.com/microsoft/teams-ai/assets/5784846/2a6cc22e-39fa-474e-a82b-5e3cae8aa638)

 thanks

**Comment by corinagum** [comment]
@Carter425 could you or Yoga provide link to public documentation? Not sure what his GitHub username is.

**Comment by Carter425** [comment]
I would like to know about Prompt starters such as below image.

is it possible to set those pre built commands via teams-ai library when user open the chat bot like copilot ?
**This feature and the docs are coming very soon. It will be possible and encouraged to utilize it with the Teams AI Library.**

also , If I want to give personalize suggested prompts based on conversation history, context, user profile and org , should I implement it manually or is there any built-in option ?

**Prompt starters based on the above would need some custom logic to implement based on those criteria.**

**Comment by asith-w** [comment]
@Carter425 @corinagum  
Thank you for the information
