### ISSUE TITLE
[Feature Request]: cert support for python sdk

### ISSUE THREAD

**Issue by yukun-dong** [microsoft/teams-ai#1776]
### Scenario

The TeamsAdapter only supports bot id and bot password. 
![image](https://github.com/microsoft/teams-ai/assets/25220706/4a8e0263-49df-44a7-a6e1-e03e97b84f09)
![image](https://github.com/microsoft/teams-ai/assets/25220706/5bb8b14f-2028-4e65-b1d6-4df83058cb1b)

### Solution

TeamsAdapter can accept cert related parameters.

**Comment by lilyydu** [comment]
Hi @yukun-dong,

We are currently blocked by Bot Framework Python SDK for this feature. However, their team is working on adding support for this

**Comment by corinagum** [comment]
@yukun-dong could you please file this issue with the Bot Framework team? cert auth is not yet supported in the BF SDK which would be a pre-cursor to it being added to our library.
