### ISSUE TITLE
[Bug]: Handoff activity does not get triggered when the deeplink URL message is sent from M365 Copilot (or any other client)

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-ai#1779]
### Language

Javascript/Typescript

### Version

latest

### Description

Following this [Developer Guide](https://microsoft-my.sharepoint.com/:w:/p/prkare/ERw-RG_YK9lCuaiObe0iiokBBg2k9BUp2JW8RY-IFkuquQ?wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1715958771382&web=1), I've created both the BotFramework project, based on this [repository](https://github.com/OfficeDev/Copilot-for-M365-Samples/tree/main/samples/msgext-northwind-inventory-ts), and the Teams AI Library project - both implementing the handoff use case scenario. 
While the BotFramework project is property get triggered every time the deeplink URL (https://teams.microsoft.com/l/chat/0/0?users=28:${botId}&continuationToken=${continuationToken}) is clicked from M365 Copilot response, the Teams AI Library seems to ignore this event. 
The sample of the `handoff` code implementation using Teams AI Library can be viewed here: https://github.com/microsoft/teams-copilot-starter/blob/main/src/bot/teamsAI.ts#L377
 

### Reproduction Steps

```bash
1.Add handoff handler to your Bot
2. Using M365 Copilot and the Developer Guide (link provided above) implement the Copilot plugin that returns the item containing the deeplink ("https://teams.microsoft.com/l/chat/0/0?users=28:${botId}&continuationToken=${continuationToken}") to the Bot chat.
3. When clicking on the deeplink URL, the Bot's chat is opened, but nothing is received in the bot handoff handler (nor there any other activities are triggered)
...
The expected behavior:
3. when clicking on the deeplink URL, the Bot's chat is opened and the Bot's handoff handler receives the activity containing the `continuationToken` passed in the deeplink URL.
```

**Comment by aacebo** [comment]
@dannygar is the bot receiving an activity payload to your endpoint `/api/messages` before the `adapter.process` is called?

**Comment by aacebo** [comment]
also it looks like your deeplike is not following the design document that states to use query param `continuation` **not** `continuationToken`
![image](https://github.com/microsoft/teams-ai/assets/44811138/5a8711cc-884b-4e1f-9932-7cdf3717ee98)
![image](https://github.com/microsoft/teams-ai/assets/44811138/6eb17250-5310-4fc5-976e-41d824e8b44d)
