### ISSUE TITLE
[Bug]: max_input_tokens is passed to max_tokens (which is actually the max output tokens)

### ISSUE THREAD

**Issue by TylerLu** [microsoft/teams-ai#1800]
### Language

C#

### Version

latest

### Description

I set `max_input_tokens` to `8000` in _config.json_ of the default prompt:
```json
{
  "schema": 1.1,
  "type": "completion",
  "completion": {
    "model": "gpt-4o",
    "max_input_tokens": 8000,
    "max_tokens": 1024,
    ...
  }
}
```
I asked the bot a question and the Bot returned the following error:
```The bot encountered an unhandled error: The chat completion API returned an error status of BadRequest: max_tokens is too large: 8000. 
This model supports at most 4096 completion tokens, whereas you provided 8000.
Status: 400 (model_error)
Content: 
{
  "error": {
    "message": "max_tokens is too large: 8000. This model supports at most 4096 completion tokens, whereas you provided 8000.",
    "type": null,
    "param": "max_tokens",
    "code": null
  }
}
```
Below is the request and response captured by Fiddler:
![image](https://github.com/microsoft/teams-ai/assets/11844726/2ca8d8bd-6010-4fb1-9ce8-2069c15e41d8)

According to [OpenAI's document](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens), `max_tokens` is the "**the maximum number of tokens that can be generated in the chat completion**". So `max_tokens` is accutally the max output tokens, and the `max_input_tokens` should not be passed to it.

Related code:
 * Link: https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Models/OpenAIModel.cs#L153
 * Screenshot:
   ![image](https://github.com/microsoft/teams-ai/assets/11844726/1167526b-d19c-4192-a0a9-1478ccafe38b)

### Reproduction Steps

```bash
1. Set `max_input_tokens` to 8000 in config.json of the default prompt.
2. Debug the Bot. 
3. Ask the Bot a question.
```

**Comment by TylerLu** [comment]
@singhk97 Thank you for the response! I appreciate your efforts in fixing this.

**Comment by hemanthaar** [comment]
We are also facing the same error and found the issue as mentioned above, Any ETA on pushing the fix. Please let us know. Thanks.
