### ISSUE TITLE
[Dev support]: What is the OAUTH_CONNECTION_NAME 

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#1801]
## Question
In the OAuth bot sample project settings file, there is a property named OAUTH_CONNECTION_NAME. I am wondering where this value comes from and where you can find it. can it find from the Azure AD app registration?
[OAUTH_CONNECTION_NAME ](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/USER-AUTH.md#configuring-the-application)

[samples](https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/06.auth.oauth.bot/appsettings.Development.json
## Code snippets) 
```CSHARP
 AuthenticationOptions<AppState> options = new();
options.AddAuthentication("graph", new OAuthSettings()
    {
        ConnectionName = config.OAUTH_CONNECTION_NAME,
        Title = "Sign In",
        Text = "Please sign in to use the bot.",
    }
);
```

**Comment by singhk97** [comment]
It is part of the Azure bot resource. The OAuth connection defines the OAuth settings used by the bot and can be configured in the Azure bot resource.

https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-register-aad?tabs=windows#to-update-oauth-connection-for-your-bot-resource
