### ISSUE TITLE
[Dev support]:Ssupporting streaming responses

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#1804]
## Question
Does the current [teams-ai](https://github.com/microsoft/teams-ai) .NET library or any other library support streaming responses?   

Is this JS sample related to streaming responses? [GitHub link](https://github.com/microsoft/teams-ai/blob/817c6cefe331a6dce2e7d2c021ff24c6f9990145/js/packages/teams-ai/src/StreamingResponse.ts#L21)"

 

thanks

**Comment by corinagum** [comment]
Hi @asith-w, while streaming has been implemented in this library for JS, it has not yet been implemented for Python or C#. That being said, the backend functionality is not quite ready for public release yet, so until then streaming won't yet be available to use.
