### ISSUE TITLE
[Bug]: GetNickName code is not correct

### ISSUE THREAD

**Issue by chenxizhang** [microsoft/teams-ai#1806]
### Language

Javascript/Typescript

### Version

latest

### Description

This is an issue of the code sample in the default template, In both JS and Python template.

![image](https://github.com/microsoft/teams-ai/assets/1996954/8b2701b3-ef2f-4d18-9ce8-c40b5b955f65)

### Reproduction Steps

```bash
Create a new teams app by using the default template (Custom Copilot => AI Agent) and check the code in `src\app\app.ts`.



export async function getNickname(
  context: TurnContext,
  state: TurnState,
  parameters: NicknameParameters
): Promise<string> {
  const nicknames = {
    "San Francisco": "The Golden City",
    "Los Angeles": "LA",
  };

  return nicknames[parameters.location] ?? `No nickname for ${parameters.location} found`;
}
```
```

**Comment by corinagum** [comment]
Hi @chenxizhang, it looks like you are using a template from https://github.com/OfficeDev/Teams-Toolkit-Samples. We don't manage those samples. Please file your bug there :)
