### ISSUE TITLE
[Bug]: max_tokens in openai_model.py wrongly set

### ISSUE THREAD

**Issue by bx0048** [microsoft/teams-ai#1835]
### Language

Python

### Version

1.2.1

### Description

In the complete function in openai_model.py the following assignment is used in line 126:

max_tokens = template.config.completion.max_input_tokens

later this variable is used in line 197 as input for the OpenAI model to set the max. number of output tokens, leading to not being able to set the max_input_tokens to higher than 4k.

### Reproduction Steps

```bash
1. set the max_input_tokens in config.json > 4k
2. call the OpenAI model
3. Error about the max_tokensize will occur
...
```

**Comment by lilyydu** [comment]
C# version - #1800
