### ISSUE TITLE
[Feature Request]: Streaming bot response token by token

### ISSUE THREAD

**Issue by kushalbhabra** [microsoft/teams-ai#185]
The current bot response is shown to the user when full text is generated. 

This increases the wait time for user to see output. 

> Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Would like to have a feature where output can be streamed token by token, which will improve user experience. 

Similar to how it's shown on ChatGPT portal or Co-Pilot demo shown in MS Build.

> Provide a clear and concise description of what you want to happen, with code snippets or pseudo code as applicable.

In code developer can specify the activity type to be streamed text instead of fixed text.

> Provide a clear and concise description of any alternative solutions or features you've considered.

I've considered updating response activity every 1-2 seconds, but that seems like a hack and overhead code.

> Add any other context or screenshots about the feature request here.

If it requires MS Teams product team to make changes, do we know if this is in their roadmap? 

Meanwhile any workaround suggestions will also be helpful.

**Comment by corinagum** [comment]
@kushalbhabra please provide some sample code that has the response taking too much time. Have you noticed a difference in performance when you have a shorter plan?

**Comment by Stevenic** [comment]
@kushalbhabra the Teams Client doesn't support streaming responses from bots and this would require such a huge infrastructure change by the Teams Platform that I don't see this feature being supported anytime soon...

While we could certainly add support for letting OpenAI stream responses to the bot there would be little value in doing so as you'd have to wait for the complete response before sending to the teams client anyway.

**Comment by corinagum** [comment]
Thanks Steve for the response. I've marked this as `wontfix` and will close.

**Comment by xyg189** [comment]
I want this feature also. Can we use context.updateActivity() send steaming messages to user?

**Comment by Daviderikmollberg** [comment]
I second the above. This would be a very important feature, especially for cases where you can't rely on ChatGPT3.5 (which is the case for most languages in the world excluding the big ones). The wait time for ChatGPT4 is unbearably slow if you have to wait for the entire response before ingest the answer.  The token-by-token streaming is essential for a good user experience in this case. 

Has there been any movement on this? And is there a correct channel to advocate for this feature?

**Comment by rick-li** [comment]
Any update on above issue ?

> I want this feature also. Can we use context.updateActivity() send steaming messages to user?

I'm using this updateActivity to stream the response from openai api, not sure how it affect the performance, i hope teams sdk can support it natively.

i see some demo of ms365/copilot chat which shows response is streaming, not sure how it is implemented.

**Comment by lilyydu** [comment]
@kushalbhabra @xyg189 @Daviderikmollberg @rick-li 

Thanks everyone for your ideas and feedback! We recognize the importance of this feature and are currently exploring how to enable this capability. Please keep sharing your input on this, and we will keep you posted with future updates.

**Comment by mc-ccit** [comment]
Hi @lilyydu ,

With all the great new features from MS build, will there be any updates on this feature as of yet?
