### ISSUE TITLE
Python | Citations With openai assistants

### ISSUE THREAD

**Issue by ahmedmahmoudR** [microsoft/teams-ai#1875]
### Language

Python

### Version

latest

### Description

I have built a Teams Bot using the Teams AI library and integrated it with OpenAI Assistants. However, the citations with the assistants API file search (vector store  )are not working. I need guidance with a code example on how to do this

![image](https://github.com/user-attachments/assets/9a989b9f-87a0-4012-81ce-571484e72357)

### Reproduction Steps

```bash
1.Open Bot from teams 
2. Send Question to Bot
3. Return from openai file-search without citations reference 
...
```

**Comment by ahmedmahmoudR** [comment]
When AI-powered features like Feedback Loop and citations. will be generally available ?

**Comment by ahmedmahmoudR** [comment]
hey @corinagum  can I apply this with python ?  [#1590](https://github.com/microsoft/teams-ai/issues/1590)

**Comment by corinagum** [comment]
Yes, #1590 applies to all 3 languages at this time. I will close this issue as a duplicate.

**Comment by ahmedmahmoudR** [comment]
Hi @corinagum, I didn't get it. If it's applicable, is there any documentation for this?

**Comment by ahmedmahmoudR** [comment]
> When AI-powered features like Feedback Loop and citations. will be generally available ?

@corinagum  Why did you ignore this question?

**Comment by corinagum** [comment]
#1590 is the work item for assistants with citations, which hasn't been completed yet for any of our 3 supported languages. that is why at this time there is no further available documentation as it is not yet implemented with our library.
