### ISSUE TITLE
[JS] Sensitivity Label

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#1876]
https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3816509

**Comment by lilyydu** [comment]
Closing out as complete via [this guide](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage#add-sensitivity-label) - requirement was to allow developers to add sensitivity label to a message through the `PredictedSayCommand` which can be achieved today.
