### ISSUE TITLE
[Dev support]: Use local llm

### ISSUE THREAD

**Issue by rcalv002** [microsoft/teams-ai#1879]
Scenario
The official documentation at https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/teams-conversation-ai-overview mentions that we can use local llms. I found this to be possible with the typescript sdk as i could pass in an endpoint, but was unable to find the equivalent for the dotnet SDK.

Solution
Provide an overload on the dotnet sdk to pass in endpoint and model name so we can use local openapi compliant apis like ollama?

**Comment by rcalv002** [comment]
Any chance you could provide a sample? I'm spent plenty of time trying to accomplish this and although embedding generation seems to work, implementing the PromptCompletionModel (public class OllamaAIModel : IPromptCompletionModel) and using it did direct api calls to my ollama instance, but to endpoints that dont exist. Here's what it tries to reach for chat completions

"/v1/openai/deployments/llama3/chat/completions?api-version=2024-04-01-preview"

where it should just be "/v1/chat/completions"

It's been an endless rabbit hole of dependencies without much real progress. The teams ai overview page mentions support for this several times but I haven't seen any guidance offered.

**Comment by Stevenic** [comment]
@rcalv002 it looks like you're trying to configure your model with Azure OpenAI settings... The URL's for Azure are different then standard OpenAI URL's and they're not going to work with projects like Llama.cpp or Ollama.  You need to configure your model instance with OpenAI settings and configure a custom endpoint. You'll also still want to provide an OpenAI key but this can be anything so just set it to "none" or something.

I've only tested Llama.cpp (using the TS SDK) and haven't tested other projects like Ollama but any OpenAI compatible chat endpoint should work. What framework are you trying to run your local llm with?
