### ISSUE TITLE
[Feature Request]: Support for Teams AI library in Visual Studio

### ISSUE THREAD

**Issue by kimizhu** [microsoft/teams-ai#188]
Copied issue from https://github.com/OfficeDev/TeamsFx/issues/9080

Details from original issue:

Is your feature request related to a problem? Please describe.
I want to get started with Teams AI library but this [article](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams%20conversational%20ai/conversation-ai-quick-start) says I have to use VS Code. However I have used VS2022 and Blazor to build my current Teams app and it would be annoying to have to have a separate VS Code project for any AI library integrations.

Describe the solution you'd like
Will you be providing support for VS 2022 and Blazor?

Describe alternatives you've considered
N/A

Additional context

![image](https://github.com/microsoft/teams-ai/assets/11223734/887223d8-9e1b-4e10-a8d3-eb6f7d4bc0f6)

**Comment by corinagum** [comment]
From #217 (Duplicate)

> It is part of the Visual Studio installer. TTK is not supported for dotnet in VS Code, only Visual Studio.

**Comment by corinagum** [comment]
Reopening this item for tracking TTK work @kuojianlu

**Comment by corinagum** [comment]
Closing as resolved
