### ISSUE TITLE
[Bug]: Bot does not respond when deployed but works correctly in local environment. 

### ISSUE THREAD

**Issue by anishgurjar** [microsoft/teams-ai#1882]
I have a team AI bot that uses RAG to chat over data which works perfectly fine in local environment, but as soon as I deploy it does not response. 

When I debug in test tool and in teams via chrome and edge, the bot works great. To deploy it, I did the following steps:

a. Provision - successful without any errors
b. Deploy - successful without any errors
c. Publish - successful without any errors
d. App is validated and there are no errors there either.

Next, I go on my developer portal and click Preview in Teams. When I text the bot here when it is published, not response as shown in the screenshot. The red highlighted section is how it worked correctly in my local environment and the yellow messages are sent when the app is published. 

Even after publishing the app for the org through the teams admin center, there is no response. 

Since it worked perfectly fine on my local environment, I don't think any of my code is wrong. What am I missing that is not sending the request when the bot is published? 

Thanks a lot for the help!
<img width="817" alt="Capture" src="https://github.com/user-attachments/assets/4f1b7be4-189a-4c3e-86eb-f986758f49d7">

**Comment by francis-xavier-inyangat** [comment]
issue was closed, where is the link to the solution @anishgurjar
