### ISSUE TITLE
[Bug]: TeamsAI bot cannot be deployed to cloud using Teams Toolkit

### ISSUE THREAD

**Issue by anishgurjar** [microsoft/teams-ai#1888]
### Language

Javascript/Typescript

### Version

latest

### Description

**Describe the bug**
Hi. This issue is targeted to both Teams Toolkit team and Teams AI team since I am not sure which team is responsible for this. 

I am trying to chat over my data using Azure OpenAI and have that as a teams bot. Last week, the deploy to Teams feature was created mentioned here: [https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/announcing-deploy-to-teams-from-azure-openai-studio/ba-p/4198388](url)

The article goes into great detail about how to debug in local environment, which works perfectly fine on my local environment too. I'm able to chat over my data, get citations, have the feedback loop, and all the fancy features. 

The article however provides no guidance on deploying this to cloud. I followed Teams Toolkit guidelines to provision, deploy and publish the app. I also validated the app. No errors in any of the stages. 

However, when I preview the app on remote environment in Teams using dev.teams.microsoft.com portal, I always get "Bot encountered an error. Check source code". There is almost no doucmentation that I could find on how to exactly log those errors on application insights. 

I am wondering if someone has ever tried deploying the actual TeamsAI library to a remote environment instead of merely debugging it in local environment. 

**What I have tried to troubleshoot**:
1. Double checked that I have cognitive services openAI user role and the app service has Cognitive Services OpenAI User role assignment as suggested in the article and the readme.
2. Made sure to verify that provision and deploy happened successfully, and resources were properly created in Azure. 

Any help, from either of the teams is appreciated. 

### Reproduction Steps

```bash
**To Reproduce**
Steps to reproduce the behavior:
1. Go to oai.azure.com
2. Follow [https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/announcing-deploy-to-teams-from-azure-openai-studio/ba-p/4198388](url) article. It's basically having an Azure AI search resource and uploading documents to perform RAG. 
3. Validate the app, provision the app, and then deploy the app. 
4. Visit [https://dev.teams.microsoft.com/home](url) and preview the app in teams.
```

**Comment by Carter425** [comment]
Hi @anishgurjar,

I understand that John Miller from Teams Toolkit has also gotten in touch with you.

There was an error in the instructions for assigning the Cognitive Service OpenAI User role after deploying to Azure. You should be assigning the Cognitive Service OpenAI User role from your deployed custom copilot User Assigned Managed Identity to your Azure OpenAI resource whereas the instructions note using the system assigned identity on the App Service resource.

The instructions in the README and Learn Docs are being updated.

You can follow the instructions below after deploying your app to Azure. Please note that you must use a Microsoft 365 account with the same tenant as your Azure account used during setup, as this app is securely configured for single-tenant usage.

**Assigning Cognitive Service OpenAI User role from your deployed custom copilot User Assigned Managed Identity to your Azure OpenAI resource**

As this sample uses managed identity, you must assign Cognitive Service OpenAI User role from the custom copilot's User Assigned Managed Identity to your Azure OpenAI resource after deploying your app to Azure for your deployed custom copilot to receive responses from Azure OpenAI.

Go to [Azure portal](https://portal.azure.com/) and select resource groups

Select the resource group you deployed your custom copilot to

Select the Managed Identity resource

Click Azure role assignments

Click add role assignments.

Under Scope select Resource group

Under Subscription select the Azure subscription of your Azure OpenAI resource

Under Resource group select the resource group with your Azure OpenAI resource

Under Role select Cognitive Service OpenAI user

Select save to finish assigning the role

Now, your published custom copilot Teams app is ready for use in Teams accounts with the same tenant as the Azure account used during setup.
