### ISSUE TITLE
[C#] Update `OpenAIModelFactory.cs` to use constructors instead of deserializing json

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#1910]
**Requirements**
* Upgrade `OpenAI` package to v2.0.0-beta.8
* Replace json deserialization code in `TestUtils/OpenAIModelFactory.cs` by initializing using the respective constructors.

**Context**
Up until v2.0.0-beta.8 some classes didn't allow setters on properties that needed to be mocked so I had to deserialize json strings.

**Comment by manojks1999** [comment]
@singhk97 ,

Can I work on this issue ?

**Comment by singhk97** [comment]
The `OpenAI` package has been updated to `v2.1.0-beta.1`
