### ISSUE TITLE
[Bug]: Outdated Documentation on "Powered by AI" Section

### ISSUE THREAD

**Issue by XariZaru** [microsoft/teams-ai#1947]
### Language

Python

### Version

latest

### Description

Trying to follow the "Powered by AI" steps listed here: [Powered by AI](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/POWERED-BY-AI.md)

The following sample code:
```python
app = Application[AppTurnState](
    ApplicationOptions(
        ...,
        ai=AIOptions(
           enable_feedback_loop=True
        ),
    )
)
```

The AIOptions object requires a "Planner" object. I don't see other examples or how Planner would be used. Maybe there is some documentation I missed?

### Reproduction Steps

```bash
1. Followed steps according to "Powered by AI" documentation
2. Could not run sample code. Missing some context.
```

**Comment by corinagum** [comment]
@XariZaru A Planner is one of the building blocks for setting up the AI module. Please see the linked sample and link to the docs. 
https://github.com/microsoft/teams-ai/blob/main/python/samples/04.ai.d.chainedActions.listBot/src/bot.py#L57
https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/PLANNER.md

**Comment by XariZaru** [comment]
> @XariZaru A Planner is one of the building blocks for setting up the AI module. Please see the linked sample and link to the docs. https://github.com/microsoft/teams-ai/blob/main/python/samples/04.ai.d.chainedActions.listBot/src/bot.py#L57 https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/PLANNER.md

Thank you so much. This documentation helps. I have a question. The LLM I am using is hosted externally and accessed via an REST endpoint. It looks like this feedback mechanism is for natively supported LLMs in library. What would you recommend as a best alternative to gathering feedback from users if not through this functionality?

**Comment by corinagum** [comment]
Please see our Llama sample (JS only) for implementing your own custom LLM client.

feedback loop is related to Teams client, not the LLM directly, so you would just need to add handling of the incoming feedback responses, as you would need to do for OAI too. If you mean storing the feedback, we do not currently provide guidance on that as it is the user's discretion on how to store data.

**Comment by XariZaru** [comment]
> Please see our Llama sample (JS only) for implementing your own custom LLM client.
> 
> feedback loop is related to Teams client, not the LLM directly, so you would just need to add handling of the incoming feedback responses, as you would need to do for OAI too. If you mean storing the feedback, we do not currently provide guidance on that as it is the user's discretion on how to store data.

So I enabled feedback_loop to true but in the bot emulator framework kit that Microsoft provides, I do not have the option to react to the message. Is this only testable in Teams itself?

![image](https://github.com/user-attachments/assets/b608164c-1f28-4a82-8ce5-fcffb2dcb20e)

**Comment by corinagum** [comment]
Yes, this is a Teams only feature.
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/b345428e-7d9e-42c6-b8f0-27421cb3af21">
