### ISSUE TITLE
[PY/JS]: Chat Completions Tools - Bug Bash 

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#1955]
```[tasklist]
### JS samples
- [x] JS LightBot - OAI ✅ Corina
- [x] JS LightBot - AOAI ✅ Corina
- [x] JS ListBot - OAI - ✅  Corina
- [x] JS DevOps bot - OAI
- [x] JS DevOps bot - AOAI ✅ Corina
- [x] JS CardGazer - OAI #2039
- [x] JS CardGazer - AOAI
- [ ] JS WhoBot - OAI Brian?
- [ ] JS WhoBot - AOAI Brian?
- [x] JS ListBot - AOAI ✅ Corina
```

```[tasklist]
### PY samples
- [x] PY LightBot - OAI  ✅ Lily
- [x] PY LightBot - AOAI ✅ Lily
- [x] PY ListBot - OAI  ✅ Lily
- [x] PY ListBot - AOAI
- [x] PY DevOps bot - OAI  ✅ Lily
- [x] PY DevOps bot - AOAI ✅  Brian
- [x] PY Langchain - OAI  ✅ Lily
- [x] PY Langchain - AOAI ✅  Brian
```

## Directions:

1. Pull latest changes from this repo and open the sample's folder. 
2. Comment out this code in `teamsapp.local.yml`: 
![image](https://github.com/user-attachments/assets/e82237bf-f18f-4c33-add3-149e5ae60fd1)
    This is to make sure you are using the latest code changes, not what is latest published code.
3. Add AOAI key and endpoint or OAI key to `.env`, `.env.local.user`, and update `azure.bicep` and `azure.parameters.json` with the key and/or endpoint. 

`.env.local.user`: 
![image](https://github.com/user-attachments/assets/184c170b-8a24-4be3-8897-0ab8fa7879c9)

`.env`:
![image](https://github.com/user-attachments/assets/6c708dca-cca4-4524-9bbe-b68f304b2c8a)

`azure.bicep`:
![image](https://github.com/user-attachments/assets/b385910f-3f35-4c67-b777-b07c38dcdd51)

4. Run the sample and if no problems detected, please add a checkmark with your name above. If you do come across any problems, please list details of which sample / what model(s) you used, take screencaps of the chat log, and other error messages or related context, and post them as a comment here. Feel free to put an ❌ with your name in the tasklist above.

Having more than one person per sample per LLM would be much appreciated. Thank you!

**Comment by lilyydu** [comment]
testing with non-specified parallel_tool_calls is throwing 400 because of the AOAI API

[#1492](https://github.com/openai/openai-python/issues/1492)

**Comment by BMS-geodev** [comment]
PY Langchain - AOAI tested with proper creds. Seems fully functional.

**Comment by BMS-geodev** [comment]
`PY DevOps bot - AOAI` tested and working properly. I've made note of a response text formatting issue with the team for further discussion.
