### ISSUE TITLE
[Feature Request]: Get an user by ID without a Team or a Conversation Reference

### ISSUE THREAD

**Issue by XVincentX** [microsoft/teams-ai#1959]
### Scenario

The primary use case is background processes that need to notify users when some events happen. Currently developers are forced - when the bot starts or whenever possible, to loop through a bunch of teams to save the IDs of the potential people we want to contact, but it's brittle and annoying.

### Solution

An API to get user reference without having needing a Team ID reference or a conversation reference

### Additional Context

I know this might not be the right repository - but I have been advised by another Microsoft Employee to post it here :)

**Comment by corinagum** [comment]
Can you provide more information and context about what your request is? What does the current code look like? Is this in a chat or a channel? What is the user scenario here; why do they need a bot collecting IDs? Who recommended you post here? Perhaps they can provide more context?
