### ISSUE TITLE
[Bug]: Getting an error "The operation was canceled" from CompletePromptAsync method

### ISSUE THREAD

**Issue by mukeshmrajput** [microsoft/teams-ai#1960]
### Language

C#

### Version

latest

### Description

We're calling "CompletePromptAsync" method manually from the incoming activities handles in the code. The problem is, we're having 9 static questions that we're sending to Azure Open AI ChatCompletiond API sequentially with prompt through the "CompletePromptAsync" method. Looks like first 3 to 4 question are being answered and rest all are fails with error message "The operation was canceled"

### Reproduction Steps

```bash
1. Using dotnet sample (dotnet\samples\08.datasource.azureaisearch\AzureAISearchBot)
2. Updated Azure->OpenAIApiKey and Azure->OpenAIEndpoint in appsettings.json file
3. Changed model name to gpt-4o in prompt config file and updated data_sources to Vector Database index (Cognitive Search)
5. Program.cs: Added below line to listen incoming message handler.
   app.OnActivity(ActivityTypes.Message, activityHandlers.OnMessageActivityAsync);
6. In incoming message handler. Calling "CompletePromptAsync" method manually for static 9 questions in sequentially looping along with keep updating turnState.Temp!.Input to runtime question. 
7. We're seeing prompt response successful from "CompletePromptAsync" method for first 3 to 4 questions then rest all questions giving prompt response "Error" with "The operation was canceled".
8. Need suggestion or help why such error throwing? what's the fix for it
```

**Comment by PjPraveenkumar** [comment]
Hi @mukeshmrajput thanks for reaching out to us. I'll validate and get back to you.

**Comment by PjPraveenkumar** [comment]
hello @mukeshmrajput could you please share the code snippet for calling the "CompletePromptAsync" method manually for static 9 questions in sequentially looping along with keep updating turnState.Temp to validate it from our end?

**Comment by mukeshmrajput** [comment]
Thanks @PjPraveenkumar for your support. 

We're using dotnet sample (dotnet\samples\08.datasource.azureaisearch\AzureAISearchBot) with our own vector DataSource as RAG. You can paste attached files in this sample project and configure Azure Open AI Endpoint and Key in appsettings.json and try to reproduce the error.

Regarding console log, we're trying it to get for you and share here, meantime you can give try with attached files.

Thanks,
Mukesh
[DotNetFiles.zip](https://github.com/user-attachments/files/16814024/DotNetFiles.zip)

**Comment by mukeshmrajput** [comment]
Hi @PjPraveenkumar  

Attached the console logging of AI modules
[consol_log.txt](https://github.com/user-attachments/files/16832531/consol_log.txt)
 for your reference

**Comment by mukeshmrajput** [comment]
Hi @PjPraveenkumar 

Attached another log wherein if you look at ChatCompletionAPI call at line # 642, 692 and 732 never return back with response. Strange part in between all these line numbers are the line number 688 which telling sending FIN, it could be the problem for not returning response for the calls at mentioned lines 

[console_log_4Sept.txt](https://github.com/user-attachments/files/16870532/console_log_4Sept.txt)

**Comment by mukeshmrajput** [comment]
Hi @PjPraveenkumar 

I haven't heard back anything from you on this. Are you actively looking into this?

Thanks,
Mukesh

**Comment by PjPraveenkumar** [comment]
Hi @mukeshmrajput Apologies for the delay. I’ve been unable to validate due to some access issue, which has prevented me from checking further. I’ll provide an update as soon as possible.

**Comment by mukeshmrajput** [comment]
Thanks @PjPraveenkumar. Did you get a chance to debug the provided code?

**Comment by PjPraveenkumar** [comment]
Hi @mukeshmrajput From the provided files, I don’t see the onmessage activity handler function that calls CompletePromptAsync. However, I tried implementing the following sample and it seems to be working fine. Could you please take a look at the sample and identify any differences?

https://github.com/microsoft/teams-ai/blob/main/dotnet/samples/04.e.twentyQuestions/GameBotHandlers.cs#L89

**Comment by corinagum** [comment]
Closing this issue since it's been a while since we got a response.
