### ISSUE TITLE
Add streaming to CONCEPTS

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#1969]

**Comment by lifan0127** [comment]
This sounds exciting. Does Teams natively support streaming?

**Comment by rajan-chari** [comment]
> This sounds exciting. Does Teams natively support streaming?

Support was added to the Teams-ai js library but not yet supported in the teams client yet.  (@lilyydu can confirm)

Here is a sample:  https://github.com/microsoft/teams-ai/pull/1965/files

**Comment by lilyydu** [comment]
Hey @lifan0127,

We are in the midst of enabling streaming on Teams, the earliest estimated public rollout will be in the next few months. It is going to take some time as changes are needed on multiple services and the client. The sample linked above will only work within our testing tenants
