### ISSUE TITLE
ActionPlanner: Combine OpenAIPlanner and AzureOpenAIPlanner classes into new ActionPlanner class

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#199]
The use of two different planners is currently causing confusion. We should follow LangChain's lead and combine the `OpenAIPlanner` and `AzureOpenAIPlanner` classes into a single `ActionPlanner` class. 

**potential issue**
This may cause some confusion for SK users as there's an `ActionPlanner` class in SK and our version of the ActionPlanner would be closser to what SK calls a `SequentialPlanner`.

**Comment by govil1811** [comment]
P0
