### ISSUE TITLE
[Bug]: Got "API isn't enabled for the bot" error when using teams chef sample

### ISSUE THREAD

**Issue by tecton** [microsoft/teams-ai#1998]
### Language

Javascript/Typescript

### Version

latest

### Description

I've got an error `{"error":{"code":"BadArgument","message":"API isn't enabled for the bot"}}` when using OpenAI streaming feature. And I cannot find the `StreamingResponse` class, are there any configuration steps that I missed?

### Reproduction Steps

```bash
1. Clone the sample "a.teamsChefBot".
2. Fill the "SECRET_OPENAI_KEY" variable in env file.
3. Fill the "OPENAI_PROJECT_KEY" variable.
4. Press F5 to start local debugging.
5. Send a message in chat window.
6. There's an error in console which shows "API isn't enabled for the bot".
```

**Comment by lilyydu** [comment]
Hey @tecton,

The streaming feature is only enabled within certain test tenants right now. We will be announcing the public preview rollout shortly. 

The StreamingResponse class is located [here](https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/StreamingResponse.ts)
