### ISSUE TITLE
AI: Add type coercion logic to the entity parsing

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#2]
Currently the entity parsing logic used by the `ResponseParser` class only ever returns strings for entities. I'd like to do some automatic type coercion to convert entities into proper primitives like int, bool, float, object, etc.

**Comment by govil1811** [comment]
If breaking change than P0 else nice to have P2

**Comment by corinagum** [comment]
ResponseParser is obsolete. Closing.
