### ISSUE TITLE
ActionPlanner: adopt SK's config methods for registering models

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#200]
SK uses the pattern of `kernel.Config.AddAzureTextCompletionService()` to configure the models that should be used. The `ActionPlanner` should adopt a similar pattern to better align with SK style prompts. So in JS you could add a model using `planner.addAzureTextCompletionService()`

**Comment by govil1811** [comment]
P0

**Comment by corinagum** [comment]
Closing since we have forked away from SK
