### ISSUE TITLE
[Bug]: Broken links across the repository 

### ISSUE THREAD

**Issue by gauravkeshre** [microsoft/teams-ai#2000]
### Language

Javascript/Typescript, C#, Python

### Version

latest

### Description

I ran a broken link check on the repo and found that there are over 50 broken links some of which  return HTTP error 404, 403.
Attaching the report file with this issue. 
[teams-ai-broken-links.txt](https://github.com/user-attachments/files/16941009/teams-ai-broken-links.txt)

### Reproduction Steps

1. install link checker `npm install -g markdown-link-check `
2. cd into teams-ai
3. run `for file in $(find . -type f -name '*.md'); do markdown-link-check "$file"; done`
4. Observe the results (attaching a simplified report)

**Comment by corinagum** [comment]
I did not know about this package, and I love it! Thank you for the heads up! Re-reviewing your PR.
