### ISSUE TITLE
[Bug]: Missing credentials error when use `azureADTokenProvider` to call Azure OpenAI

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#2001]
### Language

Javascript/Typescript

### Version

latest

### Description
I got follow error when using `azureADTokenProvider`
OpenAIError: Missing credentials. Please pass one of `apiKey` and `azureADTokenProvider`, or set the `AZURE_OPENAI_API_KEY` environment variable.

### Reproduction Steps

1. Use `azureADTokenProvider` as follow
<img width="308" alt="image" src="https://github.com/user-attachments/assets/3e6bec6e-80f2-4808-9aec-a4782b65d190">

2. Run the app

**Comment by blackchoey** [comment]
Found the root cause, this line sets the wrong parameter:
https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/models/OpenAIModel.ts#L234

**Comment by corinagum** [comment]
@blackchoey could you elaborate? Are you saying `endpoint` is incorrect?

**Comment by blackchoey** [comment]
@corinagum Let me create a PR to fix it:) Will try to submit a PR within this week.
