### ISSUE TITLE
[Bug]: File Consent Leads to NotImplemented Error and Automatic Retries

### ISSUE THREAD

**Issue by lifan0127** [microsoft/teams-ai#2004]
### Language

Python

### Version

latest

### Description

When user interacts with a file consent card, both accept and decline invoke actions result in 502 Bad Gateway with the following response, even though the corresponding file_consent_accept/decline handlers are called. Furthermore, it leads to 3 automatic retries by Teams that further disrupt the user experience.

```json
{
    "errorCode": 1008,
    "message": "<BotError>Agent returned unsuccessful status code NotImplemented",
    "standardizedError": {
        "errorCode": 1008,
        "errorSubCode": 1,
        "errorDescription": "<BotError>Agent returned unsuccessful status code NotImplemented"
    }
}
```

![image](https://github.com/user-attachments/assets/364aa7eb-5bd4-4829-bc82-8ed0c51b593c)

![image](https://github.com/user-attachments/assets/86fcf517-28ce-44df-b9fe-d783930754ea)

### Reproduction Steps

```bash
1. Ensure supportsFiles is turn on in manifest
2. Display a FileConsentCard
3. Choose "Accept" or "Decline"
4. Verify file_consent_accept/decline handler is executed
5. Monitor network activity for failed invoke request
```

**Comment by lilyydu** [comment]
Hey @lifan0127,

Did you resolve this by adding the above `send_activity` line?

**Comment by lifan0127** [comment]
Yes. Digging through the [botbuilder source code](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L467C82-L467C97), I realized that sending an invoke response is required. But it is not obvious that we have to add it in the handler. Perhaps updating the example would be helpful.

https://github.com/microsoft/teams-ai/blob/main/python/packages/ai/teams/app.py#L419

**Comment by lilyydu** [comment]
This looks like a bug on our end, we should be calling `sendActivity` in our handler wrapper- will file for this

**Comment by lifan0127** [comment]
@lilyydu Thanks for fixing it so quickly!
