### ISSUE TITLE
[Bug]: ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by sholtomaud** [microsoft/teams-ai#2029]
### Language

Javascript/Typescript

### Version

latest

### Description

npm i @microsoft/teams-ai
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: md@1.0.0
npm error Found: openai@4.28.5
npm error node_modules/openai
npm error   openai@"~4.28.4" from the root project
npm error
npm error Could not resolve dependency:
npm error peer openai@"^4.61.0" from @microsoft/teams-ai@1.4.1
npm error node_modules/@microsoft/teams-ai
npm error   @microsoft/teams-ai@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:

# npm resolution error report

While resolving: md@1.0.0
Found: openai@4.28.5
node_modules/openai
  openai@"~4.28.4" from the root project

Could not resolve dependency:
peer openai@"^4.61.0" from @microsoft/teams-ai@1.4.1
node_modules/@microsoft/teams-ai
  @microsoft/teams-ai@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

### Reproduction Steps

```bash
npm i @microsoft/teams-ai
```

**Comment by sholtomaud** [comment]
Using the VSCode MSTeams extension the above issue was generated on macos. So we are unable to start building any MSTeams apps with this library.

**Comment by Benjiiim** [comment]
Are you trying to run a sample?
If yes, have you tried to copy the samples folder outside of the project, in order to use the public version of the packages and not the code & configuration from the js/package folder?

**Comment by corinagum** [comment]
@sholtomaud by MS Teams extension, do you mean Teams Toolkit extension? Which app(s) were you trying to build?

**Comment by sholtomaud** [comment]
> @sholtomaud by MS Teams extension, do you mean Teams Toolkit extension? Which app(s) were you trying to build?

Yes "Teams Toolkit". I was just trying to follow the bouncing ball and "create a new app". 
![image](https://github.com/user-attachments/assets/00ce7365-7ad9-45b7-a705-a743877de3e0)

**Comment by sholtomaud** [comment]
> Can you try to upgrade the openai version in package.json to 4.61.0?
> 
> Are you trying to run a sample from the teams-ai repository? If yes, have you tried to copy the samples folder outside of the project, in order to use the public version of the packages and not the code & configuration from the js/packages folder?

I'm just running this out of the box. Click button, let the extension do its thing, then run ```npm i``` ... fail. Nothing special.

**Comment by sholtomaud** [comment]
I'm not going to upgrade anything because the expected behaviour is that this works out of the box.

**Comment by corinagum** [comment]
@sholtomaud when you click Create a New App, what options are you choosing? (What type of app are you setting up)?

**Comment by sholtomaud** [comment]
Can't you test for all of this? I thought MS was the guru of production releases? 

Custom CoPilot->AI Agent->TS->New Folder->SomeAppName->
![image](https://github.com/user-attachments/assets/675539ab-981a-4282-bef8-6e9a3c73601d)
->
![image](https://github.com/user-attachments/assets/3da72356-566c-4b23-816f-79ed19d9c5ea)
->
![image](https://github.com/user-attachments/assets/a943fd58-8a25-4841-8ace-e46a755df415)

**Comment by corinagum** [comment]
Thanks @therealjohn. Will add some extra info
