### ISSUE TITLE
[Bug]: The Contributing file (CONTRIBUTING.md) has broken links

### ISSUE THREAD

**Issue by cleemullins** [microsoft/teams-ai#2033]
### Language

All

### Version

latest

### Description

The file [contributing.md ](https://github.com/microsoft/teams-ai/blob/main/CONTRIBUTING.md) has two broken links in the "Legal" section. 

Consider deleting this entire section:
> Alternatively, download the agreement ([Microsoft Contribution License Agreement.docx](https://www.codeplex.com/Download?ProjectName=typescript&DownloadId=822190) or [Microsoft Contribution License Agreement.pdf](https://www.codeplex.com/Download?ProjectName=typescript&DownloadId=921298)), sign, scan, and email it back to [cla@microsoft.com](mailto:cla@microsoft.com). Be sure to include your github user name along with the agreement. Once we have received the signed CLA, we'll review the request.

The links point off to codeplex, which doesn't really exist anymore.

**Comment by corinagum** [comment]
thanks @cleemullins, long time no chat :)
