### ISSUE TITLE
[Dev support]: How to launch an azureai assistant with a vector from vector_store?

### ISSUE THREAD

**Issue by DeepReef11** [microsoft/teams-ai#2040]
## Question

I am trying to get the assistant to answer like in AzureAI on Teams. How to get the assistant with its assigned vector or choose the vector?

## What you have tried already

I've tried providing an existing assistant ID that has a vector assigned but this won't work either.  I find the documentation really hard to understand and I did not find the examples helpful, specifically those that allow choosing the data because I coulnd not find  any mention of the possibility to reference the vector store.

**Comment by SubbaReddi** [comment]
@DeepReef11 : Did you check following references:
https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/DATA-SOURCES.md#customize-a-data-source
https://github.com/microsoft/teams-ai/blob/dc821c05c5e3b00f1529485cd4021ccc631f4e19/js/samples/04.ai-apps/i.teamsChefBot-streaming/src/index.ts#L124
