### ISSUE TITLE
ActionPlanner: support OpenAI functions for plan creation 

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#205]
We should support the use of OpenAI functions for plan creation as it simplifies prompt creation for the developer and OpenAI is now tuning for better results when calling functions. The use of AlphaWave can even further improve the reliability of plans created using functions. 

The function list can be automatically created for the developer once #204 is complete.

To support the SAY command we will need to automatically add a "SAY" function on behalf of the developer, All other functions can just be converted to DO commands.

**Comment by govil1811** [comment]
P1

**Comment by aacebo** [comment]
this may no longer be necessary since models utilizing function calling are being deprecated in favor of the new tools feature.

**Comment by aacebo** [comment]
closing this since we now have an epic to track the tools feature addition
