### ISSUE TITLE
Planner: update interface to remove completePrompt() method and change generatePlan() args

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#206]
As part of moving prompt management into the planner (#202) we will need to change the `Planner` interface some. We should remove `completePrompt()` all together leaving just `generatePlan()`. And for `generatePlan()` we should remove both the `prompt` and `options` args and instead just pass a pointer to the AI system. The final interface should look like this:

```TS
export interface Planner<TState extends TurnState> {
    /**
     * Generates a plan for the AI system to execute.
     * @param context Context for the current turn of conversation.
     * @param state Application state for the current turn of conversation.
     * @param ai AI system calling the planner.
     * @returns The plan that was generated.
     */
    generatePlan(
        context: TurnContext,
        state: TState,
        ai: AI<TState>
    ): Promise<Plan>;
}
```

**Comment by govil1811** [comment]
P0

**Comment by singhk97** [comment]
how are we expecting to specify the prompt when the `generatePlan` method does not accept one as input? Are we expecting it to be preconfigured within the planner itself?
