### ISSUE TITLE
[Dev support]: Can't debug individual function calls

### ISSUE THREAD

**Issue by stokedout** [microsoft/teams-ai#2063]
Please be sure to check the Discussions Q&A section before filing a new question.

## Question

How can I debug the function calls made by this sample? If I add breakpoints to the method body of each of the `@app.ai.action("...")` nothing happens
https://github.com/microsoft/teams-ai/blob/main/python/samples/04.ai.d.chainedActions.listBot/src/bot.py#L74-L123

## What you have tried already

I've tried typing only "LightsOn" or "LightsOff" and also enabled debug over more code than just my own following this [SO post ](https://stackoverflow.com/a/60678160/978264)

> Note: please use this template to file your questions regarding implementation. Once your question is answered, our team will move this question to Q&A in Discussions for findability.

**Comment by stokedout** [comment]
To add a little more context, I want to have two prompts, one for clarifying the user question and a second for generating SQL and fetching data from a database. Perhaps you could advise if this should be tools, sequence or chain etc

**Comment by singhk97** [comment]
Can you confirm if the actions are being triggered in the first place?

Also, for best perforamnce use the `tools` augmentation. See [Function Calls](https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/FUNCTION-CALLS.md).
