### ISSUE TITLE
[Bug]: The value of citation entity field 'citation.appearance.abstract' exceeds the length limit

### ISSUE THREAD

**Issue by anishgurjar** [microsoft/teams-ai#2064]
### Language

Javascript/Typescript

### Version

latest

### Description

Hi, I have a bot that was working fine a few days ago. All of a sudden, I started getting this error:

RestError: Error while parsing citation entity with id: 1. Detailed error message: The value of citation entity field 'citation.appearance.abstract' exceeds the length limit. The maximum length is '480' characters, but the provided length is '500' characters.
 
 I thought it was just me, until I also saw a post here: https://learn.microsoft.com/en-us/answers/questions/2083250/the-value-of-citation-entity-field-citation-appear
 
 The only thing that has changed is I have been adding more documents in my blob storage, though not sure if it is related or not. 

### Reproduction Steps

1. Create a prompt that is about a paragraph long and add it in role_information in the config.json file.
2. Have about 15-20 documents in the storage over which RAG is happening.
3. Run it in teams (not test tool).

**Comment by anishgurjar** [comment]
Can I turn citations off temporarily until this is addressed? if so, how?

**Comment by corinagum** [comment]
Thanks @anishgurjar for reporting this issue. It looks like the Teams client has made a hard requirement that the abstract length not be longer than 480. I will file a bugfix shortly
