### ISSUE TITLE
[Dev support]: 06.auth.teamsSSO.bot dotnet sample does not working as previous

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#2072]
## Question
I was trying 06.auth.teamsSSO.bot dotnet sample 
[06.auth.oauth.bot](https://github.com/microsoft/teams-ai/tree/main/dotnet/samples/06.auth.oauth.bot)

It’s not working now; there is no authentication option. Can anyone confirm if this dotnet sample is functioning ?

I tried teamsSSO.bot sample too and it also not working.
[06.auth.teamsSSO.bot](https://github.com/microsoft/teams-ai/tree/main/dotnet/samples/06.auth.teamsSSO.bot)
![image](https://github.com/user-attachments/assets/49018673-9cd0-4338-baa5-fbb65fba4249)

**Comment by jemjos** [comment]
hi @asith-w, it looks like this is a known issue in Teams client and not related to Teams AI library specifically.  Please track the latest update on this [here](https://github.com/microsoft/teams-ai/issues/1934).

**Comment by corinagum** [comment]
Thanks @jemjos for linking these two issues!
@asith-w, please use the link above for tracking. Closing this issue as a duplicate
