### ISSUE TITLE
[Bug]: RE: fix: JS, PY, C# - Update citations abstract length to be max 480 chars #2067

### ISSUE THREAD

**Issue by KylerLas** [microsoft/teams-ai#2080]
### Language

Javascript/Typescript

### Version

1.5.1

### Description

Hello,

I just updated @microsoft/teams-ai from 1.3.1 to 1.5.1 as it involves the citation bug fix. This also required to update openai from 4.28.4 to ^4.61.0. 

The issue is that, with the newer versions, when we deploy our chatbot to local and dev we get the following error:

> OpenAIModel: The 'requestConfig' option is deprecated. Use 'clientOptions' instead.
> C:\Users\AA23142\Desktop\LAWA HR Chatbot\HR Chatbot\node_modules\openai\src\index.ts:417
>       throw new Errors.OpenAIError(
>             ^
> OpenAIError: Missing credentials. Please pass one of apiKey and azureADTokenProvider, or set the AZURE_OPENAI_API_KEY environment variable.

An error that we do not get when using @microsoft/teams-ai 1.3.1 and openai 4.28.4. I was able to launch and test the local chatbot by adding the AZURE_OPENAI_API_KEY variable in my .env file. I was also able to successfully deploy the dev version by adding the AZURE_OPENAI_API_KEY variable in the "Environmental variables" tab of the chatbot Web App resource in Azure.

Also there isnt a citation issue anymore but the citations themselves do not display properly or at all as seen in the image attached

![Capture](https://github.com/user-attachments/assets/6e97e4fc-6576-4bc1-87b3-a32b7ab3798e)

I do thank you all for this product, it's incredibly useful to our organization here at LAWA.

### Reproduction Steps

```bash
1. npm update openai@latest
2. npm update @microsoft/teams-a@latest
3. Deploy or local debugging
...
```

**Comment by corinagum** [comment]
@KylerLas  thanks for reporting. Were you running one of the samples?

**Comment by corinagum** [comment]
Related to: https://github.com/microsoft/teams-ai/issues/2060

**Comment by KylerLas** [comment]
> @KylerLas thanks for reporting. Were you running one of the samples?

@corinagum My team and I have been working with a chatbot that we had exported as a ZIP from the Azure OpenAI studio. All the connections worked straight out of the box that way, nothing needed to be changed.

**Comment by corinagum** [comment]
Ok that means your code is based off sample 4.h. Thank you, I am investigating this today.

**Comment by anishgurjar** [comment]
@corinagum Getting the same error when updating teams AI to the 1.5.1. Currently I have citation turned off by specifying the bot "DO NOT RETURN CITATIONS" as a workaround. However, as per this conversation https://learn.microsoft.com/en-us/answers/questions/2083250/the-value-of-citation-entity-field-citation-appear, the rep said that the issue is fixed.
It still shows [doc 1], [doc 2], etc.

**Comment by KylerLas** [comment]
Hi @corinagum any updates on connecting the citations hyperlinks to the chatbots responses?

**Comment by corinagum** [comment]
For tracking purposes, related issue: https://github.com/OfficeDev/teams-toolkit/issues/12518

**Comment by corinagum** [comment]
I have checked in the fix and will do a patch release first thing in the morning.
