### ISSUE TITLE
[Dev support]: Can we upload documents for the bot to parse?

### ISSUE THREAD

**Issue by anishgurjar** [microsoft/teams-ai#2088]
Is is possible to upload documents have the bot parse the documents like it does in chatgpt? Does a feature like that exists yet?

**Comment by jemjos** [comment]
hi @anishgurjar, you can find documentation on how to sent/receive files using bot [here](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4). And for the parsing part, it needs to be a custom implementation using AzureOpenAI, OpenAI, etc.
While we don't have an exact sample demonstrating that, [this sample](https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai-apps/c.vision-cardGazer#setting-up-the-sample) requires users to sent an image to the bot in-order to create an adaptive card.
