### ISSUE TITLE
[Dev support]: validating each chat

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#2102]
I want to validate whether a user has a 3rd party license during each chat turn with the bot.
this validation should occur even before the authentication check.

I understand that app.OnActivity() can be used for this purpose, but I’m working on a project similar to the 04.ai.a.teamsChefBot example where OnActivity() is not explicitly defined.

Is there a way to check on every turn, ensuring that only licensed users can proceed with the conversation?

**Comment by aacebo** [comment]
I think what you want is to use `app.turn('beforeTurn', ...)` https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/Application.ts#L980

**Comment by asith-w** [comment]
@aacebo  Is it ths event in dotnet sdk ? 

```
 app.OnBeforeTurn((context, turnState, _) =>
 {

     return Task.FromResult(true);
 });
```
