### ISSUE TITLE
[Bug]: LightBot Dotnet sample error

### ISSUE THREAD

**Issue by Jegadeesh-MSFT** [microsoft/teams-ai#2108]
### Language

C#

### Version

latest

### Description

We encountered the following errors while running the .NET sample of Lightbot. The errors persist and keep repeating even when I choose 'Continue' in the debugger.

![Image](https://github.com/user-attachments/assets/f4d09020-f35c-43e2-af1f-034ed74db18e)

  Message=
  Source=
  StackTrace:
  at c (https://staticsint.teams.cdn.office.net/teams-modular-packages/hashed-assets/precompiled-web-worker-inner~i-7640a2a365c05855.worker.js:1:2978927)
    at https://staticsint.teams.cdn.office.net/teams-modular-packages/hashed-assets/precompiled-web-worker-inner~b-7c46793c292c6494.worker.js:1:1106146

### Reproduction Steps

1.The issue occurs after pressing F5 or selecting the Debug option.

**Comment by singhk97** [comment]
Can you share repro steps? It looks like the debugging is breaking at Javascript code.

**Comment by Jegadeesh-MSFT** [comment]
Hi @singhk97 ,

Repro steps ,

1. open the solution file on visual studio.
2. setup dev tunnel and Provide "Prepare app dependencies" through Teams toolkit.
3. click in debug or press F5 , it will lead to the error

Please find the below video 

https://github.com/user-attachments/assets/a42ae317-5280-490b-9781-71d6f26799a4

**Comment by aacebo** [comment]
closing as the issue seems to be related to developer project debugger setup and not the SDK itself.
