### ISSUE TITLE
[Bug]: ListBot app bot is throwing error whenever a command is provided

### ISSUE THREAD

**Issue by AjayJ-MSFT** [microsoft/teams-ai#2109]
### Language

C#

### Version

latest

### Description

After installing the app and whenever a command is provided the bot is throwing error saying "Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')".
![Image](https://github.com/user-attachments/assets/dea79483-1877-40b0-b2e3-49f346ef8923)

### Reproduction Steps

1.Run the sample as per the readme 
2.Install to teams 
3.Try to provide any command to the bot

**Comment by SubbaReddi** [comment]
@AjayJ-MSFT : I tried but the issue is not reproducible for me.
Can you check with latest version in repository and let me know if issue is reproducible. Do we have any specific steps to reproduce the issue?

**Comment by AjayJ-MSFT** [comment]
@SubbaReddi : I’m following the steps outlined in the README to run the sample with the latest repository, but I’m still encountering the same issue.

**Comment by SubbaReddi** [comment]
Can you ping me in teams to validate the issue?

**Comment by AjayJ-MSFT** [comment]
@SubbaReddi : We have verified that the sample is working for us with a paid OpenAI API key.
