### ISSUE TITLE
[Bug]: C# - Could not load type 'Json.More.JsonNull' from assembly 'Json.More,

### ISSUE THREAD

**Issue by asith-w** [microsoft/teams-ai#2112]
### Language

 C#

### Version

latest

### Description

I updated to the latest Microsoft.Teams.AI 1.7.0 version (**dotnet**) and getting below error 

`The bot encountered an unhandled error: Could not load type 'Json.More.JsonNull' from assembly 'Json.More, Version=2.0.0.0, Culture=neutral, PublicKeyToken=17ed63f672b0e278'.`

what could be the reason ?

### Reproduction Steps

1.Upgrade the latest dotnet version Microsoft.Teams.AI 1.7.0

**Comment by singhk97** [comment]
Have you tried clearing the nuget cache and re-installing all the dependencies?

**Comment by asith-w** [comment]
I updated several package versions, and issue had disappeared
