### ISSUE TITLE
[C# Port] Refactor the action handling system

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#212]

**Comment by singhk97** [comment]
The current action delegate is quite rigid and has a few flaws. Look at the default actions and how the handler functions are implemented here: https://github.com/microsoft/teams-ai/blob/bfe4412b2b3a400110fc7bb5b667c0b96828df7f/dotnet/packages/Microsoft.Bot.Builder.M365/Microsoft.Bot.Builder.M365/AI/Action/DefaultActions.cs#L10-L12

The flaws are:
 1. Unused parameters - the delegate signature has a fixed set of parameters which might not be used in the handler implementation. We ideally don't want users to write functions with parameters that they won't be using. Possible solutions: 
   
     -  Supporting multiple delegate types - this is what SK does. They have at least 15 different delegate types that they support. Those delegate signatures are a combination of a 2 parameters and a few return types. It might be harder for us to do this as we support 5 parameter
     - Having a single parameter object - This is problematic as it's unclear which properties are required for an arbitrary function.
     - Dynamic delegates - It might be possible to have a dynamic delegates type. Take a look at: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/overview?view=aspnetcore-7.0.



![Image](https://github.com/microsoft/teams-ai/assets/115390646/c46dae25-a875-42ee-b00e-f4a8a9bc45bb)


The delegate type for the `MapGet` method is dynamic and dependent on the previous parameter. They might be using the reflection api to figure out the parameters and populate the delegate accordingly. 


 2. Making the `data` parameter type more explicit and not just "object" - We have it at that right now because the parameter must be able to take all kinds of types. However, we want to take advantage of the strongly-typedness of C#. Generic types will probably fix this.

**Comment by swatDong** [comment]
@singhk97 , I have another idea to use parameter attribute to support dynamic argument. This idea comes from [Azure Functions Binding](https://learn.microsoft.com/azure/azure-functions/functions-bindings-expressions-patterns) that Azure Functions support dynamic argument by different parameter attributes, such as:
<img width="456" alt="image" src="https://github.com/microsoft/teams-ai/assets/7642967/5bb60753-8381-4de1-848e-3ad86be6a316">
<img width="461" alt="image" src="https://github.com/microsoft/teams-ai/assets/7642967/f86c4ff6-6da7-46a3-bd62-06e48c58e6c6">

For example, we provide parameter attributes like `TurnContextAttribute`, `TurnStateAttribute`, `ActionDataAttribute`, `ActionNameAttribute`. Then it's up to action method to use none or one or more of those attributes.
``` csharp
    public class MyInstance
    {
        [Action("FullAction")]
        public void MyFullActionHandler(
            [TurnContext] TurnContext context,
            [TurnState(typeof(MyTurnState))] MyTurnState state,
            [ActionData(typeof(MyData))] MyData data,
            [ActionName] string actionName)
        {
            return;
        }

        [Action("PartialAction")]
        public void MyPartialActionHandler([ActionName] string actionName, [ActionData(typeof(MyData))] MyData data)
        {
            return;
        }

        [Action("DoNothing")]
        public void DoNothingActionHandler()
        {
            return;
        }
    }
```

By the way, [Generic Attributes](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/generic-attributes) is just proposed, so for now we may need to pass type to the attribute.

**Comment by singhk97** [comment]
Adding @vule-msft to the discussion.

**Comment by stephentoub** [comment]
> Supporting multiple delegate types - this is what SK does. They have at least 15 different delegate types that they support. Those delegate signatures are a combination of a 2 parameters and a few return types. It might be harder for us to do this as we support 5 parameter

It's what SK used to do.  It's no longer what it does.  It now supports any number of arguments of any relevant type.
https://github.com/microsoft/semantic-kernel/pull/1195

**Comment by swatDong** [comment]
> > Supporting multiple delegate types - this is what SK does. They have at least 15 different delegate types that they support. Those delegate signatures are a combination of a 2 parameters and a few return types. It might be harder for us to do this as we support 5 parameter
> 
> It's what SK used to do. It's no longer what it does. It now supports any number of arguments of any relevant type. [microsoft/semantic-kernel#1195](https://github.com/microsoft/semantic-kernel/pull/1195)

Thanks for this reminder. It's great to know there's such use pattern in SK.
BTW, I went through the code and noticed that it's using [*MethodInfo.Invoke(...)*](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel/SkillDefinition/SKFunction.cs#L535) to call user-defined native method.
Is there any usage or performance consideration on choosing `MethodInfo.Invoke` or `Expression.Compile`?

**Comment by stephentoub** [comment]
> Is there any usage or performance consideration on choosing MethodInfo.Invoke or Expression.Compile?

Expression.Compile is using reflection emit under the covers to generate custom IL.  It's thus much more expensive on first use, in exchange for having invocation performance be much faster.  If you're going to be executing the call a lot and the overhead of those calls matter, it can be a worthwhile tradeoff.  The difference is measured in nanoseconds, though, so you really do need to be making many, many calls to the resulting delegate for the startup costs to be worth it.

Also, recent versions of .NET optimize MethodInfo.Invoke further.  In .NET 7, the implementation can actually use reflection emit under the covers to achieve a similar optimization.  See https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#reflection for more details.

**Comment by swatDong** [comment]
> Expression.Compile is using reflection emit under the covers to generate custom IL. It's thus much more expensive on first use, in exchange for having invocation performance be much faster. If you're going to be executing the call a lot and the overhead of those calls matter, it can be a worthwhile tradeoff. The difference is measured in nanoseconds, though, so you really do need to be making many, many calls to the resulting delegate for the startup costs to be worth it.
> 
> Also, recent versions of .NET optimize MethodInfo.Invoke further. In .NET 7, the implementation can actually use reflection emit under the covers to achieve a similar optimization. See https://devblogs.microsoft.com/dotnet/performance_improvements_in_net_7/#reflection for more details.

This is really helpful. Thanks a lot!

**Comment by stephentoub** [comment]
> Is there any suggested getting-started or potential risk for providing analyzer to check attribute-binding parameter type?

There are tons of analyzers implemented in https://github.com/dotnet/roslyn-analyzers... you should be able to find some good fodder there.  The risk is simply that you're writing code that will run as part of compilation, e.g. if you have a bug and it's really slow, that will significantly slow down compile times.
