### ISSUE TITLE
[Feature Request]: Allow passing custom Bot

### ISSUE THREAD

**Issue by stepro** [microsoft/teams-ai#2130]
### Scenario

Please look at this code:

https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application/TeamsAdapter.cs#L48

It restricts the means for authentication to using the configuration-based approach only in two ways:

a) it doesn't expose an equivalent to the `CloudAdapter` constructor that accepts a custom `BotFrameworkAuthentication` instance.
b) it hardcodes usage of `ConfigurationServiceClientCredentialFactory`.

This makes it impossible to use Teams.AI when the underlying bot framework configuration is using federated credentials, which is currently pending a configuration-based implementation (see https://github.com/microsoft/botbuilder-dotnet/pull/6838).

### Solution

One or both of the following:

- The bot framework implements the configuration-based approach for federated credentials (I've suggested an extension of [this](https://github.com/microsoft/botbuilder-dotnet/pull/6838) PR [here]( https://github.com/microsoft/botbuilder-dotnet/pull/6838#issuecomment-2427413576)).
- The Teams.AI library allows passing a custom `BotFrameworkAuthentication` instance to `TeamsAdapter`.

Just the first approach will work as an immediate solution and may be the easier of the two, but the second approach seems like it should be supported in general to enable more flexibility around authentication.

### Additional Context

Thanks in advance for considering!

**Comment by singhk97** [comment]
Thanks for the feature request! The second solution seems viable to me, we'll add it to our backlog but don't have a timeline for this.

Would you like to open a PR?

**Comment by stepro** [comment]
Sure, I'll give it a shot!

**Comment by stepro** [comment]
> Sure, I'll give it a shot!

Like this: https://github.com/microsoft/teams-ai/pull/2166
