### ISSUE TITLE
[Bug]: citation.appearance.abstract exceeds the length limit in azure openai sample

### ISSUE THREAD

**Issue by adashen** [microsoft/teams-ai#2132]
### Language

Javascript/Typescript

### Version

latest

### Description

The issue is copied from https://github.com/OfficeDev/teams-toolkit/issues/12518.
 And it seems from the open AI bot sample code issue. So we raised it here
From the user:
We have created Azure Open AI Bot and published using the teams option which recommended using team tool kit and publishing the bot via teams do not provide any response.

### Reproduction Steps

To Reproduce
Steps to reproduce the behavior: (please see attached word document for reproducing the error)
[Create an Azure Bot in Azure Portal.docx]
(https://github.com/user-attachments/files/17368494/Create.an.Azure.Bot.in.Azure.Portal.docx)

**Comment by iamyashikagoyal** [comment]
![Image](https://github.com/user-attachments/assets/7ae57203-8382-4638-9f28-b5d895904239)
Tried updating the version as well, but that is also not helping, i am receiving the same error.

**Comment by corinagum** [comment]
Closing this as duplicate. I am investigating #2080 and will get a fix out as soon as possible.
