### ISSUE TITLE
[Samples JS]: Azure OpenAI Sample

### ISSUE THREAD

**Issue by cassidyRonan** [microsoft/teams-ai#214]
Request for a sample project to be added to the repo using the Azure OpenAI components rather than the OpenAI counterparts to clarify differences e.g. such as whether the defaultModel property relates to the Deployment name or the Model name, etc.

**Comment by corinagum** [comment]
Hi @cassidyRonan, 

To set up Azure OpenAI, you will implement something like the following:

```js
const planner = new AzureOpenAIPlanner({
  apiKey: process.env.apiKey,
  defaultModel: 'gpt-35-turbo', // this depends on the model you have access to/want to use
  endpoint: process.env.endpointURL // provided by AOAI
  apiVersion: '2023-03-15-preview' // also depends on your AOAI configuration
 // other settings
});
```

As far as what models you have access to and your endpoint, internally we have different models and endpoints so we aren't able to provide that here. You will need to check your Azure OpenAI subscription to verify the model and versions. Otherwise, AOAI documentation should be able to help. Please note that adding Azure OpenAI moderation within this project isn't available yet, but that code is pending for merge. :) 

I'll keep this issue open in order to track if/when we set up a sample.

**Comment by cassidyRonan** [comment]
Hi @corinagum ,

I appreciate the help, thank you very much. And it's great to hear that the AOAI moderation is on the way!

Just a clarification for the default model parameter, would that be the deployment name of the model in AOAI or the actual model name?

Additionally, does the endpoint url need / at the end? I ask as I have been getting back an axios 404 when trying to use the library and believe it is a malformed configuration of the Planner parameters on my end.

**Comment by tinsheep** [comment]
Hi @cassidyRonan thanks for all the additional info but I am still getting an Axios 404 so assuming it is not finding my Azure deployment. I implemented the AzureOpenAIPlanner and for the defaultModel I have my AOAI Deployment Name, for the apiVersion I have the Model Version.
For the endpoint, I have tried: 
- https://xxx-openai.openai.azure.com/
- https://xxx-openai.openai.azure.com/openai/
- https://xxx-openai.openai.azure.com/openai/deployments/
(not xxx obviously but my endpoint name)
Wondering if you have any additional thoughts or things I might be missing?  I also added my apiKey and did not include any moderation.  Thanks for any thoughts!

Also, can you give me a point to the AOAI documentation that helped? thanks!

**Comment by cassidyRonan** [comment]
Hi @tinsheep,

I actually solved this issue for myself earlier today. My issue was in the configuration of the prompt, so the config.json alongside the skprompt.txt had a default model parameter that had open AI's 'gpt-3.5-turbo' listed where as for AOAI, it should be your model deployment name or you can remove it altogether.

Hope this is of some help.

**Comment by tinsheep** [comment]
@cassidyRonan Thank you for the reply and link and glad it is working for you.  Also @corinagum FYI

I learned from the library code that it was putting in the /openai/deployments/ and I just needed the endpoint as stated above and the defaultModel to be my AOAI deployment name. However for me, I was still getting a bad request for all that and what i did to get it to work is remove the apiVersion altogether from my planner definition then it worked. I have a text-davinci-003 deployment but I was using the model version number of the AOAI deployment.

<img width="464" alt="image" src="https://github.com/microsoft/teams-ai/assets/8007578/db528c79-24db-4a38-ab41-9a306813cb4a">

**Comment by corinagum** [comment]
Some internal discussion: We want to support both AOAI and OAI in the samples. We will need to determine the best way to represent both options without adding too much overhead for the first-time dev.

**Comment by corinagum** [comment]
All samples for JS now include support for both OpenAI and Azure OpenAI
