### ISSUE TITLE
[Bug]: Context hasn't got Citation data

### ISSUE THREAD

**Issue by ffarukkoc** [microsoft/teams-ai#2149]
### Language

Python

### Version

latest

### Description

Hello,

I created a bot via using my documents. When I debug it (Teams on Edge), it doesn't show citations.

To understand the problem, I wrote following code and see that context is empty. As a result bot doesn't show citations on user interface (Teams).  

I have 2 questions:
-> How I can show citations on Teams? Do I set any configuration on Azure or VS Code/Bot side?
-> How I can add a breakpoint to system code (e.x teams.ai.ai.py) ? I am trying to understand citation data doesn't come from Azure site or it is deleting any part of code execution.

@bot_app.ai.action(ActionTypes.SAY_COMMAND)
async def on_say(context: ActionTurnContext[PredictedSayCommand], state: TurnState):
    msg_context = context.data.response.context
    print('Citation context: ')
    print(msg_context)

    return  ""

Thank you for your help.

### Reproduction Steps

1. Open Teams Toolkit via VS Code and Click Create New App 
2. Follow the steps below:
   2.1. Custom Engine Agent
   2.2. Chat With Your Data
   2.3. Azure AI Search
   2.4. Python
   2.5. Azure Open AI
3. Then system will create a bot
4. Enter enviroment info
5. Run indexing code
6. Debug in Teams (Edge)

**Comment by singhk97** [comment]
Take a look at this sample to see citations working with Azure OpenAI On Your Data:
1. https://github.com/microsoft/teams-ai/blob/main/python/samples/04.ai.f.dataSource.azureOpenAI/README.md
2. To see how to setup the `Activity` object to include citations, see: https://github.com/microsoft/teams-ai/blob/70a0746fc8b9b583f5930a900519f6c143cc8c3c/python/packages/ai/teams/ai/ai.py#L269-L337

Also for questions in the future please use the [Discussions](https://github.com/microsoft/teams-ai/discussions) feature.

**Comment by ffarukkoc** [comment]
Thank you Singhk, I will try it and if there is still a problem, I will write to discussions.

**Comment by ffarukkoc** [comment]
Hello, 
I tried to run the code but I couldn't succeed. It gives "[Error] - code:Core.DecryptionError, message: Cipher text is broken"error.

Alternatively, I added data source to my project as following image. 

![Image](https://github.com/user-attachments/assets/bd8f93a7-33c6-40db-9d2d-b9c08b69e826)
 
It also gave error :( 
"
The chat completion API returned an error
status of None: Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: data_sources', 'type': 'invalid_request_error', 'param': None, 'code': None}}
"
I tried to follow the code and I noticed that because of data source part it gives error. 
![Image](https://github.com/user-attachments/assets/53121538-9364-4b92-bd54-55bbf8879465)

Do you have any suggestion to solve this problem?

**Comment by ffarukkoc** [comment]
Hello,
I found the solution. Main problem is on data source definition. First of all, you have to check did your index saved as data source. You can do it from Azure AI Studio ([see example](https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line%2Cjavascript-keyless%2Ctypescript-keyless%2Cpython-new&pivots=programming-language-studio#add-your-data-using-azure-openai-studio)). Then you have to add data source part to config.json file. Whlie doing that don't forgot to delete extra information on augmentation part.
