### ISSUE TITLE
Teams AI Library - Programming languages

### ISSUE THREAD

**Issue by sayali-MSFT** [microsoft/teams-ai#2152]
### Scenario

Type of issue
Missing information

Feedback
Docs reference JavaSccript and C# as the programming languages for Teams AI Library, but samples are also available in Python.

Page URL
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview

Content source URL
https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md

Author
@michaelmaillot

Document Id
177cc18e-15ad-7c36-3604-083914c1ceea

### Solution

The Python sample is missing here-
![Image](https://github.com/user-attachments/assets/cc9ffd30-0c3f-43c2-8dca-25467b25b554)

**Comment by singhk97** [comment]
@SubbaReddi Do you know who we can redirect this to?

**Comment by lilyydu** [comment]
duplicate with #1262
