### ISSUE TITLE
[Feature Request]: Provide two new invoke handlers, (`message/fetchTask`, `message/submitAction`) for Custom Feedback Loops

### ISSUE THREAD

**Issue by jk-msft** [microsoft/teams-ai#2167]
## Overview

We currently allow Bot developers to receive feedback from Teams users using [Feedback Loops](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bot-messages-ai-generated-content?tabs=before%2Cbotmessage#add-feedback-buttons). When a user clicks "Submit" the feedback, `message/submitAction` invoke is fired. We need a new invoke handler for `message/submitAction` invoke.

We are introducing Bot developers to create **Custom** feedback loops. These custom feedback loops allow Bot developers to show either an Adaptive Card (AC) task module or a website task module. If a bot sent a message with custom feedback loop enabled to the Teams client, the Teams client will fire new invoke, `message/fetchTask` to determine whether the custom feedback loop should show an AC task module or a website task module. We need another invoke handler for `message/fetchTask` invoke.

### Default Feedback

![Image](https://github.com/user-attachments/assets/f0d1d475-b00f-4f69-b1ed-c964325a73f8)

### Custom Feedback (AC)

![Image](https://github.com/user-attachments/assets/340bc4c1-4a6a-4788-8c31-a1a685d69024)

### Custom Feedback (Website)

![Image](https://github.com/user-attachments/assets/ff8d4c68-3bff-442e-87fb-674f9dd426ac)

### Solution

Provide invoke handlers for 
- `message/submitAction`
- `message/fetchTask`

## Return Values

How I am currently handling these two invokes inside `onInvokeActivity`

### `message/submitAction`

```javascript
{
  status: 200,
  body: {}
}
```

#### Adaptive Card

```javascript
const taskModuleReturn = {  
  task: {  
    type: 'continue',  
    value: {  
      card: [Object], // Should contain valid Adaptive Card Payload 
      height: 200,  
      width: 400,  
      title: 'Test Task Module Title with AC'  
    }  
  }  
};
return {
  status: 200,
  body: taskModuleReturn
};
```

#### Website URL

```javascript
const taskModuleReturn = {  
  task: {  
    type: 'continue',  
    value: {  
      url: "https://bing.com", // Should contain valid URL with the valid domain listed under App Manifest
    }  
  }  
};
return {
  status: 200,
  body: taskModuleReturn
};
```

### Send messages with feedback loop

```javascript
    this.onMessage(async (context, next) => {
      console.log("Running with Message Activity.");
      const removedMentionText = TurnContext.removeRecipientMention(context.activity);
      const txt = removedMentionText.toLowerCase().replace(/\n|\r/g, "").trim();
      await context.sendActivity(`Echo: ${txt}`);
      await context.sendActivity({
        type: ActivityTypes.Message,
        text: "Old message with feedbackLoopEnabled = true",
        channelData: {
          feedbackLoopEnabled: true // use default feedback form
        },
      });
      await context.sendActivity({
        type: ActivityTypes.Message,
        text: "Old message with feedbackLoopEnabled = false",
        channelData: {
          feedbackLoopEnabled: false // use default feedback form
        },
      });
      await context.sendActivity({
        type: ActivityTypes.Message,
        text: "new message with feedbackLoop = default",
        channelData: {
          feedbackLoop: {
            type: "default"
          }
        },
      });
      await context.sendActivity({
        type: ActivityTypes.Message,
        text: "new message with feedbackLoop = custom",
        channelData: {
          feedbackLoop: {
            type: "custom"
          }
        },
      });
      // By calling next() you ensure that the next BotHandler is run.
      await next();
    });
```

**Comment by jk-msft** [comment]
[I created a similar ticket for bot SDK](https://github.com/microsoft/botbuilder-dotnet/issues/6865)

**Comment by aacebo** [comment]
@jk-msft  thanks for the detailed submission! We intend to start working on this in the upcoming sprint.
