### ISSUE TITLE
[Bug]: Feedback loop interface has has misnamed property...

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/teams-ai#2171]
### Language

Javascript/Typescript

### Version

1.6.0

### Description

The interface **[FeedbackLoopData](https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/Application.ts#L146-L162)** states the data coming back is in the `actionValue` property, but looks like it should be `actionType` (or the data returned is incorrect).

Not sure if the response contains the incorrect property name, or if the interface is incorrect... suspect the latter... 

```diff
  import {
    Application,
    ActionPlanner,
    DefaultConversationState,
++  FeedbackLoopData,
    Memory,
    OpenAIModel,
    PromptManager,
    TurnState
  } from "@microsoft/teams-ai";

  // ... omitted for brevity

  const app = new Application({
    storage,
    ai: {
      planner,
++    enable_feedback_loop: true,
    },
  });


  // ... omitted for brevity

++// PATCH to fix interface bug:
++// > FeedbackLoopData expects `actionValue` but data returned is in `actionType`
++export interface FeedbackLoopDataPatch extends FeedbackLoopData {
++  actionType: {
++    reaction: string;
++    feedback: string;
++  };
++}
++app.feedbackLoop(async (context: TurnContext, state: TurnState, feedbackLoopData: FeedbackLoopData) => {
++  // what do you get back normally... rut-ro... you get `actionType`, not `actionValue`
++  console.log('Feedback loop data:', feedbackLoopData);
++
++  // patch the bug with custom interface from above
++  const fbData = feedbackLoopData as FeedbackLoopDataPatch;
++  if (fbData.actionType?.reaction === 'like') {
++    console.log(`👍 ${fbData.actionType?.feedback}`);
++  } else {
++    console.log(`👎 ${fbData.actionType?.feedback}`);
++  }
++});
```

Console output from above test:

```text
Feedback loop data: {
  actionName: 'feedback',
  actionType: { reaction: 'like', feedback: 'rut ro' },
  replyToId: undefined
}
👍 rut to
```

### Reproduction Steps

1. Create simple chat bot (VSC TTK > New App > Custom Engine Agent > Basic AI Chat Bot
1. Implement feedback using the steps above.
1. Add necessary Azure AI deployment details to **./env/.env.testtool.user**
1. Run in Teams Test Test
1. Send message to get bot to respond
1. Add reaction
1. Look at console that validates what's in the description above

**Comment by corinagum** [comment]
Hi @andrewconnell, I spoke with the team working on feedback loop and they have confirmed that the data being passed is `actionValue` not `actionType`:
![Image](https://github.com/user-attachments/assets/b1393e76-f8a7-4014-8517-3fc5bb7240e0)

I'm going to close this issue, but if you could please reproduce the problem and share the data response with the repro I will re-open the issue.
