### ISSUE TITLE
[Dev support] [JS]: Oauth consent flow not working with regional bot service

### ISSUE THREAD

**Issue by Benjiiim** [microsoft/teams-ai#2186]
## Question
With Teams AI Library, how to configure OAuth auth with a multi-tenant regional bot service to make the user consent flow work?

## Code snippets
```
// Values from https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#prepare-the-bot-code and https://github.com/microsoft/botbuilder-js/issues/4418

let botFrameworkAuthConfig: ConfigurationBotFrameworkAuthenticationOptions = {
    BotOpenIdMetadata: "https://login.botframework.com/v1/.well-known/openidconfiguration",
    ValidateAuthority: true,
    OAuthApiEndpoint: "https://europe.api.botframework.com",
    OAuthUrl: "https://europe.api.botframework.com",
    ToChannelFromBotOAuthScope: "https://api.botframework.com",
    ToBotFromChannelOpenIdMetadataUrl: "https://login.botframework.com/v1/.well-known/openidconfiguration",
    ToBotFromEmulatorOpenIdMetadataUrl: "https://login.microsoftonline.com/botframework.com/v2.0/.well-known/openid-configuration",
    ToBotFromChannelTokenIssuer: "https://api.botframework.com",
    ToChannelFromBotLoginUrl: "https://login.microsoftonline.com/botframework.com",
    CallerId: "urn:botframework:azure"
  }

const adapter = new TeamsAdapter(
    botFrameworkAuthConfig,
    new ConfigurationServiceClientCredentialFactory({
        MicrosoftAppId: process.env.BOT_ID,
        MicrosoftAppPassword: process.env.BOT_PASSWORD,
        MicrosoftAppType: 'MultiTenant'
    })
);
```

## Reproduction steps

```
- From the JS b.oauth-bot sample in the 1.6.1 release.
- In the azurebot.bicep file, replace the three 'global' values by 'westeurope'
- In the index.ts file, replace the TeamsAdapter instantiation code by the code above
- Run the app in local environment (registering the app in Entra ID, deploying the regional Bot Service in Azure and running the code locally).
- In Teams, send a message to the bot
- Wait for the consent banner to appear and click on "Continue"
```

## Expected result
The consent dialog should open to allow the user to grant consent to the requested permission (User.Read)

## Result
The consent banner disappears but the consent window never appears.

## Additional notes
If admin consent has already been granted for this tenant before, the authentication flow works fine with the above config (user consent flow not needed).

Please note that the user consent flow in Teams works well when runing the sample with no modification (global configuration of the bot service bicep file and with an empty object passed in the TeamsAdapter constructor for the botFrameworkAuthConfig property).

**Comment by Nivedipa-MSFT** [comment]
@Benjiiim - Thank you for your inquiry about your Teams app development issue!  We will check and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@Benjiiim - Could you kindly share the sample link you are testing, so we can investigate it on our end?

**Comment by Benjiiim** [comment]
@Nivedipa-MSFT > [b.oauth-bot](https://github.com/microsoft/teams-ai/tree/main/js/samples/05.authentication/b.oauth-bot)

**Comment by Nivedipa-MSFT** [comment]
@Benjiiim - Thank you for your patience! We were able to reproduce the issue in the Web Teams version 1415/24110115713.. We have reported this as a bug for further investigation. 

We will keep you updated as soon as we receive further information. Thank you for bringing this to our attention!

**Comment by Benjiiim** [comment]
Hello @Nivedipa-MSFT - Have you been able to get some updates on this one? Thanks.

**Comment by SubbaReddi** [comment]
@Benjiiim :
Can you try by making following updates:

- In manifest.json, please add "europe.token.botframework.com" to valid domains

- In bot app registration -> Navigate to authentication -> Replace the existing redirect url https://token.botframework.com/.auth/web/redirect with https://europe.token.botframework.com/.auth/web/redirect

**Comment by Benjiiim** [comment]
@SubbaReddi > thanks a lot for your time and work on this one.

I was already using the Europe version of the redirect url (forgot to include that in the repro step above) but I was missing the europe.token.botframework.com domain in the validDomains property of the app manifest!
Adding that domain fixed the issue, both in the sample and in my app. 🎉

May I ask if it is safe to remove *.botframework.com now that I have added europe.token.botframework.com?
That seems to work but the sample is using a wildcard so I'm wondering if other subdomains are expected?

Thanks again!

**Comment by SubbaReddi** [comment]
@Benjiiim : I believe you can keep *.botframework.com as valid domains. As it is bot framework related domain only, it is safe to keep it.
