### ISSUE TITLE
[Bug]: [C#] Error while parsing citation Entity

### ISSUE THREAD

**Issue by FrancescoPirani-94** [microsoft/teams-ai#2234]
### Language

C#

### Version

latest

### Description

Hello! I would like to report an issue i've found in my bot:

Suddendly my bot stopped working since few days without any changes to my code side and the reason why i'ts now working is the follow exception:

"Error while parsing citation entity with id: 1. Detailed error message: The value of citation entity field 'citation.appearance.encodingFormat' is not valid. Received value is text/html"

For context, i'm using this clas AiEntity such as it's used in the official repo:

```
/// <summary>
/// The citations's AIEntity.
/// </summary>
public class AIEntity : Entity
{
    /// <summary>
    /// Required. Must be "https://schema.org/Message"
    /// </summary>
    [JsonProperty(PropertyName = "type")]
    public new string Type = "https://schema.org/Message";

    /// <summary>
    /// Required. Must be "Message".
    /// </summary>
    [JsonProperty(PropertyName = "@type")]
    public string AtType = "Message";

    /// <summary>
    /// Required. Must be "https://schema.org"
    /// </summary>
    [JsonProperty(PropertyName = "@context")]
    public string AtContext = "https://schema.org";

    /// <summary>
    /// Must be left blank. This is for Bot Framework's schema.
    /// </summary>
    [JsonProperty(PropertyName = "@id")]
    public string AtId = "";

    /// <summary>
    /// Indicate that the content was generated by AI.
    /// </summary>
    [JsonProperty(PropertyName = "additionalType")]
    public List<string> AdditionalType = new() { "AIGeneratedContent" };

    /// <summary>
    /// Optional. If the citation object is included, then the sent activity will include citations that are referenced in the activity text.
    /// </summary>
    [JsonProperty(PropertyName = "citation")]
    public List<ClientCitation> Citation { get; set; } = new();
}

```

Any clue why this is happening? It seems like the value "text/html" is no longer a valid option, but last week the bot was doing perfectly fine having the same setup.

Thank you so much

### Reproduction Steps

```bash
1. Start the bot
2. Ask any questions
3. The bot throws an exception
```

**Comment by corinagum** [comment]
@FrancescoPirani-94 Hi thanks for bringing this to our attention. I will have to make a quick update to the C# inline docs. 
After doing some hunting around, I confirmed with the service team for Teams that the new only allowable value for `citation.appearance.encodingFormat` is `application/vnd.microsoft.card.adaptive`. It applies to `citation.appearance.text` which must be an adaptive card.

This change is for now; in the future other types may be supported. 

These changes are intended for custom copilots so data like charts can be displayed. 

For now, please see the [JS inline documentation](https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/types/ClientCitation.ts) for updated information.

**Comment by johnborges** [comment]
@FrancescoPirani-94 Do you have an example of how you're sending an Activity using `AIEntity`?
