### ISSUE TITLE
[Bug]: listBot sample not building / working with Teams Toolkit

### ISSUE THREAD

**Issue by davrous** [microsoft/teams-ai#225]
**Describe the bug**
I've followed the steps described in the readme: https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.d.chainedActions.listBot to try the listBot sample using the Teams Toolkit v5. But when pressing F5 to run the solution, I've got an error during the "npm install" command execution:

![image](https://github.com/microsoft/teams-ai/assets/933018/63df8e69-e96e-44b6-a2c2-26b1b2cab546)

**To Reproduce**

> Steps to reproduce the behavior:

1. Open the listBot sample in VS Code
2. Press F5
3. See error

Solution suggested: we need to modify the sample (and probably all other Teams AI Samples) to use the same approach as the Teams Chef AI Bot from the Team Toolkit sample gallery: https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/teams-chef-bot which is:

- call "yarn start" instead of "npm install" in the deploy YAML part
- register the OpenAIKey environment variable in the YAML part too

**Desktop(s) (please complete the following information):**

- OS: Windows 11 21H2
- Browser: Edge
- Version: 114
- Node: 16.18.1

**Comment by corinagum** [comment]
I am partially investigating this with #180. Once we get that one fixed let's investigate further if listBot in particular still isn't working. (David not to be repetitive -- I'm just leaving notes for all 😆 )

**Comment by corinagum** [comment]
Fixed by @aacebo in #259
