### ISSUE TITLE
[Bug]: Cannot build sample projects

### ISSUE THREAD

**Issue by ryriddle** [microsoft/teams-ai#241]
**Describe the bug**

> I cannot build the sample projects. ```yarn build``` fails. I was able to work through the first failure by removing yarn.lock from the devOpsBot and the teamsChefBot samples. After that ```yarn build``` fails with this (dependency?) error.

PS C:\src\teams-ai\js> yarn build
devOps-demo
 | src/index.ts(165,5): error TS2345: Argument of type '(context: TurnContext, state: ApplicationTurnState, data: EntityData, action?: string) => Promise<false>' is not assignable to parameter of type '(context: TurnContext, state: ApplicationTurnState, entities: EntityData, action?: string | undefined) => Promise<boolean>'.
 |   Types of parameters 'context' and 'context' are incompatible.
 |     Type 'import("C:/src/teams-ai/js/node_modules/botbuilder-core/lib/turnContext").TurnContext' is not assignable to type 'import("C:/src/teams-ai/js/samples/04.ai.e.chainedActions.devOpsBot/node_modules/botbuilder-core/lib/turnContext").TurnContext'.
 |       Types have separate declarations of a private property '_adapter'.
 | src/index.ts(176,23): error TS2345: Argument of type 'import("C:/src/teams-ai/js/samples/04.ai.e.chainedActions.devOpsBot/node_modules/botbuilder-core/lib/turnContext").TurnContext' is not assignable to parameter of type 'import("C:/src/teams-ai/js/node_modules/botbuilder-core/lib/turnContext").TurnContext'.
 |   Types have separate declarations of a private property '_adapter'.
 | `yarn build` failed with exit code 1
Stopping 11 active children
Aborted execution due to previous error

**To Reproduce**

> Steps to reproduce the behavior:

1.In the root JavaScript folder, install and build all dependencies

    ```bash
    cd teams-ai/js
    yarn install
    yarn build

**Expected behavior**

> I expect to be able to build and run the samples.

**Comment by corinagum** [comment]
Hi @ryriddle, thank you for your patience. It turns out that `botbuilder` was not the same version across projects; particularly `teamsChefBot`. 🤦🏻‍♀️ We are working to get a PR merged in today, but if you are in a rush or have a few minutes, could you bump `botbuilder` to 4.19.3 and let us know how that goes? 

If not, again we hope to have the merge in asap.  We still have some more validating to do across samples.

**Comment by ryriddle** [comment]
Thanks, this issue is fixed. But now I am facing this issue in node v16 and v18. https://github.com/microsoft/teams-ai/issues/180
