### ISSUE TITLE
Documentation: Lunch & Learn / other questions

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#290]
Presentation TBD by Corina and Kavin. See #73 for a little more context

-----
Other questions:

- [x] Update [AI memory](https://github.com/microsoft/teams-ai/blob/main/getting-started/02.API-REFERENCE.md#ai-memory-history)
- [ ] What is the magic behind mapping my meta prompt / prompt with the action? How is the code being called from prompts?
- [ ] How to validate that code is mapped correctly (to prompts)?
- [ ] When is `SAY` value returned in the `sendActivity` flow?
- [ ] (Token count exceeded exception)What would be your advise to have the text generated by the AI at the beginning, followed by the text I'd like to return from my API calls?
    - Need to clarify this question
- [ ] Pros/Cons of OpenAI v.s. Azure OpenAI
- [ ] Document 'Harness the power of AI: Extend Copilot and beyond'

**Comment by govil1811** [comment]
P2

**Comment by singhk97** [comment]
@corinagum i like the idea of a lunch & learn - we can organize this elsewhere?

**Comment by singhk97** [comment]
@corinagum We have a recurring meeting for learning. Do we want to close this ticket?

**Comment by corinagum** [comment]
I'm pretty sure Tatiana still wants us to do a presentation, so I'm leaning towards no. thoughts?

**Comment by lilyydu** [comment]
Completed via office hours given to BEACON team on 4/12
