### ISSUE TITLE
[PY] Engineering System

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#298]

**Comment by blackchoey** [comment]
@aacebo I'm not working on this, will unassign myself and move the status back to triaged

**Comment by aacebo** [comment]
@blackchoey are you still working on this?

**Comment by blackchoey** [comment]
@aacebo Thanks for following up. I'm not working on this. This issue was created at the beginning to share, discuss and track what should be done for Python. Feel free to rearrange the issues I created.
