### ISSUE TITLE
[PY] Twenty Questions

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#316]
https://github.com/microsoft/teams-ai/tree/main/js/samples/03.ai-concepts/a.twentyQuestions

**Comment by aacebo** [comment]
@Stevenic

**Comment by BMS-geodev** [comment]
test comment

**Comment by BMS-geodev** [comment]
I have the VScode Teams toolkit running with proper permissions. 

Last night I ran the PY echobot, and the JS twenty questions.

**Comment by BMS-geodev** [comment]
I'm reviewing the code in two parts,

The logic related to twenty questions in the JS example

The framework requirements for a bot, as seen in the PY echobot.

I hope with those two I can make a first pass on the objective today...with a reasonable attempt at approved style and format, and deployment ephemera
