### ISSUE TITLE
[PY] Teams Toolkit integration

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#324]
The purpose is to create a sample project that works with VS Code Teams Toolkit, as a starting point to build other Python sample projects.

**Comment by blackchoey** [comment]
> The sample is now available at https://github.com/frankqianms/bot-conversation-py

The sample is updated to enable 1-click F5 experience. We're still discussing what's the recommended practice for pro python developers.

**Comment by aacebo** [comment]
@blackchoey whats the status of this?

**Comment by blackchoey** [comment]
@aacebo We now has a sample project based with the recommended Python dev experience from Python team. I think we can close this one.
The next step is adding a Python template to Teams Toolkit, as well as updating the Python samples in this repo. Will create new issues to track.
