### ISSUE TITLE
(Blocked: status is watching) [Bug][Sample - 04.ai.b.messageExtensions.gptME]: PREVIEW_MODE only works in Team channel

### ISSUE THREAD

**Issue by swatDong** [microsoft/teams-ai#328]
**Describe the bug**

When running gptME sample with [`PREVIEW_MODE`](https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.b.messageExtensions.gptME/src/index.ts#L82) enabled, the final "*Send*" action only works in Team channel, but does not work in Personal chat or Group chat.

**To Reproduce**

1. Clone repo and go to sample *js/samples/04.ai.b.messageExtensions.gptME*
2. Set OpenAI key. Set [`PREVIEW_MODE`](https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.b.messageExtensions.gptME/src/index.ts#L82) to `true`
3. Run the sample
4. Try the ME in Teams channel. It works
5. Try the ME in Personal chat or Group chat. It fails with "***Unable to reach app. Please try again.***"

**Expected behavior**

I'm not sure if it's a Teams limitation or any error in manifest. Should `botMessagePreview` work for all chats?

**Screenshots**
<img width="561" alt="image" src="https://github.com/microsoft/teams-ai/assets/7642967/9757b34a-de3e-42b7-87e1-28ca50dc6c80">
<img width="557" alt="image" src="https://github.com/microsoft/teams-ai/assets/7642967/ef076f3c-c9fe-4afb-8e70-d815f1512469">

In addition, from the browser dev tool (F12), there's no outgoing request or console error after clicking "*Send*".

**Comment by sunshineo** [comment]
I just ran into this identical problem. Working in channel, but does not work in personal or group chat, no network request sent and no console log at all.
And BTW I'm not even using the gptME sample. I'm using my own app
Also in this ticket https://github.com/microsoft/teams-ai/issues/21 , @Stevenic thinks it's a manifest issue

**Comment by sunshineo** [comment]
On the doc about bot response with adaptive card [here](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit?tabs=javascript%2Cdotnet-1), it says:

> The prerequisite to get the bot response with an Adaptive card is that you must add the bot object to your app manifest, and define the required scope for the bot. Use the same ID as your message extension for your bot.
I'm 100% sure I have the same id and all 3 scopes `personal, groupchat, team`. I also played with it and removed team scope, and it continues to work in the channel, and continues to not work in personal or group chat. I think it's petty clear that this is some bug internal to Teams.

<img width="857" alt="image" src="https://github.com/microsoft/teams-ai/assets/1072766/317c31e9-12bf-4d09-995c-3693c1294af4">

**Comment by swatDong** [comment]
Tried to re-create a bot and re-install the app in Teams, and now the preview message works in personal & group chat.
Noticed a difference - there's a system message before the preview message is sent. Maybe Teams side fixes this.
<img width="222" alt="image" src="https://github.com/microsoft/teams-ai/assets/7642967/7616a046-f23c-4b0a-9bb3-d97c777fb5a0">

@sunshineo - does `botMessagePreview` work for you now?

**Comment by sunshineo** [comment]
Hi @swatDong , it is when debug locally, it does not work in chat and works in post. If install the app, then it works

**Comment by swatDong** [comment]
> Hi @swatDong , it is when debug locally, it does not work in chat and works in post. If install the app, then it works

Are you using VSCode to debug locally? I also met that but fixed by clearing browser's user data profile. E.g., in *.vscode/launch.json*, set `userDataDir` to the launch browser config:
```json
        {
            "name": "Launch App in Teams (Chrome)",
            "type": "chrome",
            "request": "launch",
            "url": "https://teams.microsoft.com/l/app/...",
            ...
            // add userDataDir setting here
            "userDataDir": "${workspaceFolder}/my-temp-folder"
        },
```

VSC uses a fixed temp profile folder for each workspace. Setting `userDataDir` means to use a new empty profile so the launched Teams client can be latest.

**Comment by sunshineo** [comment]
Tested. This line does not help. I have a support ticket with MSFT. The ticket number is 3229870. I got the following reply 

Hi ,

  We have verified that the issue occurs (in the sample app) only when it runs locally, but this is working fine in all scopes when it deploys from the Teams admin center. Could you please confirm whether you are facing the same problem locally?

 After I confirmed it's only locally, the ticket was closed

Regards,

**Comment by swatDong** [comment]
`The launched Teams client` I mentioned is the Teams Web Client (i.e., the Teams opened in browser).
Just checked my client version. I enabled [M365 targeted release](https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites#enroll-your-developer-tenant-for-microsoft-365-targeted-releases-optional) - maybe that let me to get some early updates/fixes.

**Comment by corinagum** [comment]
Problem has been resolved and has started roll-out. We will announce here when the changes are publicly available.

**Comment by swatDong** [comment]
Tried that preview message work on both standard release and targeted release.
@sunshineo - does `botMessagePreview` work on your side now?

**Comment by sunshineo** [comment]
No
@corinagum or @swatDong , what update do I need to do to our project? Or do we just need to wait?

**Comment by swatDong** [comment]
> No @corinagum or @swatDong , what update do I need to do to our project? Or do we just need to wait?

Could you please try to create a new bot and test?
In addition, there's a known unsupported scenario - preview message in the bot's own chat. So please test in another user chat or group chat.

**Comment by corinagum** [comment]
Closing as resolved.
