### ISSUE TITLE
[Bug][C# typeAheadBot sample]: selecting item from dynamic choice set shows error

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/teams-ai#333]
After selecting an item from the dynamic choice set, Adaptive Card shows below error, and the "Submit" button does not work.

![image](https://github.com/microsoft/teams-ai/assets/37978464/14a3b565-aab4-48c2-a905-d1b092520375)

There is no useful information in F12 and it seems that the selection action is a pure-frontend operation.

The same error happens in the [typeahead search sample in Microsoft-Teams-Samples](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-type-ahead-search-adaptive-cards/csharp). Also reported an issue in that repo: https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/868.

The typeAheadBot js sample works well.

**Comment by corinagum** [comment]
Closing as resolved
