### ISSUE TITLE
[Bug]: 04.AI.C.ACTIONMAPPING.LIGHTBOT throwing dependency error while debugging

### ISSUE THREAD

**Issue by aratigurav** [microsoft/teams-ai#368]
Not able to run/debug the sample LightBot app, it shows dependency issues.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to (https://github.com/microsoft/teams-ai/tree/main/js/samples/04.ai.c.actionMapping.lightBot)
2. Cloned the repo locally.
3. Followed the readme instructions to yarn install and build
4. While debug/run it throws below error
5. [script.ScriptExecutionError]: Script ('npm install --no-audit') execution error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: typedoc@0.19.2
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.0.5" from the root project
npm ERR!   peer typescript@">=2.7" from ts-node@9.1.1
npm ERR!   node_modules/ts-node
npm ERR!     dev ts-node@"^9.0.0" from the root project
npm ERR!   25 more (tslint, tsutils, tsutils, @standardlabs/downlevel-dts, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@"3.9.x || 4.0.x" from typedoc@0.19.2
npm ERR! node_modules/typedoc
npm ERR!   dev typedoc@"^0.19.2" from the root project
npm ERR!   peer typedoc@">=0.7.0 <0.20.0" from typedoc-plugin-external-module-name@4.0.6
npm ERR!   node_modules/typedoc-plugin-external-module-name
npm ERR!     dev typedoc-plugin-external-module-name@"^4.0.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.0.8
npm ERR! node_modules/typescript
npm ERR!   peer typescript@"3.9.x || 4.0.x" from typedoc@0.19.2
npm ERR!   node_modules/typedoc
npm ERR!     dev typedoc@"^0.19.2" from the root project
npm ERR!     peer typedoc@">=0.7.0 <0.20.0" from typedoc-plugin-external-module-name@4.0.6
npm ERR!     node_modules/typedoc-plugin-external-module-name
npm ERR!       dev typedoc-plugin-external-module-name@"^4.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:

**Expected behavior**

The sample should run without an error.

**Desktop(s) (please complete the following information):**

- OS: Windows 11
- Browser Edge
- Version: node version V16.14.1 or V18 on both it does not work.

**Comment by corinagum** [comment]
@aratigurav when you say you did yarn and build, did you do it in the `js` directory or sample? It should be done in `js`. This is done so users have access to the latest bits from the teams-ai package.

**Comment by aratigurav** [comment]
Yes @corinagum i tried installing using yarn at the js directory. I even tried deleting the node modules. Still same issue.
