### ISSUE TITLE
[Bug]: use model from planner options or prompt config

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/teams-ai#377]
In JS SDK, it uses the model from prompt config. And if no model defined in prompt config, it uses the model from planner options.
However, in .NET SDK, it always uses the model from prompt config.

The reason is that .NET SDK creates semantic kernel instance and configures AI services with the planner options directly. https://github.com/microsoft/teams-ai/blob/889d249f72e235713a6bafaee1bcc26408c67098/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Planner/OpenAIPlanner.cs#L39-L41

**Comment by corinagum** [comment]
is this a dotnet bug? could you either add `js` or `dotnet` tag please? :) And we should discuss at next scrum.

**Comment by kuojianlu** [comment]
Yes, just for `dotnet`. Added `dotnet` tag.

**Comment by corinagum** [comment]
Hi, since Steve's upcoming changes will no longer be using SK config, this bug can be closed as no op :)
