### ISSUE TITLE
[C# Refactor] Replace Newtonsoft JSON with System.Text.Json in code base

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#406]

**Comment by singhk97** [comment]
As part of this, make the custom json convertor classes internal

**Comment by singhk97** [comment]
Note: The activity handler methods still use Newtonsoft.Json library as the Botframework SDK classes, such as TeamsChannelAccount are implemented to work only with Newtonsoft.Json. When we unify these packages we should look into moving over to System.Text.Json then.
