### ISSUE TITLE
Update tokenizer library in ConversationHistory class

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#436]
@corinagum While exploring tokenizer options for Python, I found the tokenizer used in JS SDK (gpt-3-encoder) does not support `cl100k-base` encodings used by `gpt-4` and `gpt-3.5-turbo`. We should use a tokenizer that supports `cl100k-base` encoding to get more accurate result. https://www.npmjs.com/package/@dqbd/tiktoken could be an alternative per my research.

@singhk97 I didn't get enough time to confirm whether C# SDK has same issue, as the tokenizer comes from Semantic Kernel. You may also take a look and switch to a proper tokenizer if needed.

Reference material, which contains available libraries for each encoding: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by corinagum** [comment]
@blackchoey thanks for filing this issue. Next time, could you add appropriate labels as well?

**Comment by aacebo** [comment]
no longer needed as we don't have a `ConversationHistory` class anymore.
