### ISSUE TITLE
[Feature Request]: Better support for custom planner and client extensibility

### ISSUE THREAD

**Issue by pkbullock** [microsoft/teams-ai#442]
At the moment, you can extend the OpenAIPlanner and AzureOpenAIClient objects allow custom implementations, please keep that!! By using those I have managed to work around issue #401 and include the necessary calls to support "Bring your own data".

Instead my request is to improve and open up some of the private methods to allow to be overridden to adjust the behavior of the within derived classes with the option use some of the underlying code of the library. This would make the library more flexible to changes in the service as this evolves. 

**Describe your user scenario**

I am looking to bring my own data into Teams AI toolkit, I created a custom classes to get this to work. The user scenario is to specific Azure Cognitive Search in the data sources to get more grounded results. 

**Describe the solution you'd like**

I'd like to improve the extensibility I had to recreate a lot of code to get this to work because methods are private, ideally if they are either overridable or callable by derived classes this would remove need to duplicate code.

**Describe alternatives you've considered**

- I have considered not using the Teams AI SDK, but this would involve more work in the long run, I like this library.
- Azure Open AI does not do this at a service level (which would be great if it could) to have deployments that included this grounded data source, reducing the level of coding required.

**Additional context**

I am using the JavaScript/Typescript libraries.

**Comment by julbrs** [comment]
Hi @pkbullock,

> I created a custom classes to get this to work

I understand that you have something that is working to search your own data inside Teams AI. I would love to get a look and see how it's done. Is it possible?

And I would like also to get access to "my own data" directly in Teams AI. Seems it's not possible as of today,

Thanks!

**Comment by aacebo** [comment]
since this was posted our planners have been re-implemented. I'm curious if this is still relevant?

**Comment by igrgurina** [comment]
> since this was posted our planners have been re-implemented. I'm curious if this is still relevant?

is it now possible to use Azure AI Search index as a data source for planner or prompt?

**Comment by aacebo** [comment]
Yes with our introduction of `DataSources` you can now add custom sources of data in a modular way.

Here is an example in our chefbot sample, https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.a.teamsChefBot/src/VectraDataSource.ts#L53, you just need to create a class that implements the interface `DataSource`, then you can add our custom datasource to the planner like so https://github.com/microsoft/teams-ai/blob/main/js/samples/04.ai.a.teamsChefBot/src/index.ts#L118. 

In the sample we are using a local vector package called `vectra`, but you can substitute in any source of data you want to use.

**Comment by igrgurina** [comment]
Do you maybe know if this will also work with the .NET version of the library? Is there feature parity?

**Comment by aacebo** [comment]
@igrgurina yes C# has this functionality and is at parity. We are working on updating the C# chefbot sample with this new datasource functionality but for now please use the js chefbot sample as a reference. The syntax should be near identical.

Closing this for now but please submit a bug if you have any issues.
