### ISSUE TITLE
Remove moderator interface and use decorators to register moderator interface

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#446]
@aacebo Please add more details here, e.g. why we want to make this change.

**Comment by aacebo** [comment]
We want to explore making this change to explore a new pattern of overriding default functionalities in the SDK. Right now in the other libraries you are expected to override a base class such as `Moderator` and pass it in as an argument to the SDK if you want to implement your own moderation logic.

I propose that a simpler and more _pythonic_ way of doing this is by exposing `decorators` that allow the user to register their own handlers, for example in the linked by they would be `@app.ai.review_prompt` and `@app.ai.review_plan`. This would:

1. be more python friendly syntax
2. not require the developer to import/declare another class
3. be a pure functional implementation, making the code lighter and easier to test.
