### ISSUE TITLE
Telemetry Headers

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#454]
We need to add telemetry for tracking AI Library usage:

Users actively building using AI library - Test vs production
What are bot feature APIs they are using
MAU of app built via SDK

[code](https://github.com/microsoft/teams-ai/blob/stevenic/unification/js/packages/teams-connector/src/auth/connectorFactoryImpl.ts#L12)

Make sure SMBA is logging correctly
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/issues/598
- [ ] https://github.com/microsoft/teams-ai/issues/745
```

**Comment by corinagum** [comment]
Requests made to botbuilder team:

https://github.com/microsoft/botbuilder-js/issues/4552
https://github.com/microsoft/botbuilder-dotnet/issues/6701
https://github.com/microsoft/botbuilder-python/issues/2033

**Comment by aacebo** [comment]
currently following up with SMBA on our side to make sure they can ingest custom headers we set. BF team should be able to start this work in the JS SDK early next year.
