### ISSUE TITLE
Consolidate AzureOpenAIPlanner and OpenAIPlanner into one class

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#468]
Opening this issue to have asynchronous discussion on consolidating these two classes into one.

**Comment by singhk97** [comment]
@Stevenic @corinagum mentioned that you want to consolidate these two classes. Will this be a part of the ActionPlanner class? What do you envision for this?

**Comment by corinagum** [comment]
FYI @blackchoey

**Comment by aacebo** [comment]
closing because since our recent refactor this is no longer relevant.
