### ISSUE TITLE
Python Adaptive Cards

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#471]
expose the ability for developers using the SDK to create views using `AdaptiveCards`.

Note: the project https://github.com/microsoft/AdaptiveCards has implementations in `NodeJS` and `Dotnet` but not `Python` so we will probably have to write an internal implementation.

**Comment by blackchoey** [comment]
Python botbuilder provides `CardFactory` so we don't need to implement ourselves. This feature focus on adding decorators for Adaptive Card related events and can be closed with related PR merged.
