### ISSUE TITLE
General: typing "state.conversation.value.field" is too long. Remove the ".value"

### ISSUE THREAD

**Issue by Stevenic** [microsoft/teams-ai#49]
Currently it feels pretty cumbersome to have to type `state.conversation.value.field` all the time. The `.value` seems like an unneeded step. It's there because there are a series of management operations. I'd like to try flipping the relationship such that management functions are nested under a `.__manage` property that hangs off the scope. That would mean that developers can use `state.conversation.field` to access their state properties and `state.conversation.__manage.delete()` to delete the current state.

**Comment by govil1811** [comment]
P0

**Comment by corinagum** [comment]
Finished with #667
