### ISSUE TITLE
[Bug]: C# - AI.CompletePromptAsync does not resolve {{$history}} in prompt

### ISSUE THREAD

**Issue by swatDong** [microsoft/teams-ai#490]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

When calling `AI.CompletePromptAsync` to get a plain text response, the variable `{{$history}}` in prompt is not resolved.
To be compared, calling `AI.ChainAsync` resolves `{{$history}}` correctly.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to [Chef Bot Sample](https://github.com/microsoft/teams-ai/tree/main/dotnet/samples/04.ai.a.teamsChefBot)
2. Change `AI.ChainAsync` to `AI.CompletePromptAsync` in *TeamsChefBotApplication.cs*.
3. Follow readme to run it on Teams

**Expected behavior**

Each AI call should include correct history data.

**Comment by swatDong** [comment]
@singhk97 - this is due to [`_SetTempStateValues`](https://github.com/microsoft/teams-ai/blob/main/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/AI.cs#L418) is only called by `ChainAsync`.

Is that as designed or a missing calling bug?

**Comment by singhk97** [comment]
This is a bug, please feel free to add `_SetTempStateValues` to `CompletePromptAsync` method.

**Comment by swatDong** [comment]
Sure, will do.
