### ISSUE TITLE
[Feature Request]: SDK reference in the documentation

### ISSUE THREAD

**Issue by aycabas** [microsoft/teams-ai#493]
It's a very common practice to have a reference page for Microsoft SDKs in the documentation. It helps developers to understand more about the capabilities of the SDK and the reference page acts as the dictionary of the SDK.

One of the examples of a reference pages: https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teams-js/?view=msteams-client-js-latest

Even though SDK itself provides all the examples of the functions and classes, it's sometimes not clear to the developer the "purpose" of the function rather than "how-to" step. Reference page for the Teams AI library can help developers deep dive in the SDK capabilities and be the central point for any time when PG needs to share a reference.

**Comment by singhk97** [comment]
Thanks for opening this issue. We'll probably get to this in the near future.

**Comment by singhk97** [comment]
The technical docs should be available as soon as we GA. Will close the issue then.

**Comment by aacebo** [comment]
this should now be available, closing
