### ISSUE TITLE
[Feature Request]: Support in-app SSO implementation in addition to OAuth Connection based SSO implementation

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#494]
*Hard to figure out a suitable name for this feature. Refer below terminology as well as other part to better understand the feature. We can discuss for a better name.*

# Terminology:
* OAuth Connection based SSO implementation: all the steps (login start page, token exchange) of SSO as well as token cache are managed in the cloud (via Azure Bot Service's OAuth Connection). This is how `OAuthPrompt` works.
* In-app SSO implementation: all the steps of SSO are implemented in the Teams app's source code. Including login start page, token exchange logic and optionally token cache. This is how `TeamsBotSsoPrompt` works in `@microsoft/TeamsFx` package.

# Why:
For some user scenarios, developers need more flexibility when adopting Teams SSO. For example, developer may need to user a cert instead of client secret when exchange tokens during SSO. In this case, developer cannot rely on OAuth Connection in Azure Bot Service because it only supports client secret. So, we also need a more flexible way to better support developers.

In the meanwhile, having multiple Teams related packages could confuse developers. So it would be great if we can unify into one package.

# Pros & Cons for the 2 approaches:
|   | In-app SSO implementation | OAuth Connection based SSO implementation |
| --- | --- | --- |
| Pros | * Gives user more control on each SSO stage <br> * Do not require an Azure subscription during development <br> * No need to touch Azure resources when updating authentication options | * User can write less code to enable SSO <br> * Cache the access token by default |
| Cons | * User needs to write more code when enabling SSO | * Requires an Azure subscription during development <br> * Not suitable for some user scenarios like using cert during token exchange  |

**Comment by garrytrinder** [comment]
Our documentation focuses on the OAuth Connection approach, heading down the In-app would potentially leave developers in the dark with little to no documentation to assist them should they hit any issues.

For example, if you go searching for how to add SSO to a bot or message extension, it is highly probable that you will hit upon these resources which focus on the OAuth connection approach.

[TUTORIAL] Build a bot with SSO authentication: https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso
[DOCS]: Enable SSO for your app https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-overview
[SAMPLE]: bot-conversation-sso-quickstart https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart

Another thing to add is that using the In app approach uses the old Bot Framework portal, whilst this has an advantage of not requiring an Azure subscription to use it, it is an old approach and you would never use this in production, so feels counter-intuitive (personal opinion).

/cc @tacri (@Stevenic mentioned that you were looking into auth)

**Comment by blackchoey** [comment]
@garrytrinder thanks for your great feedback. I want to clarify that the in-app approach also works with the Azure Bot Service. It just does not require an OAuth Connection so the old Bot Framework portal also works with it.

Document is indeed important. I think we need new documents for Teams-AI library as the programming experience is different than botframework. The in-app approach will also be included in the new documents if we have it.

**Comment by garrytrinder** [comment]
Thanks for the update @blackchoey.

There is an ongoing discussion around changes to the Authentication class, https://github.com/microsoft/teams-ai/discussions/671, where does this fit in with those discussions?

How would a developer authenticate with and call another API? Let's say for example the bot needs to send requests to Microsoft Graph and a custom API secured with AAD, bot using delegate authentication, how would the developer get an access token for each API?

Would this also apply to message extensions?

**Comment by blackchoey** [comment]
Hi @garrytrinder , short answer to your questions is: the improvement fits the discussions in #671. So as long as #671 works for your scenarios, the improvement works. The goal in this design is to not impact how to write authentication code using Teams-AI library. I think your scenarios are valid. We need more discussions there to ensure they're supported.

To share more technical background:
The Teams SSO flow involves a token exchange step, which means the Teams app need to exchange the SSO token for desired access token (e.g. MS Graph token, token for custom API secured with AAD) using AAD OBO flow. The in-app SSO implementation improvement aims to give developers more control over this step, like using a client secret or client certificate (which is a recommended practice) during token exchange, whether to cache the token to a persistent store, etc. So, it's a supplement to #671, not a replacement to it.

**Comment by blackchoey** [comment]
This will be implemented in the library and now tracks with #788
