### ISSUE TITLE
[Bug]: Typing indicator is sent to user even if bot reply

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#496]
**Describe the bug**

The bot sends a typing indicator to user on every turn. The bot does not send something back to the user, leaving them confused as to why there was a typing indicator in the first place. 

Scenario: 

The activity is routed to the AI module, and the generated plan does not have a 'SAY' command. Unless something is explicitly configured in the `afterTurn` activity handler, the user will not receive a message.

**To Reproduce**

> Steps to reproduce the behavior:

Try the list bot sample and ask it to create a list. If you observe the terminal, you will see that a plan is generated to create a list, but it will not have a SAY command to communicate that action to the user.

**Expected behavior**

> Provide a clear and concise description of what you expected to happen.

In general, if there's a typing indicator, the bot should reply.

**Possible Solution**

> If applicable, add screenshots to help explain your problem.

In the after turn method, if the bot has not responded (see "turnContext.responded" property), have the bot send something like "Okay" or "Got it."

**Comment by singhk97** [comment]
This could be an issue on the Teams side - needs further investigation.

**Comment by aacebo** [comment]
unable to verify
