### ISSUE TITLE
Add decorator to register handlers for Teams AI events

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#498]
Need to be able to override following default implementations with custom handlers:
_on_unknown_action
_on_flagged_input
_on_flagged_output
_on_rate_limited
_on_plan_ready

Feel free to call out if anything is missing or anything is included in the scope incorrectly.

**Comment by aacebo** [comment]
@blackchoey this can currently be done via the `action` decorator like this:

```python
app.ai.action("___UnknownAction___", allow_overrides=True)
async def on_unknown_action(context: TurnContext, state: TurnState, data, name) -> bool:
    return True
```

The JS SDK doesn't have different decorators for each action it just does it like this, can this ticket be closed?

**Comment by blackchoey** [comment]
Just realized that. I'm find with it. Do you think we need to expose the magic strings (`___UnknownAction___`, etc.) in some way? If yes, we can either track it in this issue or create a new issue and close this one.

**Comment by blackchoey** [comment]
https://github.com/microsoft/teams-ai/blob/PYTHON/python/packages/ai/teams/ai/actions/action_types.py is exported for developers. Closing this issue.
