### ISSUE TITLE
Update sample and default LLM to AOAI

### ISSUE THREAD

**Issue by govil1811** [microsoft/teams-ai#503]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe your user scenario**
Update all samples to use AOAI. 

> Provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
EPM/CPM have bundling AOAI + Teams AI Library and is landing well with customers. Samples help them onboard customers better and faster

**Describe the solution you'd like**
AOAI as the default LLM model in samples. 

> Provide a clear and concise description of what you want to happen, with code snippets or pseudo code as applicable.

**Describe alternatives you've considered**

> Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by corinagum** [comment]
Note: this is in progress for JS. Unfortunately teams chef bot isn't eligible for this change yet since embedding is only supported in Open AI right now.

**Comment by corinagum** [comment]
Changing assignee to @Stevenic since he is currently updating samples with breaking changes

**Comment by corinagum** [comment]
These changes have been merged
