### ISSUE TITLE
After deployment vis toolkit getting cannot find restify module 

### ISSUE THREAD

**Issue by Sandeep-FED** [microsoft/teams-ai#539]
I'm trying to deploy and publish the app to teams using teams toolkit, even I have locally tested the echo bot and its totally working fine, but after deploying to Azure its throwing cannot find module restify.

And also the app isn't getting published to Teams.

Sometimes I'm getting dotnev can't find similar error:
Tried running npm i, but it still producing the same error
<img width="669" alt="image" src="https://github.com/microsoft/teams-ai/assets/36669540/7695e4e7-e03a-496d-a592-0836cc019737">

Using JS samples

**Comment by corinagum** [comment]
Is this still causing issues @Sandeep-FED

**Comment by singhk97** [comment]
We have done major revamps to all the samples (both C# and JS) you should try provisioning those samples. Closing issue for now.
