### ISSUE TITLE
npm package updates

### ISSUE THREAD

**Issue by freistli** [microsoft/teams-ai#561]
Hi Team, the current npm package (0.1.0-preview.2) was released 4 months ago and some updates in JS are not reflected. Could you please release an up-to-date npm package so that developers don't need to use private one to get latest changes?

**Comment by garrytrinder** [comment]
+1

**Comment by corinagum** [comment]
Hey guys! We will have a new preview release with LOTS of exciting new changes very soon! Please keep an eye out :)
