### ISSUE TITLE
[C#] Port Vectra to dotnet

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#571]
https://github.com/singhk97/vectra-dotnet

**Comment by corinagum** [comment]
Pending: Needs a package to be ported to dotnet, written by @Stevenic

**Comment by singhk97** [comment]
This is still in progress.

**Comment by singhk97** [comment]
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.Memory.Sqlite - semantic kernel has a connector for sqlite based vector store.

**Comment by singhk97** [comment]
Decided to use [Kernel Memory](https://github.com/microsoft/kernel-memory) as it's the complete RAG solution built for .NET
