### ISSUE TITLE
[Feature Request]: Support multiple connections in Application

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/teams-ai#621]
Authentication can current be configured for a Bot, however the `Application` class only accepts a single settings object in the `authentication` property.

```ts
const app = new Application<ApplicationTurnState>({
   ...,
   authentication: {
     connectionName: "MicrosoftGraph",
     title: "Sign In"
   }
});
```

**Describe the solution you'd like**

Extend the `authentication` property to accept multiple settings objects to obtain access tokens that developers can use to call different APIs easily. It is common for developers to send requests to more than one API from a bot, for example, Microsoft Graph and 3P API.

**Comment by singhk97** [comment]
This has been implemented. You can add multiple auth settings handle user signin for different settings.
https://github.com/microsoft/teams-ai/blob/dad653e19bd21858663ffff22fcd88c9381a0308/js/samples/06.auth.oauth.bot/src/index.ts#L83C1-L88C14
