### ISSUE TITLE
[PY]: change `RateLimited` action to `HttpError` action

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#632]
(https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/AzureOpenAIModerator.ts#L269) we assume any api error to be a rate limit which might be misleading to an developer that may have, for example, entered a bad api key and instead gottten a 401. Should we change the action RateLimited maybe to something like APIError and pass it the error body so the developer can handle it appropriately? Otherwise I would suggest we create more actions and use them appropriately by http status code instead of using RateLimit as a catch all

**Comment by blackchoey** [comment]
@aacebo Is there any conclusion on whether we should change `RateLimitedError` to `APIError` or create more actions based on the status code? If not, I will change `RateLImitedError` to `APIError` based on the assumption that people usually don't have the requirement to handle API errors based on status code. And this can be done with additional logic in the `APIError` handlers.

We can wait before there's explicit request to register handlers for different status code.

**Comment by blackchoey** [comment]
Hi @corinagum @singhk97 , per my previous discussion with @aacebo , the proposed improvement to this is replacing `RateLimited` action with `APIError` action, and provide status code / error response to the action. We will not take the other proposal that creates more actions based on status code.

I want to align with you on the solution before I create a PR for this. So we will improve all 3 SDKs in the same way. Can you share your thoughts to the solution?

**Comment by aacebo** [comment]
close this as your PR was merged @blackchoey
