### ISSUE TITLE
[C#] change `RateLimited` action to `APIError`

### ISSUE THREAD

**Issue by aacebo** [microsoft/teams-ai#634]
(https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/AzureOpenAIModerator.ts#L269) we assume any api error to be a rate limit which might be misleading to an developer that may have, for example, entered a bad api key and instead gottten a 401. Should we change the action RateLimited maybe to something like APIError and pass it the error body so the developer can handle it appropriately? Otherwise I would suggest we create more actions and use them appropriately by http status code instead of using RateLimit as a catch all

**Comment by singhk97** [comment]
#794 fixed.
