### ISSUE TITLE
suggest: add env file for user to add openai keys before debug

### ISSUE THREAD

**Issue by wenytang-ms** [microsoft/teams-ai#672]
**Describe your user scenario**

> when i run the sample, the [sample](https://github.com/microsoft/teams-ai/tree/PYTHON/python/samples/04.ai.a.teamsChefBot) in python branch may add env file before user run debug, user add their openai keys, endpoints or other configurations. 

And once user start local debug the sample app without seeting these keys, user does not know where to add these configuration values.

**Comment by blackchoey** [comment]
Samples now provide `sample.env` to users.
Example: https://github.com/microsoft/teams-ai/pull/1356/files#diff-bcce57a33db45981abe2d60f60c86728d3084d6fe08aff9511953e2da4f52a9d
