### ISSUE TITLE
[C#] Teams parity - meeting events

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#696]
![Image](https://github.com/microsoft/teams-ai/assets/115390646/2850d667-3a7f-4395-9ef0-297f63e6e2db)

![Image](https://github.com/microsoft/teams-ai/assets/115390646/ca2ad76d-d1a4-46c8-be86-7a5b0695c95b)

These scenarios should be supported in the new teams AI library. Some of them are activity handlers, some of them are GET api calls. There's a `teamsInfo` file in the Bot Framework SDK that has all the  meetings-related GET apis. For scenarios supported by it we should be able to simply import and use it. Otherwise we should be able to handle meetings-related events.

**Comment by singhk97** [comment]
There were new activity types added to meetings: https://github.com/microsoft/botbuilder-js/blame/663bc953054ccc603887dcc19bcb0a8d65e7b2b1/libraries/botbuilder/src/teamsActivityHandler.ts#L1247

**Comment by swatDong** [comment]
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L806-L815

- application/vnd.microsoft.readReceipt
- application/vnd.microsoft.meetingStart
- application/vnd.microsoft.meetingEnd
- application/vnd.microsoft.meetingParticipantJoin
- application/vnd.microsoft.meetingParticipantLeave
