### ISSUE TITLE
[Feature Request]: support rich text

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/teams-ai#707]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe your user scenario**

Currently, the SDK regards `activity.text` as input. However, for rich text, `activity.attachments` will contain much more information.

**Describe the solution you'd like**

> Provide a clear and concise description of what you want to happen, with code snippets or pseudo code as applicable.

**Describe alternatives you've considered**

> Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by aacebo** [comment]
@kuojianlu please update this with **describe the solution you'd like**, im not sure by the description what the problem is or how we should support rich text.

**Comment by kuojianlu** [comment]
@aacebo I think the issue is a little out-of-date, because `activity.attachments` is now supported to some extent, like the `TeamsAttachmentDownloader` to download the attachment files.

Close as resolved.
