### ISSUE TITLE
[Python]: BF protocol says that activities of unknown name should be ignored, not thrown as not implemented

### ISSUE THREAD

**Issue by corinagum** [microsoft/teams-ai#711]
Update: I was looking at incorrect branch. Will regroup after looking at correct branch.

**Describe the bug**

According to [Bot Framework protocol](https://github.com/Microsoft/botframework-sdk/blob/main/specs/botframework-activity/botframework-activity.md#event-activity), events that are not of type INVOKE should be ignored by the bot, not responded to with 'Not implemented'

![image](https://github.com/microsoft/teams-ai/assets/14900841/82bd0442-d1eb-4e52-bc94-cc84a21ffb28)

Currently, Teams AI C# has instances of [events not of type invoke that are throwing not implemented](https://github.com/microsoft/teams-ai/blob/cdc2838c7e39be405cb864bcc0abeb235efc2a53/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/Application.cs#L463C11-L479). **This means that if a bot were to receive an activity that does not match channel requirements, it will throw an error instead of ignoring it.**

C# implementation in Botbuilder: https://github.com/microsoft/botbuilder-dotnet/blob/617394d6ff834b0804cceabff2ed9d6e06342cd4/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L191-L194

### Teams AI:
![image](https://github.com/microsoft/teams-ai/assets/14900841/abc02168-3e6f-46e2-9875-6603d635f7e3)

### BF dotnet:
![image](https://github.com/microsoft/teams-ai/assets/14900841/46f9c892-7c5d-462b-9030-6110f624cfe3)

> Provide a clear and concise description of what you expected to happen.

The correct outcome is that the bot will ignore any activities that are unknown (with the exception of invoke activities)

**Comment by aacebo** [comment]
@blackchoey can you confirm we are handling this correctly in python please?

**Comment by aacebo** [comment]
from what I can tell this is working as expected in the python implementation.
