### ISSUE TITLE
[C#] [JS Breaking Changes MVP] Planner Interface

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#715]
- [ ] Implement new planner interface 
  - `Planner.ts`
  - `TestPlanner.ts` (tests should be in the `Microsoft.TeamsAI.Tests` project
- [ ] Update existing OpenAI/AOAI Planner to work with updated interface. We will deprecate it later when the `ActionPlanner` is implemented.

_NOTE:_ Do not implement the `ActionPlanner.ts` and `LLMClient.ts` we will do it later.

**Comment by kuojianlu** [comment]
https://github.com/microsoft/teams-ai/pull/797
