### ISSUE TITLE
[C#] [JS Breaking Changes MVP] Turn State

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#716]
Files to implement/update

- [x] `TurnState.ts` 
- [x] `TestTurnState.ts` equivalent in the test files if needed.
- [x] `MemoryFork.ts`
- [x] `Application.ts` the changes in this class are just to incorporate updated turn state (including ApplicationBuilder)

**Comment by singhk97** [comment]
Update all the samples with the new turn state changes except for Echo bot which has already been implemented.

Look at the changes done in Echo bot here: https://github.com/microsoft/teams-ai/pull/851/files# - looks at the `samples/01.messaging.echoBot` folder. The main changes are to the `Model` classes.

**Comment by lilyydu** [comment]
https://github.com/microsoft/teams-ai/pull/844
https://github.com/microsoft/teams-ai/pull/851
