### ISSUE TITLE
[C#] [JS Breaking changes MVP] Moderator

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#717]
All the code files in the `moderators` folder

- [ ] `AzureOpenAIModerator.ts`
- [ ] `DefaultModerator.ts`
- [ ] `Moderator.ts`
- [ ] `OpenAIModerator.ts`

Prompt Management - All prompt management is now done by the Planner. This impacted the interfaces for both the Planner and Moderator.

**Comment by lilyydu** [comment]
https://github.com/microsoft/teams-ai/pull/805
