### ISSUE TITLE
[C#] [JS Breaking changes MVP] AI class

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#718]
- The changes in the `AI.ts` class should be for the most part self-contained. 
- The new planner interface will have to be implemented already before working on this.
- `jsonschema` npm library is used extensively. .NET should use the equivalent from the `System.Text.Json` if it makes sense. Otherwise will need some discussion on this.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/teams-ai/pull/807
- [x] [No need] Support json schema
```

**Comment by kuojianlu** [comment]
`System.Text.Json` does not support json schema validation. Third-party solutions:
- [Newtonsoft.Json.Schema (paid)](https://www.newtonsoft.com/jsonschema)
- [JsonSchema.Net](https://github.com/gregsdennis/json-everything) which is based on System.Text.Json
- [NJsonSchema](https://github.com/RicoSuter/NJsonSchema)

**Comment by kuojianlu** [comment]
#807
