### ISSUE TITLE
[Feature Request]: Support for multiple storage accounts (e.g. Azure blobs) of conversation chat history

### ISSUE THREAD

**Issue by dannygar** [microsoft/teams-ai#748]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe your user scenario**

The customer has various organizations where storage of the chat history must be securely separated and managed by different security groups. In today's Teams AI library implementation, the storage is configured, initialized and attached to the Bot Teams AI application class before Bot receives the context from Teams. That is, it's impossible to know what storage to use for one organization or another before the context has been made available on each message turn. 
Ideally, it'd be great if the Conversation chat cache can be written into the storage that is determined on every Bot message turn.

**Describe the solution you'd like**

> Provide a clear and concise description of what you want to happen, with code snippets or pseudo code as applicable.

If there is a way to provide the storage factory, that can be overwritten/selected on every context turn, that'd solve this problem.

**Describe alternatives you've considered**

> Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by Stevenic** [comment]
The addition of a storage factory to the Application options and ApplicationBuilder is probably the best approach. The default factory would just use the configured provider but a custom factory could be registered that would have a signature of `(context: TurnContext) => Promise<Storage>` This would be called at the start of the turn prior to loading any state.

**Comment by aacebo** [comment]
since there is now a `turnStateFactory` option to the `Application` class https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/Application.ts#L136 I am closing this.
