### ISSUE TITLE
[Feature Request]: Ask for openai function_call support

### ISSUE THREAD

**Issue by chagong** [microsoft/teams-ai#751]
When use teams-ai to build chatbot, I need teams-ai lib to support openai function_call for scenario like: the bot needs to call external API to get some data for AI to generate response. For example: get the real time weather.

Let me know if it's already supported or planned.

**Comment by corinagum** [comment]
imadilkhalil is correct :) 
The latest function changes from OpenAI 2 weeks ago have been refactored to tools and we are currently in development for this work.
