### ISSUE TITLE
[C#] [JS Breaking changes] Planner: Assisstant Planner

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#798]
https://github.com/microsoft/teams-ai/pull/795/files

**Comment by swatDong** [comment]
OpenAI officially provides Node and Python client sdk, but no .NET. So one pre-requisite is to add http calls for (/assistant, /threads, ...), which does not depend on state/planner interface.

**Comment by lilyydu** [comment]
Also includes two new samples - mathBot sample and orderBot sample.
