### ISSUE TITLE
Offer UI for thumbs up thumbs/down user feedback to developer

### ISSUE THREAD

**Issue by glockstock** [microsoft/teams-ai#80]

**Comment by corinagum** [comment]
I'd be interested in helping out with this one, even if just the UI side. Would need to investigate if developer has any permissions to add UI over messages or if message extension is the best option.

**Comment by govil1811** [comment]
P2

**Comment by corinagum** [comment]
This is now available with feedback loop Powered by AI features. Please see our getting started documentation: Powered by AI

**Comment by SirArnoldB** [comment]
> This is now available with feedback loop Powered by AI features. Please see our getting started documentation: Powered by AI

Documentation link: https://github.com/microsoft/teams-ai/blob/main/getting-started/CONCEPTS/POWERED-BY-AI.md
