### ISSUE TITLE
[JS] Refactor 'AzureOpenAIModerator' to 'AzureContentSafetyModerator'

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#802]
We have different naming conventions in JS and C# for the same moderator.

JS is called `AzureOpenAIModerator` vs C# is `AzureContentSafetyModerator`

Azure's moderation service is called AzureContentSafety, should rename JS for alignment and consistency.

**Comment by singhk97** [comment]
JS reference: https://github.com/microsoft/teams-ai/blob/main/js/packages/teams-ai/src/moderators/AzureOpenAIModerator.ts

C# reference: https://github.com/microsoft/teams-ai/blob/breaking-changes-2/dotnet/packages/Microsoft.TeamsAI/Microsoft.TeamsAI/AI/Moderator/AzureContentSafetyModerator.cs
