### ISSUE TITLE
[JS] Remove incomplete `functions` augmentation

### ISSUE THREAD

**Issue by singhk97** [microsoft/teams-ai#948]

**Comment by lifan0127** [comment]
As I understand `functions` augmentation no longer exists so it may be helpful to remove its references in code comments.

https://github.com/microsoft/teams-ai/blob/c976453a99ee413eb95effa0c48a94ae5c98990f/js/packages/teams-ai/src/planners/ActionPlanner.ts#L91

https://github.com/microsoft/teams-ai/blob/c976453a99ee413eb95effa0c48a94ae5c98990f/js/packages/teams-ai/src/AI.ts#L52
