### ISSUE TITLE
[C#] MathBot and OrderBot - Add support for AzureOpenAI

### ISSUE THREAD

**Issue by lilyydu** [microsoft/teams-ai#957]
associated: #958

**Comment by lilyydu** [comment]
Unable to support until AzureOpenAI provides Assistants support
https://learn.microsoft.com/en-us/answers/questions/1428786/availability-of-openai-assistants-api-on-azure-ope

**Comment by NikhilB95** [comment]
I believe Azure OpenAI has launched Assistants
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant

**Comment by singhk97** [comment]
#1571 #1609
