### ISSUE TITLE
[Bug]: [JS & dotnet] OAuth Connection based message extension auth does not work if not enable SSO

### ISSUE THREAD

**Issue by blackchoey** [microsoft/teams-ai#991]
**Please note: any submissions with insufficient reproducible information will be marked as 'Waiting for customer input' and may be closed is there is no response**

**Describe the bug**

If the Teams app manifest does not enable SSO (removing the `webApplicationInfo` field in the manifest), the OAuth Connection based message extension auth will not work.

**To Reproduce**

1. Download https://github.com/microsoft/teams-ai/tree/main/js/samples/06.auth.oauth.messageExtension
2. Remove `webApplicationInfo` filed in `appPackage/manifest.json`
3. Debug the app
4. Type `profile` to show user profile
5. Message extension shows `We didn't find any matches` instead of displaying the sign in link

**Expected behavior**

The Message Extension should provide a link asking user to login.

**Screenshots**

![image](https://github.com/microsoft/teams-ai/assets/16605901/0ad99f8e-471a-484d-9678-bc35b1659d83)

**Desktop(s) (please complete the following information):**

- OS: [e.g. macOS]

**Smartphone (please complete the following information):**

**Additional context**

The root cause should be our library always use `silentAuth` for query command, which means using Teams SSO.
One idea to solve this is adding an `EnableSSO` setting to authentication settings so developer can control whether to use SSO.

**Comment by singhk97** [comment]
Implemented `enableSso` feature to toggle SSO in sign in flow. This feature should be available in the next minor releases.
